### ISSUE TITLE
[OTHER] remove alert

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#109]
### What would you like to share?

There's an alert when the logout button is clicked, it should be removed.

Remove this line👇🏾
https://github.com/Dun-sin/Whisper/blob/774dcd3c91d6b65c3e3e3ebce6c09e16e646956a/client/src/context/reducers/authReducer.js#L21

> # Before contributing, read 👉🏾 [this](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md) 👈🏾

**Comment by jsvigneshkanna** [comment]
@Dun-sin , please assign me this issue,will fix it

**Comment by jsvigneshkanna** [comment]
@Dun-sin PR- #114
