### ISSUE TITLE
[FEATURE] Add confirmation modal

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#110]
### Description

When a user clicks to log out, there should be a modal asking if they truly want to log out.
This is so that if they accidentally click the logout button, it asks if they are sure they want to log out.

## Your Tasks
- [ ] Create a modal pop-up, that's triggered when a user clicks on the logout button, Should have two options (yes, no)
- [ ] The background for `no` should be `rgb(255 159 28)`

### Screenshots
Logout button
![image](https://user-images.githubusercontent.com/78784850/195838910-b1da0e22-e68b-458a-8144-2bbd83453c73.png)

> # Before contributing, read 👉🏾 [this](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md) 👈🏾

**Comment by FireFoxHD** [comment]
I'll handle this @Dun-sin

**Comment by TanmayBhosale** [comment]
@Dun-sin, I can work on this!

**Comment by Hrx4** [comment]
Hey @Dun-sin  you can assign me this issue , i will solve this.
