### ISSUE TITLE
[FEATURE] Remove change of colour hover effect

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#111]
### Description

When you hover the start button the colour changes, and it has a text underline(the default style for a link), remove that

Element that the change should apply to
https://github.com/Dun-sin/Whisper/blob/774dcd3c91d6b65c3e3e3ebce6c09e16e646956a/client/src/pages/Start.jsx#L21-L29

### Screenshots

![image](https://user-images.githubusercontent.com/78784850/195256674-f4c54708-b4d2-45d5-ae50-03631ba73997.png)

> # Before contributing, read 👉🏾 [this](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md) 👈🏾

**Comment by jsvigneshkanna** [comment]
Please assign me this issue

**Comment by kaustav202** [comment]
I'd like take this up @Dun-sin

**Comment by Dun-sin** [comment]
> I'd like take this up @Dun-sin 

Definitely, thanks for wanting to contribute, Good Luck.

Make sure you follow the rules in the contributing file, or your PR will not be accepted

**Comment by NizarAhamed97** [comment]
Can i get this?
