### ISSUE TITLE
[OTHER] remove signin text

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#116]
### What would you like to share?

Remove the sign-in text in the sign-in page

### Additional information
Here's the element to remove
https://github.com/Dun-sin/Whisper/blob/3e3a255c6a3ac08f342cf8518a5a1238f7fe346d/client/src/pages/Login.jsx#L122

![image](https://user-images.githubusercontent.com/78784850/195552575-3c208c43-55d1-4257-9e05-516a583b66e3.png)

> # Before contributing, read 👉🏾 [this](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md) 👈🏾

**Comment by anuragh2002** [comment]
Hey @Dun-sin I would like to work on it. Can you please assign this issue to me?

**Comment by Dun-sin** [comment]
> Hey @Dun-sin I would like to work on it. Can you please assign this issue to me?

Definitely, thanks for wanting to contribute, Make sure you follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted
Good Luck

**Comment by anuragh2002** [comment]
Also, should I just delete this element or modify it with different text?
