### ISSUE TITLE
[FEATURE] add background colour to search

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#120]
### Description

Change the background colour to the primary colour (already declared in tailwind) for search component.

### Your tasks:
- [ ] Change the background colour by adding `bg-primary` to the div below👇🏾
https://github.com/Dun-sin/Whisper/blob/ef002eb88fdeb9ebe72a1ea42579fe303bc3c72f/client/src/pages/Searching.jsx#L71
- [ ] change the colour for the loading animation (the element below 👇🏾) to `rgb(255 159 28)`
https://github.com/Dun-sin/Whisper/blob/ef002eb88fdeb9ebe72a1ea42579fe303bc3c72f/client/src/pages/Searching.jsx#L72

### Screenshots

![image](https://user-images.githubusercontent.com/78784850/195835081-1279d90b-347d-47e8-9882-36f79dfe581a.png)

> # Before contributing, read 👉🏾 [this](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md) 👈🏾

**Comment by Sayan2908** [comment]
@Dun-sin can you assign it to me?

**Comment by Dun-sin** [comment]
> @Dun-sin can you assign it to me?
> 

Definitely, thanks for wanting to contribute, Make sure you follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted
Good Luck

**Comment by Hrx4** [comment]
is there any specific color for background?

**Comment by Dun-sin** [comment]
> is there any specific color for background?

There is but it's already defined, just do as the issue says

**Comment by Dun-sin** [comment]
> is there any specific color for background?

If you want it, let me know

**Comment by Hrx4** [comment]
ok , you can assign me the issue.

**Comment by Dun-sin** [comment]
> ok , you can assign me the issue.
> 

Great, thanks for wanting to contribute, Make sure you follow the rules [here](https://github.com/Dun-sin/Code-Magic/blob/main/CONTRIBUTING.md#rules), else your PR will rejected and closed. 
Good Luck
