### ISSUE TITLE
[FEATURE] Make the text colour clearer when searching

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#125]
## Your tasks
- [ ] Make the text colour of this page white

here's the element that needs the change👇🏾
https://github.com/Dun-sin/Whisper/blob/01e7d8fbb4a613b0c15d3b1fb1e97db44de389d7/client/src/pages/Searching.jsx#L73

### Screenshots

![image](https://user-images.githubusercontent.com/78784850/195888204-b8ab8933-9470-49d6-a60c-4e35552c0cc7.png)

**Comment by jsvigneshkanna** [comment]
@Dun-sin please assign me this issue

**Comment by Dun-sin** [comment]
> @Dun-sin please assign me this issue

leaving this issue for new contributors

**Comment by jeoffreyduke** [comment]
> > @Dun-sin please assign me this issue
> 
> leaving this issue for new contributors

Could I work on two of your projects? This issue should be easy🙃

**Comment by Dun-sin** [comment]
> > > @Dun-sin please assign me this issue
> > 
> > 
> > leaving this issue for new contributors
> 
> Could I work on two of your projects? This issue should be easy🙃

will leave this for entirely new people

**Comment by Dun-sin** [comment]
> Hey can I do this?

Definitely, thanks for wanting to contribute, Make sure you follow the rules [here](https://github.com/Dun-sin/Code-Magic/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted
Good Luck

**Comment by Dun-sin** [comment]
@Omm2005 an update on this pls? It doesn't take up to 10 minutes to finish this up

**Comment by Omm2005** [comment]
i am so sorry I forgot about this... I have exams and all stuff right now..
I will complete it ASAP!

**Comment by Omm2005** [comment]
Do I have to make a Pull request to new branch in your ?
