### ISSUE TITLE
[FEATURE] save the right room to context

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#126]
### Description

The default room when saving the message to context is 'anon', it should be the roomid generated at the backend

where needs change:
https://github.com/Dun-sin/Whisper/blob/01e7d8fbb4a613b0c15d3b1fb1e97db44de389d7/client/src/components/Chat.jsx#L75

#### Your Tasks
- [ ] Send the room id from the backend
- [ ] Use it for the addmessage dispatch room field

> # Before contributing, read 👉🏾 [this](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md) 👈🏾

**Comment by khanhtranngoccva** [comment]
I can contribute to this, Dunsin!

**Comment by Dun-sin** [comment]
> I can contribute to this, Dunsin!

thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck

**Comment by Dun-sin** [comment]
sorry @khanhtranngoccva this has already been fixed
