### ISSUE TITLE
[FEATURE] change `login anonymously` UI

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#130]
### Description

Make the `login anonymously` button to just a clickable text

- [ ] remove the background
- [ ] add an underline on hover

new:
![image](https://user-images.githubusercontent.com/78784850/195779062-0aa4e42d-eaa4-4b71-94cd-862524fb40a2.png)

### Screenshots

Old:
![image](https://user-images.githubusercontent.com/78784850/195778784-c6fc84bb-7c40-4955-b57c-86e8b370afbf.png)

> # Before contributing, read 👉🏾 [this](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md) 👈🏾

**Comment by najeebkp** [comment]
hi @Dun-sin please assign this to me

**Comment by Dun-sin** [comment]
> hi @Dun-sin please assign this to me

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck
