### ISSUE TITLE
[FEATURE] add stop button 

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#132]
### Description

We have a button to start searching for someone to talk to, but we don't have one for when someone wants to stop searching.

**Tasks**
- [ ] add stop button, should have the same styles as the stop button, but smaller
- [ ] when clicked should stop searching for a a user

**Comment by ays14** [comment]
Hi @Dun-sin , can I take this up?

**Comment by Dun-sin** [comment]
> Hi @Dun-sin , can I take this up? 

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck

**Comment by Dun-sin** [comment]
@ays14 an update on this please?

**Comment by ays14** [comment]
> @ays14 an update on this please?

Hi @Dun-sin , I am working on it. Will finish this over the weekend.

**Comment by mathiasayivor** [comment]
> > @ays14 an update on this please?
> 
> Hi @Dun-sin , I am working on it. Will finish this over the weekend.

@ays14 any updates on this?
