### ISSUE TITLE
[FEATURE] Make the navbar mobile responsive

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#138]
### Description

On smaller screens(mobile), the navigation bar squeezes the rest of the content.

Tasks:
- [ ] Move the navigation bar to the bottom of the screen rather than the side

### Screenshots

![Screenshot_2022-10-15-12-07-11-978_com brave browser](https://user-images.githubusercontent.com/78784850/196017654-ccd9c5b3-3194-4360-ba3b-ca7293e753d0.jpg)

**Comment by Harsh-garg-coder** [comment]
can you assign this issue to me?

**Comment by Dun-sin** [comment]
> can you assign this issue to me?

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck

**Comment by Dun-sin** [comment]
@Harsh-garg-coder an update on this pls

**Comment by Harsh-garg-coder** [comment]
@Dun-sin i will complete this by EOD

**Comment by Dun-sin** [comment]
@Harsh-garg-coder
