### ISSUE TITLE
[FEATURE] Improve on route guard

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#139]
### Description

The current implementation for routing does not make provision for multiple unguarded routes. It would be good for us to have a routing solution, where we can add/remove protection for multiple routes easily.

**Comment by Dun-sin** [comment]
Hmmmm, I don't understand this, explain more

**Comment by mathiasayivor** [comment]
The current implementation. It works but does not provide room for adding multiple unguarded routes. This means multiple `if` statements when we want to add other pages that do not need to be guarded and the code, becomes hacky/messy.
![Screenshot from 2022-10-16 11-12-37](https://user-images.githubusercontent.com/74247733/196032183-d0833b33-cab5-4747-86b0-f3f93afea75e.png)

The proposed structure provides room for adding more unprotected routes (i.e separate registration page, docs page, etc) easily.
![Screenshot from 2022-10-16 11-19-22](https://user-images.githubusercontent.com/74247733/196032374-b4261321-bc8d-433a-a4fd-41ec3b3629e3.png)

**Comment by Dun-sin** [comment]
Alright makes sense
