### ISSUE TITLE
[FEATURE] Improve on user registration flow

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#140]
### Description

The current registration flow makes two requests to the server; The first one is for checking if the user exists and the second is for registering the user if the account does not exist. We can greatly improve on this by doing all those checks at the backend, in a single request.

**Comment by Dun-sin** [comment]
Makes sense, are you working on this one or should I leave it up for other contributions

**Comment by mathiasayivor** [comment]
> Makes sense, are you working on this one or should I leave it up for other contributions

Sure. You can assign me.
