### ISSUE TITLE
[FEATURE] Write better code

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#15]
If you find a bad code, write a cleaner and better code

**Comment by mathiasayivor** [comment]
I think we'd need a coding style guide-ish?

**Comment by Dun-sin** [comment]
do you have suggestions on how?

**Comment by mathiasayivor** [comment]
Well, most of it could be done with eslint + editorconfig...
Then we add a STYLE_GUIDE.md file for specific instructions.

**Comment by Dun-sin** [comment]
Alright I will let you take this, create a separate issue so you can tag this specifically

**Comment by Vishrut19** [comment]
Hey @Dun-sin what do you want me to do in this issue ? If this issue is still open

**Comment by Dun-sin** [comment]
> Hey @Dun-sin what do you want me to do in this issue ? If this issue is still open

read, the original issue
this is based on refactoring
