### ISSUE TITLE
[FEATURE] <Add favicon>

### ISSUE THREAD

**Issue by gambhirsharma** [Dun-sin/Whisper#153]
### Description

Whisper website uses the Default React Favicon. Change it with a custom-made one to make the website more appealing to new users. :)

**Comment by omagr** [comment]
please assign it to me i will add custom made favicon

**Comment by Dun-sin** [comment]
> please assign it to me i will add custom made favicon

hi, thanks kindly send the designs you do for one to be picked

**Comment by omagr** [comment]
![logos](https://user-images.githubusercontent.com/88016895/196780307-a0ee51e0-8e3e-414f-a89d-d036730a2e6a.png)
so I made these logos, what's your thought?

**Comment by Dun-sin** [comment]
> ![logos](https://user-images.githubusercontent.com/88016895/196780307-a0ee51e0-8e3e-414f-a89d-d036730a2e6a.png) so I made these logos, what's your thought?

The middle one is definitely cool, do you think you can add a vector/image related to being anonymous in the hole of the lettper "P"

**Comment by Dun-sin** [comment]
> > ![logos](https://user-images.githubusercontent.com/88016895/196780307-a0ee51e0-8e3e-414f-a89d-d036730a2e6a.png) so I made these logos, what's your thought?
> 
> The middle one is definitely cool, do you think you can add a vector/image related to being anonymous in the hole of the letter “P”

I think just a question mark(?) will do

**Comment by omagr** [comment]
> > > ![logos](https://user-images.githubusercontent.com/88016895/196780307-a0ee51e0-8e3e-414f-a89d-d036730a2e6a.png) so I made these logos, what's your thought?
> > 
> > 
> > The middle one is definitely cool, do you think you can add a vector/image related to being anonymous in the hole of the letter “P”
> 
> I think just a question mark(?) will do

alright!
![Group 24](https://user-images.githubusercontent.com/88016895/196855572-7bf5a696-098e-461d-a021-61c37bca6ba3.png)
something like this?

**Comment by Dun-sin** [comment]
> > > > ![logos](https://user-images.githubusercontent.com/88016895/196780307-a0ee51e0-8e3e-414f-a89d-d036730a2e6a.png) so I made these logos, what's your thought?
> > > 
> > > 
> > > The middle one is definitely cool, do you think you can add a vector/image related to being anonymous in the hole of the letter “P”
> > 
> > I think just a question mark(?) will do
> 
> alright!
> ![Group 24](https://user-images.githubusercontent.com/88016895/196855572-7bf5a696-098e-461d-a021-61c37bca6ba3.png)
> something like this?

Yes!

**Comment by Dun-sin** [comment]
@omagr want to add it to the project?

**Comment by omagr** [comment]
yes, i am doing it right now!

**Comment by Dun-sin** [comment]
> yes, i am doing it right now!
> 

Yeah their are some rules in this repo, kindly check them before making a PR, here👇🏽

https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules)
