### ISSUE TITLE
[FEATURE] Persist app data to the database

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#159]
### Description

Currently, chats + other data are only being stored in memory and as a result, we would loose all data when there is any change on the backend (server restarts, server crashes, etc).

 We need to start saving chats + other necessities in the database to avoid data loss in case of any changes on the server.

**Comment by Dun-sin** [comment]
@mathiasayivor, have you started this? Was thinking to start, just to know.

**Comment by mathiasayivor** [comment]
Yh, I started working on it.
