### ISSUE TITLE
[FEATURE] <Adding About Page>

### ISSUE THREAD

**Issue by Kritika30032002** [Dun-sin/Whisper#164]
### Description

It will describe the use of website that What is website all about.

Assign this to me.

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>

**Comment by Dun-sin** [comment]
won't fix this, thanks for creating an issue tho
