### ISSUE TITLE
[BUG] refreshing crashes the searching/chatting page

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#165]
### Description

When a user is chatting or searching for a user, if they refresh, the app crashes unless they go back to the home page

### Screenshots

![image](https://user-images.githubusercontent.com/78784850/196754534-26fbb7e6-afdb-46f1-86ed-622b8c04253b.png)

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>

**Comment by mathiasayivor** [comment]
This is a vercel issue.

**Comment by Dun-sin** [comment]
> This is a vercel issue.

yeah, i don't know what caused it, but creating an issue so i can remember for later

**Comment by mathiasayivor** [comment]
@Dun-sin Let me try this one...

**Comment by Dun-sin** [comment]
> @Dun-sin Let me try this one...

On vercel?

**Comment by mathiasayivor** [comment]
I mean a fix

**Comment by Dun-sin** [comment]
> I mean a fix

Yeah okay, I think it has to do with the routes because this wasn't a problem before

**Comment by mathiasayivor** [comment]
> > I mean a fix
> 
> Yeah okay, I think it has to do with the routes because this wasn't a problem before

No, it's a vercel issue...

**Comment by Dun-sin** [comment]
> > > I mean a fix
> > 
> > Yeah okay, I think it has to do with the routes because this wasn't a problem before
> 
> No, it's a vercel issue...

It's weird because there really wasn't an issue like this before, maybe I messed with something in vercel.

I will check it

**Comment by mathiasayivor** [comment]
its the vercel.json file I guess

**Comment by mathiasayivor** [comment]
we're missing one
