### ISSUE TITLE
[FEATURE] add quote reply

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#167]
### Description

Add the ability for users to quote reply a message

Like GitHub, for example👇🏾

### Screenshots

![image](https://user-images.githubusercontent.com/78784850/196756844-e707a709-b74f-4c05-aeef-dc26ca0a264f.png)

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>

**Comment by drvnprgrmr** [comment]
Yeah I want to be assigned to this.

**Comment by Dun-sin** [comment]
> Yeah I want to be assigned to this.

Okay, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Code-Magic/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck

**Comment by Deva-1903** [comment]
Can I work on this issue @Dun-sin ?

**Comment by Dun-sin** [comment]
> Can I work on this issue @Dun-sin ?

Okay, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck

**Comment by Deva-1903** [comment]
> Yeah I want to be assigned to this.

lol

**Comment by Deva-1903** [comment]
> > Can I work on this issue @Dun-sin ?
> 
> Okay, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

ok
