### ISSUE TITLE
[FEATURE] better scroll when chatting

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#168]
### Description

The scroll doesn't look good, because it's the default scrollbar

**Tasks**
- [ ] reduce the side of the scroll bar and thumb
- [ ] change the colour to fit the application theme

### Screenshots

![image](https://user-images.githubusercontent.com/78784850/196758079-752b9a42-b717-4839-81b3-001627cfbc09.png)

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>

**Comment by charandevreddy** [comment]
can you assign me this?

**Comment by Dun-sin** [comment]
> can you assign me this?

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck

**Comment by psavvaidis** [comment]
Hello, I'd like to give it a try

**Comment by psavvaidis** [comment]
Thanks, I'm on it

**Comment by psavvaidis** [comment]
Hello again, quick question. It is referred in the rules not to change the package.json. However I have found a good amount of npm packages solving our problem. How can I push a working solution without changing the dependencies?

It's my first push, I'm not even sure if this the place to put this question, sorry in advance

**Comment by Dun-sin** [comment]
> Hello again, quick question. It is referred in the rules not to change the package.json. However I have found a good amount of npm packages solving our problem. How can I push a working solution without changing the dependencies?
> 
> It's my first push, I'm not even sure if this the place to put this question, sorry in advance

what does the package do?

**Comment by psavvaidis** [comment]
it the [react-custom-scrollbars-2](https://www.npmjs.com/package/react-custom-scrollbars-2) 
it does everything I need for the issue

**Comment by Dun-sin** [comment]
> it's the [react-custom-scrollbars-2](https://www.npmjs.com/package/react-custom-scrollbars-2) it does everything I need for the issue

yeah okay, you can add package.json only if you added something that updates the package

**Comment by psavvaidis** [comment]
yeah, I'm not messing with other dependency versions

**Comment by psavvaidis** [comment]
Hey, a quick update. I've hidden the thumb, having some trouble with the coloring, sorry for the delay.

**Comment by Dun-sin** [comment]
> Hey, a quick update. I've hidden the thumb, having some trouble with the coloring, sorry for the delay.

Thanks for the update👍🏽

**Comment by Dun-sin** [comment]
@psavvaidis update? It's been open for too long

**Comment by psavvaidis** [comment]
Hey,

 I'm still working on it. There has been a mixup with tailwind I think. The scrolling works of Firefox and the color change in Chrome. So, I am trying to figure out the bug.

 If you feel there is someone else that can do it faster, I am OK to be unassigned. I'll keep working on it anyways, it's an interesting problem.

**Comment by Dun-sin** [comment]
hi @psavvaidis what's up with this?

**Comment by stephenokyere233** [comment]
@Dun-sin I could hide the scrollbar if you'd want that

**Comment by Dun-sin** [comment]
> @Dun-sin I could hide the scrollbar if you'd want that

Sure do that, thanks

**Comment by stephenokyere233** [comment]
> > @Dun-sin I could hide the scrollbar if you'd want that
> 
> Sure do that, thanks 

Trying to do that now buh I'm not getting a chat buddy i just wanna see if what i did worked

**Comment by Dun-sin** [comment]
> > > @Dun-sin I could hide the scrollbar if you'd want that
> > 
> > Sure do that, thanks 
> 
> Trying to do that now buh I'm not getting a chat buddy i just wanna see if what i did worked

You are production, you have to follow the steps for it to work in production and also you need to open a private browser so you can connect with yourself and test things out

**Comment by stephenokyere233** [comment]
It's been fixed already not by me tho, I checked

**Comment by Dun-sin** [comment]
> It's been fixed already not by me tho, I checked

really? wow didn't know, thanks for letting me know

**Comment by stephenokyere233** [comment]
Yeah sure
