### ISSUE TITLE
[FEATURE] Add markdown support for messages

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#169]
### Description

It would be great to add markdown support so that users can easily format their messages

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>

**Comment by Dun-sin** [comment]
Don't understand this issue

**Comment by mathiasayivor** [comment]
> Don't understand this issue

We enable users to use markdown syntax in their messages.
Almost every modern chat app has some form of markdown syntax support for basic formatting...
i.e
**For bolding text**,
_Italics_,
~line through~
etc

**Comment by Dun-sin** [comment]
> > Don't understand this issue
> 
> We enable users to use markdown syntax in their messages.
> Almost every modern chat app has some form of markdown syntax support for basic formatting...
> i.e
> **For bolding text**,
> _Italics_,
> ~line through~
> etc

Ohhh, got it now

**Comment by Teejay128** [comment]
## Yo, @Dun-sin , can i have this task

There is this library called [marked ](https://www.npmjs.com/package/marked) for adding markdown support

I have used it before on a personal project and I think it will work well for this task

**Comment by Dun-sin** [comment]
> ## Yo, @Dun-sin , can i have this task
> 
> There is this library called [marked ](https://www.npmjs.com/package/marked) for adding markdown support
> 
> I have used it before on a personal project and I think it will work well for this task

Hi, Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck

**Comment by Teejay128** [comment]
## Yo @Dun-sin 

So I did some research and I am going to be using this library called showdown...
I have chosen the backend since I am more familiar with it.

### Running into an issue with the connection
The project is running on my localhost, but I can't seem to make a connection for some reason
![Screenshot 2023-03-01 025219](https://user-images.githubusercontent.com/104542152/222025420-a706f427-2515-41df-958d-73f77eac8a0d.png)
I tried using 2 different browsers and using private mode with the same browser, but it's not working

**Comment by Teejay128** [comment]
## Still not working...

I tried running the server manually(without using docker)
I also successfully connected to MongoDB
![Screenshot 2023-03-01 191446](https://user-images.githubusercontent.com/104542152/222226761-a187fd1c-963c-4626-a023-65f7abff8f64.png)

I'll keep you posted on any updates sha
But it will probably take a while, I am going to work on some personal projects, peace 👍🏾

**Comment by Dun-sin** [comment]
> ## Still not working...
> 
> I tried running the server manually(without using docker)
> I also successfully connected to MongoDB
> ![Screenshot 2023-03-01 191446](https://user-images.githubusercontent.com/104542152/222226761-a187fd1c-963c-4626-a023-65f7abff8f64.png)
> 
> I'll keep you posted on any updates sha
> But it will probably take a while, I am going to work on some personal projects, peace 👍🏾 

Did you check the console error

**Comment by Dun-sin** [comment]
@Teejay128 what's up with this?
