### ISSUE TITLE
[FEATURE] Add emoji picker

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#170]
### Description

Add an emoji picker to enable users to easily use emojis in messages

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>

**Comment by Dun-sin** [comment]
It actually works by default!!!

**Comment by mathiasayivor** [comment]
> It actually works by default!!!

I mean something like this:
![Screenshot from 2022-10-19 17-36-22](https://user-images.githubusercontent.com/74247733/196764491-fb351699-8b55-489f-88ed-fa6d3d5351bb.png)
 
 So that users can easily pick emojis

**Comment by Dun-sin** [comment]
> > It actually works by default!!!
> 
> I mean something like this:
> ![Screenshot from 2022-10-19 17-36-22](https://user-images.githubusercontent.com/74247733/196764491-fb351699-8b55-489f-88ed-fa6d3d5351bb.png)
>  
>  So that users can easily pick emojis

Ohh, you mean reactions!! 😂
