### ISSUE TITLE
[FEATURE] Automatically focus message input when `Edit` is clicked

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#172]
### Description

Currently, you have to manually click on the message input when you click on `Edit` and it's not a good UX. The message input should be automatically focused when users click on `Edit`

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>
