### ISSUE TITLE
[OTHER] Show github greetings to new members only

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#173]
### What would you like to share?

@Dun-sin is it possible to show GH greetings to new members only when creating new issues? The messages are too much

**Comment by Dun-sin** [comment]
> ### What would you like to share?
> 
> @Dun-sin is it possible to show GH greetings to new members only when creating new issues? The messages are too much
> 
> ### Additional information
> 
> _No response_

That's because you create too many issues🤣🤣🤣

But yeah it is, had that before, people forget about the rules so brought this one back, plus it also changes
