### ISSUE TITLE
[FEATURE] Add husky

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#175]
### Description

We're getting inconsistent code formatting when new PRs are created, and it makes reviewing new changes difficult. With husky, we can set up a git pre-commit hook for formatting code with prettier to ensure consistent code formatting.

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>

**Comment by Dun-sin** [comment]
Yeah I can just repeat the same husky used in code Magic
