### ISSUE TITLE
[FEATURE] Use modal for Logout instead of native alert

### ISSUE THREAD

**Issue by Manethpak** [Dun-sin/Whisper#177]
### Description

When logging out, the app use the browser's alert to confirm. We could make this better using customize dialog/modal instead for better UI. 
I could work on this.

### Screenshots

![image](https://user-images.githubusercontent.com/58499300/196907442-0148a62f-32d3-4942-9302-0a61e9a917fa.png)

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>

**Comment by Dun-sin** [comment]
@Manethpak pls also add the modal for closing chats

**Comment by Manethpak** [comment]
I'll worked on it!

**Comment by mathiasayivor** [comment]
@Manethpak any updates on this?

**Comment by Manethpak** [comment]
@mathiasayivor Just got the time to work on it, will be done by today!
