### ISSUE TITLE
[DOCS] Update logo in README

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#178]
### Description

The current logo in the main README is not up to date (#176). It needs to be updated asap

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>

**Comment by JatinSingh08** [comment]
Hey @mathiasayivor @Dun-sin , can you assign this to me. I would love to work on this.

**Comment by Dun-sin** [comment]
> Hey @mathiasayivor @Dun-sin , can you assign this to me. I would love to work on this.

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck

**Comment by JatinSingh08** [comment]
@Dun-sin, Can I get the updated logo to add that ?

**Comment by Dun-sin** [comment]
> @Dun-sin, Can I get the updated logo to add that ?

Right sorry, check this issue #153 and get the icon from it

**Comment by Dun-sin** [comment]
> @Dun-sin, Can I get the updated logo to add that ?

Right sorry, here you go

Just replace the link with the one in the readme

https://user-images.githubusercontent.com/88016895/196855572-7bf5a696-098e-461d-a021-61c37bca6ba3.png
