### ISSUE TITLE
[FEATURE] Add cancel editing button

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#182]
### Description

When editing a message, there should be a button to cancel editing.

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>
