### ISSUE TITLE
[FEATURE] Indicate the particular message being edited

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#183]
### Description

Currently, the user doesn't know which message is being edited and it's not a good UX.

When editing a message, there should be an indicator showing which message is being edited

this is a full stack issue, it should do the following:
— have a message show edited in the frontend and backend, frontend with displaying the edit (to the receiver) and the message schema having an edit true property (field)
— it should have an edit icon
— store the previous message in the backend

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>

**Comment by ChavvaNarayana** [comment]
Sounds good to me. I'm willing to contribute.
Please assign it to me.

**Comment by t-trafer** [comment]
Hey @Dun-sin  i would like to work on this

**Comment by Dun-sin** [comment]
> Hey @Dun-sin i would like to work on this

you have your first warning, don't spam else you will be blocked

**Comment by t-trafer** [comment]
my bad, was just going through the open issues. where can i read code of conduct here?

**Comment by t-trafer** [comment]
let me know if i can work on this now? @Dun-sin would love to contribute here

**Comment by Dun-sin** [comment]
> let me know if i can work on this now? @Dun-sin would love to contribute here

sure, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
