### ISSUE TITLE
Need Improvmen in message page

### ISSUE THREAD

**Issue by rahul152-ai** [Dun-sin/Whisper#184]
### Description

I think the UI of the chat Page needs some improvement Because after some messages they started flooting  

### Screenshots

![Screenshot (14)](https://user-images.githubusercontent.com/77874363/197216697-8bad6b93-306a-4f82-9aaf-159ee21e3e2d.png)

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>

**Comment by rahul152-ai** [comment]
I want to work on this issue, so please assign this issue to me

**Comment by Dun-sin** [comment]
Sorry, this has been fixed. Feel free to look around for other issues or report any!!
