### ISSUE TITLE
[FEATURE] Add shortcuts keys

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#186]
### Description

Users may want to quickly perform certain actions (e.g #185) and it would be great to provide shortcut keys for such actions instead of users doing a lot of clicks

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>

**Comment by Cor4zon** [comment]
@Dun-sin Could you add checklist of these shortcuts?

**Comment by Dun-sin** [comment]
> @Dun-sin Could you add checklist of these shortcuts?

Right:
ctrl + c = close a chat
ctrl + n = new partner and close chat

this are the shortcuts for now
