### ISSUE TITLE
[BUG] Users are not removed from waiting list on logout

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#187]
### Description

Users are not removed from the waiting list after logging out and as a result, new users are getting matched to ghost users

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>

**Comment by Dun-sin** [comment]
I think this should be left, in case the user just wanted to switch devices, if they get paired whoever that was on the other end can just leave

**Comment by mathiasayivor** [comment]
That's a good idea, but not all users have that intention (i.e anonymous users) and it doesn't feel good to be paired with a ghost (a logged-out user that is still on the waiting list).

Besides, switching devices is just a matter of logging in with your email on the new device and your chat data would be restored.
For pairing, the user can still get paired the moment they click on the `Start` button after logging in on the new device.

**Comment by Dun-sin** [comment]
> That's a good idea, but not all users have that intention (i.e anonymous users) and it doesn't feel good to be paired with a ghost (a logged-out user that is still on the waiting list).
> 
> Besides, switching devices is just a matter of logging in with your email on the new device and your chat data would be restored.
> For pairing, the user can still get paired the moment they click on the `Start` button after logging in on the new device.

But not all anonymous users have that intention either.

I still vote for letting it be

**Comment by mathiasayivor** [comment]
> But not all anonymous users have that intention either.

I didn't get this...

**Comment by Dun-sin** [comment]
> > But not all anonymous users have that intention either.
> 
> I didn't get this...
> 
> 

You said not every user has the intention of logging out to switch to another device.

I'm saying not every user has the intention to not do that.

In programming format
!LoginForSwitch
!!LoginForSwitch

**Comment by mathiasayivor** [comment]
I still strongly advise against this feature, or else we'd end up with a lot of logged-out users still on the waiting list.
Although there is a feature for stopping searching in #132, some users may just want to click on `Logout` instead of clicking on `Stop searching` and then `Logout`.

Instead, there should be an option for email users to choose if they still want to be searching whiles they're logged out. This makes it suitable for both `!LoginForSwitch && !!LoginForSwitch`

**Comment by Dun-sin** [comment]
> I still strongly advise against this feature, or else we'd end up with a lot of logged-out users still on the waiting list. Although there is a feature for stopping searching in #132, some users may just want to click on `Logout` instead of clicking on `Stop searching` and then `Logout`.
> 
> Instead, there should be an option for email users to choose if they still want to be searching whiles they're logged out. This makes it suitable for both `!LoginForSwitch && !!LoginForSwitch`

i don't think it's going to be that way, they may eventually get paired with themselves, but they won't be on the waiting list for a long time, but sure, let's add this as a feature, they can just search again.
