### ISSUE TITLE
[FEATURE] Enable updating of email for anonymous users

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#188]
### Description

When a user logs in anonymously, the user must first log out before being able to log in with their email.
But what if the anonymous user wants to update/add email to enable them to use features of email users (i.e add friends, log out without losing chats, etc) without losing the current chat?

We need to add the option for users to update their email after logging in.

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>

**Comment by ChavvaNarayana** [comment]
Sounds good to me. I'm willing to contribute.
Please assign it to me.
