### ISSUE TITLE
[FEATURE] ESC key should cancel editing

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#189]
### Description

There's a cancel button for canceling editing, but on devices that uses a physical keyboard, having key shortcut for this will make it easier to use. 

Related to #186

**Comment by Dun-sin** [comment]
<h1>It's great having you contribute to this project by creating an issue</h1> Make sure you are assigned to this before you work on it and you read the <a href="https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md">Contributing.md file</a>, Thank you! Welcome to the community :nerd_face:<p></p>

**Comment by KidesLeo** [comment]
Just found this project, cool stuff! Going to start working on this, assignment is appreciated.

**Comment by Dun-sin** [comment]
> Just found this project, cool stuff! Going to start working on this, assignment is appreciated.

okay, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Code-Magic/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck

**Comment by KidesLeo** [comment]
Is it alright if I go on ahead and clear the input when ESC key is pressed during normal typing? It will cancel editing and clear the input `if isEditing`  otherwise it will just clear the input. Both will set typing to false.

I think that's standard behaviour.

**Comment by Dun-sin** [comment]
> Is it alright if I go on ahead and clear the input when ESC key is pressed during normal typing? It will cancel editing and clear the input `if isEditing`  otherwise it will just clear the input. Both will set typing to false.
> 
> I think that's standard behaviour.

No stick with the issue above, if you want that as an feature, create a separate issue🙌🏽
