### ISSUE TITLE
[FEATURE] The sidebar tab navigation buttons are too close

### ISSUE THREAD

**Issue by KANE-99** [Dun-sin/Whisper#191]
### Description

A small gap will make it look better
Before:
<img width="183" alt="image" src="https://user-images.githubusercontent.com/42038491/197337014-858103b1-e959-4f51-8d24-62ee28753f34.png">
After:
<img width="183" alt="image" src="https://user-images.githubusercontent.com/42038491/197338247-796e0fd6-1f7e-4a4e-b331-b30b845b77d8.png">

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by sano2019** [comment]
I could take this if possible :)

**Comment by KANE-99** [comment]
I am already working on it :)

**Comment by sano2019** [comment]
Ah my bad, thought you were raising the issue for others to work on :) GL!

**Comment by Dun-sin** [comment]
> I could take this if possible :)

You can, but make sure you follow the rules in the contributing file, else your PR will not be accepted.

Good luck

**Comment by sano2019** [comment]
> > I could take this if possible :)
> 
> You can, but make sure you follow the rules in the contributing file, else your PR will not be accepted.
> 
> Good luck

I think @KANE-99 is already covering this, @Dun-sin. If for some reason their contribution is ineligible, I will work on this so just let me know :)

**Comment by Dun-sin** [comment]
> > > I could take this if possible :)
> > 
> > You can, but make sure you follow the rules in the contributing file, else your PR will not be accepted.
> > 
> > Good luck
> 
> I think @KANE-99 is already covering this, @Dun-sin. If for some reason their contribution is ineligible, I will work on this so just let me know :) 

Yeah it's ineligible, hence my giving it to you😁
