### ISSUE TITLE
[FEATURE] Improve on theming

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#193]
### Description

Enable users to switch to dark/light modes easily.
This should be easy to implement with tailwindcss

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

**Comment by udaykahar** [comment]
Hey, I would like to Contribute to this Project , please assign it to me...

**Comment by Dun-sin** [comment]
> Hey, I would like to Contribute to this Project , please assign it to me...

Definitely, thanks for wanting to contribute, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck

**Comment by udaykahar** [comment]
hey i'm having trouble in setting up the project in my machine

**Comment by mathiasayivor** [comment]
Have you followed the steps provided in CONTRIBUTING section?

If yes, what issue are you having?

**Comment by Dun-sin** [comment]
@udaykahar an update here pls?

**Comment by nkirukka** [comment]
Has this issue been worked on? I'd like to implement this.

**Comment by Dun-sin** [comment]
sure @nkirukka, it's all yours, just make sure you read the contributing file.

Good Luck

**Comment by nkirukka** [comment]
Hello @Dun-sin 

I’m nearly done with this but I have a few questions.

Would you like me to add the theme switch to the top of the page or include it in system settings?

**Comment by Dun-sin** [comment]
> Hello @Dun-sin 
> 
> I’m nearly done with this but I have a few questions.
> 
> Would you like me to add the theme switch to the top of the page or include it in system settings? 
> 

Hi, sorry for the late reply.

Adding it in system settings is the best option, thank you
