### ISSUE TITLE
[FEATURE] Add notification system

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#194]
### Description

It would be nice to add a notification system to the app, to get notified on certain events like: `new message`, `paired`, `chat closed`, etc.

- [x] Play notification sounds on: `new message`, `chat closed` and `paired` events
- [ ] Users can enable/disable notifications

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by mathiasayivor** [comment]
@Dun-sin I wasn't done with this pr...

**Comment by Dun-sin** [comment]
> @Dun-sin I wasn't done with this pr...

You didn't say so..... I thought the draft was an accident because I got no comment on what to do with it

**Comment by mathiasayivor** [comment]
> > @Dun-sin I wasn't done with this pr...
> 
> You didn't say so..... I thought the draft was an accident because I got no comment on what to do with it

Aight. Uploaded the new changes in #201
