### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by Adelabuadeleke** [Dun-sin/Whisper#198]
### What would you like to share?

Hello, so i can see the backend folder structure of this project, has just models, and all other code are in the index.js file, i'd suggest the folder structure broken down to the MVC(Models, Views and Controllers)  approached, it helps modularize the code, it also improves readability and scalability, i'd love to work on it, you can assign this to  me to work on.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by mathiasayivor** [comment]
@Adelabuadeleke I'm a bit confused in terms of how you plan on creating an MVC structure, as this is a more API-based app,
can you provide an overview of how you plan on structuring the backend folder?

**Comment by Adelabuadeleke** [comment]
@mathiasayivor sorry my bad, I meant creating a controllers and routes folder structure and modularizing similar functionalities into controllers and and routes, I hope that clarified what I meant?

**Comment by Dun-sin** [comment]
> 

Hi @Adelabuadeleke, just seeing this issue and I get what you meant, you can go ahead and work on this if you still want to.

Thank you

**Comment by Adelabuadeleke** [comment]
Sure, I am still very much interested in working on this, thanks for the go ahead.👍🏾

**Comment by Dun-sin** [comment]
> Sure, I am still very much interested in working on this, thanks for the go ahead.👍🏾

Awesome, just please follow the project rules in contributing.md

**Comment by Dun-sin** [comment]
Hi @Adelabuadeleke are you still interested in this issue?

**Comment by Adelabuadeleke** [comment]
Sure @Dun-sin I'm still very much interested in this issue, I've been very occupied lately, but I'd work on it before the end of the month, if you are ok with that.

**Comment by Dun-sin** [comment]
> Sure @Dun-sin I'm still very much interested in this issue, I've been very occupied lately, but I'd work on it before the end of the month, if you are ok with that.

It's been over a month already tho🤔

**Comment by Adelabuadeleke** [comment]
Yeah, apologies for that, been in the middle of sch exams that's why I haven't had the time to work on it.

**Comment by Dun-sin** [comment]
> Yeah, apologies for that, been in the middle of sch exams that's why I haven't had the time to work on it.

Understandable, hope it can get done before the start of February

**Comment by Adelabuadeleke** [comment]
Sure, I can do that.
