### ISSUE TITLE
[FEATURE] add UI for friends section

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#210]
### Description
this issue depends on when issue #213 is done

Follow the UI for the friends section

the red background color is: #FF3A46
the red profile background color is: #B42B33

### Screenshots

![image](https://user-images.githubusercontent.com/78784850/197961848-7dac1993-f4d4-4793-be25-e58b1cdd6763.png)

### Additional information

There's already a friends component available to use
https://github.com/Dun-sin/Whisper/blob/main/client/src/pages/Friends.jsx

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

**Comment by mathiasayivor** [comment]
@Dun-sin was the screenshot done with a design tool?

**Comment by Dun-sin** [comment]
@mathiasayivor no i used the screenshot tool of firefox

**Comment by mathiasayivor** [comment]
> @mathiasayivor no i used the screenshot tool of firefox

So why not just push the changes ? 😅😂

**Comment by mathiasayivor** [comment]
I like the new icons btw

**Comment by mathiasayivor** [comment]
Wondering how it would look on mobile devices 🤔

**Comment by Dun-sin** [comment]
> > @mathiasayivor no i used the screenshot tool of firefox
> 
> So why not just push the changes ? 😅😂

No that's from figma lol

**Comment by Dun-sin** [comment]
> I like the new icons btw

It's always been the icon, but I forgot the icon pack I used in figma when I started building this🤣

I have to find it

**Comment by stephenokyere233** [comment]
@Dun-sin I'd love to work on this but first could I see the mobile preview?

**Comment by Dun-sin** [comment]
> @Dun-sin I'd love to work on this but first could I see the mobile preview?

I will do this issue
