### ISSUE TITLE
Inform user for lack of connection to the server

### ISSUE THREAD

**Issue by psavvaidis** [Dun-sin/Whisper#211]
### Description

Let the user know when there is no connection to the server in the Search View

Tasks
* [ ] Display a message that informs the user there is no Connection
* [ ] Hide the default message/search button
* [ ] Try reconnecting in the background

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
404 as in page not found? does that help with getting info on when the server is down?

**Comment by psavvaidis** [comment]
sorry, I meant 503 (Unavailability)

**Comment by Dun-sin** [comment]
> sorry, I meant 503 (Unavailability)

how would you detect that

**Comment by psavvaidis** [comment]
Going through the [docs](https://socket.io/docs/v4/client-api/#manageropencallback) I found that the socket manager returns error when calls the `open` function.

This is the socket object when server is down
![Socket object](https://user-images.githubusercontent.com/68665285/198001610-7391aa27-8361-48d1-b95b-c477b338c8c0.png)

Consequently, in `BuddyMatcher.jsx` we get `socket.connected = false`. In this case, we can output a message in `BuddyMatcher.jsx:59`, before `if(isFound)` and `return`.

**Comment by Dun-sin** [comment]
> Going through the [docs](https://socket.io/docs/v4/client-api/#manageropencallback) I found that the socket manager returns error when calls the `open` function.
> 
> This is the socket object when server is down ![Socket object](https://user-images.githubusercontent.com/68665285/198001610-7391aa27-8361-48d1-b95b-c477b338c8c0.png)
> 
> Consequently, in `BuddyMatcher.jsx` we get `socket.connected = false`. In this case, we can output a message in `BuddyMatcher.jsx:59`, before `if(isFound)` and `return`.

Which means an internal server error has to be thrown, and we need an internal server error page(503) to redirect the user to

**Comment by psavvaidis** [comment]
Now that I think of it, the implementation is only on the client side. Server cannot do much if the client can't reach it in the first place. A 503 page can be useful if the client is connected to the server and the server cannot provide service.

**Comment by psavvaidis** [comment]
Would you like me to close the Issue and open a new one?

**Comment by Dun-sin** [comment]
> Would you like me to close the Issue and open a new one?

you can edit this issue

**Comment by Dun-sin** [comment]
Hi @psavvaidis still interested in working on this?

**Comment by mathiasayivor** [comment]
@Dun-sin Let me work on this
