### ISSUE TITLE
[FEATURE] Add option to copy messages

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#221]
### Description

Currently, you'd have to manually select each character in a message to copy. There should be an option to copy the whole message content.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by NeilAn99** [comment]
Hi, I would like to work on this.

**Comment by NeilAn99** [comment]
Hi, how can I test it so 2 people can connect and talk to each other? When I open 2 windows, it is stuck on searching.

**Comment by Dun-sin** [comment]
> Hi, how can I test it so 2 people can connect and talk to each other? When I open 2 windows, it is stuck on searching.
> 

You have to connect the database

**Comment by NeilAn99** [comment]
I have started both the client and server with npm start and have connected the database:
![image](https://user-images.githubusercontent.com/54966170/198206146-45777e9e-d672-4c3b-8ae4-ae0d7190a3b8.png)
Is this correct?

**Comment by Dun-sin** [comment]
> I have started both the client and server with npm start and have connected the database: ![image](https://user-images.githubusercontent.com/54966170/198206146-45777e9e-d672-4c3b-8ae4-ae0d7190a3b8.png) Is this correct?

yes it is

**Comment by NeilAn99** [comment]
any idea why i'm getting the following errors?
![image](https://user-images.githubusercontent.com/54966170/198208453-85657d08-eab2-4cf7-adf8-b509bf732caf.png)

**Comment by Dun-sin** [comment]
> any idea why i'm getting the following errors? ![image](https://user-images.githubusercontent.com/54966170/198208453-85657d08-eab2-4cf7-adf8-b509bf732caf.png)

It's a connection error, did you run the server side?
