### ISSUE TITLE
[FEATURE] Improve on the UI for message input

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#228]
### Description

The current message input + button looks too basic. And it needs some improvements

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Except that the message box doesn't wrap, I don't see your point

**Comment by mathiasayivor** [comment]
> Except that the message box doesn't wrap, I don't see your point

It's to basically style the message input to look much better

**Comment by Dun-sin** [comment]
> > Except that the message box doesn't wrap, I don't see your point
> 
> It's to basically style the message input to look much better

i still don't see the point, it works right?

**Comment by mathiasayivor** [comment]
> > > Except that the message box doesn't wrap, I don't see your point
> > 
> > 
> > It's to basically style the message input to look much better
> 
> i still don't see the point, it works right?

Are you okay with the current styling?

**Comment by mathiasayivor** [comment]
This issue is somehow synonymous with #168.
> The scroll doesn't look good, because it's the default scrollbar

**Comment by Dun-sin** [comment]
> > > > Except that the message box doesn't wrap, I don't see your point
> > > 
> > > 
> > > It's to basically style the message input to look much better
> > 
> > i still don't see the point, it works right?
> 
> Are you okay with the current styling?

100%

**Comment by Dun-sin** [comment]
> This issue is somehow synonymous with #168.
> > The scroll doesn't look good, because it's the default scrollbar

That's a different case, and there's an issue up to fix that
