### ISSUE TITLE
[BUG] error when user messages fails

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#232]
### Description

was testing the app and noticed a message failing to send, i checked the server and it shows the error is coming from this line, id is undefined
https://github.com/Dun-sin/Whisper/blob/45107de72e678a8bdcd5f5edfcd142b23a89aa7c/server/index.js#L207

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

**Comment by khanhtranngoccva** [comment]
![image](https://user-images.githubusercontent.com/61155608/198814231-b4617e11-3f46-4c06-85d7-72aec2e4b132.png)
My plan is to remove the `messageId` property like this as the ID of the message cannot and should not be returned to the client if no user is signed in. There is no event listener to listen to the `send_failed` event either.
Please assign me the issue so that I can create a PR.

**Comment by Dun-sin** [comment]
> ![image](https://user-images.githubusercontent.com/61155608/198814231-b4617e11-3f46-4c06-85d7-72aec2e4b132.png)
> My plan is to remove the `messageId` property like this as the ID of the message cannot and should not be returned to the client if no user is signed in. There is no event listener to listen to the `send_failed` event either.
> Please assign me the issue so that I can create a PR.

I think we should not remove the ID, we need the ID to know what to send again

**Comment by Dun-sin** [comment]
> ![image](https://user-images.githubusercontent.com/61155608/198814231-b4617e11-3f46-4c06-85d7-72aec2e4b132.png)
> My plan is to remove the `messageId` property like this as the ID of the message cannot and should not be returned to the client if no user is signed in. There is no event listener to listen to the `send_failed` event either.
> Please assign me the issue so that I can create a PR.

@mathiasayivor why is there an ID there?
