### ISSUE TITLE
[BUG] logout works even when the server doesn't respond

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#233]
### Description

The server was down when I tested this, I logged out to see if it will let me when if the server is down.

And it did, this is kind of related to #211, user shouldn't have access to any server side functionality while the server is down

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

**Comment by mathiasayivor** [comment]
Does this mean if the server is down, I can't log out of the app?

**Comment by Dun-sin** [comment]
> Does this mean if the server is down, I can't log out of the app?

You can, that's the problem, you will log out but if you are searching, it won't stop.

You said something about implementing when a user logs out they get taken out of the waiting list

**Comment by ozair-dev** [comment]
Hi, I may work on this issue if I have free time in my hand
