### ISSUE TITLE
[FEATURE] Add highlight color variable

### ISSUE THREAD

**Issue by psavvaidis** [Dun-sin/Whisper#234]
### Description

Add the chat bubble color as "highlight" color in tailwind.config.js to refer it in different occasions

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by AAYUSH-droid** [comment]
Hey can you specify more about what exactly needs to be done?

**Comment by psavvaidis** [comment]
Hello,

 We can discuss it in the discord server if you want to.

Cheers

**Comment by Dun-sin** [comment]
> Hello,
> 
>  We can discuss it in the discord server if you want to.
> 
> Cheers

I actually have some new changes to bring up for the colors

**Comment by AAYUSH-droid** [comment]
> Hello,
> 
> We can discuss it in the discord server if you want to.
> 
> Cheers

Sure! can you provide the discord link?!

**Comment by psavvaidis** [comment]
> > Hello,
> > We can discuss it in the discord server if you want to.
> > Cheers
> 
> Sure! can you provide the discord link?!

Yep, check DunSin's profile.

**Comment by Dun-sin** [comment]
@AAYUSH-droid check this issue if you are interested in this kind of issue ⇾ #235

**Comment by Dun-sin** [comment]
and @psavvaidis you can work on this

**Comment by Dun-sin** [comment]
@psavvaidis an update pls? it doesn't take up to an hour to do this, but reminding you incase you forgot

**Comment by psavvaidis** [comment]
> @psavvaidis an update pls? it doesn't take up to an hour to do this, but reminding you incase you forgot

I did forget it, terribly sorry.
