### ISSUE TITLE
[FEATURE] change chat colour

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#235]
### Description

The left color is: #FF3A46
the right color is: #162938

### Screenshots

![image](https://user-images.githubusercontent.com/78784850/200041321-3824015e-d744-4627-aa12-67a34e84f809.png)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

**Comment by Cor4zon** [comment]
Hi @Dun-sin! I would take that issue. Please assign it to me

**Comment by Dun-sin** [comment]
> Hi @Dun-sin! I would take that issue. Please assign it to me

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck
