### ISSUE TITLE
[FEATURE] add profile section UI

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#239]
### Description

Follow the UI design to create this, the component already exists

the component
https://github.com/Dun-sin/Whisper/blob/main/client/src/pages/Profile.jsx

### Screenshots

![image](https://user-images.githubusercontent.com/78784850/197989336-68d85a66-f5f4-4156-9b8f-0ff6a0b3bd01.png)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Uny1me** [comment]
Hey @Dun-sin assign me

**Comment by stephenokyere233** [comment]
Hey @Dun-sin I'd love to work on this one

**Comment by Dun-sin** [comment]
Sure @stephenokyere233, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Code-Magic/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck.

**Comment by stephenokyere233** [comment]
Okay sure
