### ISSUE TITLE
[FEATURE] change icon pack from `react-icons` to `iconify`

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#242]
### Description

I think the Iconify icon pack is currently the best option because it provides a clean and organized look. To use it, simply replace the current icons with the Iconify version in the navbar.

- For the search icon of the navbar (navigation), use -> https://icon-sets.iconify.design/fluent/people-search-20-regular/
- For the Chat icon of the navBar, use -> https://icon-sets.iconify.design/ion/chatbubble-ellipses-outline/
- For the Profile icon of the navBar, use -> https://icon-sets.iconify.design/fluent/person-circle-20-regular/
- For the logout icon of the navBar, use -> https://icon-sets.iconify.design/majesticons/logout-half-circle/
- For the settings icon of the navBar, use -> https://icon-sets.iconify.design/ic/outline-settings/

### Screenshots

Your focus is here
![image](https://user-images.githubusercontent.com/78784850/209005243-984e461a-7476-4892-8842-5047e1e1f628.png)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by devvsakib** [comment]
im on it, please assign me

**Comment by Dun-sin** [comment]
> im on it, please assign me 

Okay, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck
