### ISSUE TITLE
[FEATURE] Set up a CI/CD pipeline

### ISSUE THREAD

**Issue by Cor4zon** [Dun-sin/Whisper#245]
### Description

Let's improve a deployment process by setting up CI/CD pipeline. 

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Hi, thanks for making a PR, please enlighten more on what you plan to do in this issue. Mention tools and steps, thank you.

**Comment by Dun-sin** [comment]
> Okey, i think about using Travis CI. And firstly i would add code-linters (to check eslint and typescript) step to pipeline, and secondly probably some tests. What do you think about it?

Never used Travis, you can make a draft PR so we really see what's to do

**Comment by Dun-sin** [comment]
hi @Cor4zon still interested in this? never saw that draft PR
