### ISSUE TITLE
[FEATURE] Reply to older messages

### ISSUE THREAD

**Issue by Kamasah-Dickson** [Dun-sin/Whisper#246]
### Description

- Users should be able to reply to  older messages. 

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by haszankauna** [comment]
Hello @Dun-sin  can I please be assigned this?

**Comment by Dun-sin** [comment]
> Hello @Dun-sin  can I please be assigned this?

You can only work on one issue at a time.
Look at the rules here, https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules

**Comment by haszankauna** [comment]
> > Hello @Dun-sin  can I please be assigned this?
> 
> You can only work on one issue at a time. Look at the rules here, https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules
okay. That's fine. Deleted my other requests

**Comment by haszankauna** [comment]
> > Hello @Dun-sin  can I please be assigned this?
> 
> You can only work on one issue at a time. Look at the rules here, https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules
okay. That's fine. Deleted my other requests

**Comment by Dun-sin** [comment]
Alright I'm guessing you want to work on this one inste, thank you, If I'm wrong with the guess let me know, but going to assign you to it.

Please follow the rules when contributing, thank you🔥

**Comment by Dun-sin** [comment]
>@haszankauna Alright I'm guessing you want to work on this one inste, thank you, If I'm wrong with the guess let me know, but going to assign you to it.
> 
> Please follow the rules when contributing, thank you🔥

**Comment by Dun-sin** [comment]
I just realized an issue like this has been created and fixed🤦🏽‍♀️ so sorry @haszankauna and also since there's no update on this. Will be closing it.
Thank you and sorry if you already started working on it
