### ISSUE TITLE
[BUG]: Anonymous user status typing whilst disconnected

### ISSUE THREAD

**Issue by Kamasah-Dickson** [Dun-sin/Whisper#247]
### Description

I tried the application and met a new friend. He DM  me on twitter and I realized the status of the user was typing even when he is disconnected.

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by AmohPrince** [comment]
Hey @Dun-sin , Can you assign me to this issue I feel like I can tackle it.

Thanks.

**Comment by Dun-sin** [comment]
> Hey @Dun-sin , Can you assign me to this issue I feel like I can tackle it.
> 
> Thanks.

Awesome, thank you, Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck

**Comment by Dun-sin** [comment]
Hi @AmohPrince, an update on this please?

**Comment by chocoscoding** [comment]
Hey @Dun-sin , Can you assign me to this issue

**Comment by mathiasayivor** [comment]
@Dun-sin This is because of how the typing status is being updated. And it's really annoying to get a "typing" status even when the user is disconnected, or not actively typing.

I would like to work on this can I be assigned?
