### ISSUE TITLE
[BUG]: Fix positioning and UI of Anonymous Login Button

### ISSUE THREAD

**Issue by AbdurrahmanSogbesan** [Dun-sin/Whisper#249]
### Description

The 'Login Anonymously' button UI could be improved, and the button is also not placed centrally.

### Screenshots

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/64173776/213184892-9e4ed4a3-da9c-451c-bbbb-d99b53577a3d.png">

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
It's actually that way for a reason, so it won't be the main focus because I don't actually want people to login anonymously😂

But thanks for raising an issue, I appreciate it
