### ISSUE TITLE
Docker Link leading to MongoDb Website in the Readme

### ISSUE THREAD

**Issue by bonysureliya** [Dun-sin/Whisper#250]
### Description

In Readme Where Stacks are mentioned there Docker link redirects to Mongodb website

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Read the project rules my friend and fix your mistakes, thanks🔥

**Comment by bonysureliya** [comment]
So I have to create a new branch for commiting docs or should I add correct the PR name as per described in readme

**Comment by Dun-sin** [comment]
> So I have to create a new branch for commiting docs or should I add correct the PR name as per described in readme 

Just has to be something other than the main branch so you are fine with that. Just follow the rules with everything else
