### ISSUE TITLE
[FEATURE] backend for the quote reply feature

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#253]
### Description

The frontend part of this issue is done, the original issue is #167 and the PR for that issue is #252.

Tasks (the main things to be accomplished):
- the schema for the message should change to an object, one key should be the new message and the other key should be the quote message (which should be a reference to the message to be quoted)
- if a new message doesn't have a quote reply, the value should be null.

This PR is open for discussion on the discord server (link in the readme) on a better way to do this, don't want to overcrowd this issue.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Deva-1903** [comment]
I've already started working on this. Can you please assign me this issue?

**Comment by karthikeyanvelusamy** [comment]
Hey @Dun-sin , Can you assign this to me ?

**Comment by Dun-sin** [comment]
> Hey @Dun-sin , Can you assign this to me ?

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by Dun-sin** [comment]
> Hey @Dun-sin , Can you assign this to me ?

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by Dun-sin** [comment]
@karthikeyanvelusamy please do the backend based on the structure of the changes in this issue -> #169, it hasn't been merged yet because of the backend wasn't complete

**Comment by Dun-sin** [comment]
hi @karthikeyanvelusamy are you still working on this? I need to close this Issue because with the use of Markdown it's not needed any more and markdown adds a better way to do this. I'm sorry for wasting your time after so long.
