### ISSUE TITLE
[FEATURE] Encryption of messages

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#256]
### Description

Right now, the messages are just being sent to the database raw, which isn't right, we need a way to encrypt them and the user ids too

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
> hello @Dun-sin Can i be assigned this task

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Code-Magic/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck. If you need any help, let me know

**Comment by DennisMwangi1** [comment]
I have been getting this error when trying to do `npm install` 

`npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use
npm ERR! gyp ERR! stack     at VisualStudioFinder.fail (C:\Users\denni\PersonalProjects\Whisper\node_modules\node-gyp\lib\find-visualstudio.js:122:47)
npm ERR! gyp ERR! stack     at C:\Users\denni\PersonalProjects\Whisper\node_modules\node-gyp\lib\find-visualstudio.js:75:16
npm ERR! gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Users\denni\PersonalProjects\Whisper\node_modules\node-gyp\lib\find-visualstudio.js:363:14)
npm ERR! gyp ERR! stack     at C:\Users\denni\PersonalProjects\Whisper\node_modules\node-gyp\lib\find-visualstudio.js:71:14
npm ERR! gyp ERR! stack     at C:\Users\denni\PersonalProjects\Whisper\node_modules\node-gyp\lib\find-visualstudio.js:384:16
npm ERR! gyp ERR! stack     at C:\Users\denni\PersonalProjects\Whisper\node_modules\node-gyp\lib\util.js:54:7
npm ERR! gyp ERR! stack     at C:\Users\denni\PersonalProjects\Whisper\node_modules\node-gyp\lib\util.js:33:16
npm ERR! gyp ERR! stack     at ChildProcess.exithandler (node:child_process:427:5)
npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:513:28)
npm ERR! gyp ERR! stack     at maybeClose (node:internal/child_process:1091:16)
npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm ERR! gyp ERR! System Windows_NT 10.0.22000`

Im using the latest version of visual studio code on my machine

**Comment by Dun-sin** [comment]
> I have been getting this error when trying to do `npm install`
> 
> `npm ERR! gyp ERR! stack Error: Could not find any Visual Studio installation to use npm ERR! gyp ERR! stack at VisualStudioFinder.fail (C:\Users\denni\PersonalProjects\Whisper\node_modules\node-gyp\lib\find-visualstudio.js:122:47) npm ERR! gyp ERR! stack at C:\Users\denni\PersonalProjects\Whisper\node_modules\node-gyp\lib\find-visualstudio.js:75:16 npm ERR! gyp ERR! stack at VisualStudioFinder.findVisualStudio2013 (C:\Users\denni\PersonalProjects\Whisper\node_modules\node-gyp\lib\find-visualstudio.js:363:14) npm ERR! gyp ERR! stack at C:\Users\denni\PersonalProjects\Whisper\node_modules\node-gyp\lib\find-visualstudio.js:71:14 npm ERR! gyp ERR! stack at C:\Users\denni\PersonalProjects\Whisper\node_modules\node-gyp\lib\find-visualstudio.js:384:16 npm ERR! gyp ERR! stack at C:\Users\denni\PersonalProjects\Whisper\node_modules\node-gyp\lib\util.js:54:7 npm ERR! gyp ERR! stack at C:\Users\denni\PersonalProjects\Whisper\node_modules\node-gyp\lib\util.js:33:16 npm ERR! gyp ERR! stack at ChildProcess.exithandler (node:child_process:427:5) npm ERR! gyp ERR! stack at ChildProcess.emit (node:events:513:28) npm ERR! gyp ERR! stack at maybeClose (node:internal/child_process:1091:16) npm ERR! gyp ERR! stack at ChildProcess._handle.onexit (node:internal/child_process:302:5) npm ERR! gyp ERR! System Windows_NT 10.0.22000`
> 
> Im using the latest version of visual studio code on my machine

Where did you run this?

**Comment by AryanKhubchandani** [comment]
Hello @Dun-sin, if @DennisMwangi1 is not working on this may I take this issue up?

**Comment by Dun-sin** [comment]
> Hello @Dun-sin, if @DennisMwangi1 is not working on this may I take this issue up?

Sure

**Comment by Dun-sin** [comment]
@AryanKhubchandani been too long on this? What's up with this?

**Comment by sandeep-red** [comment]
Hi @Dun-sin, can i work on this issue?

**Comment by Dun-sin** [comment]
> Hi @Dun-sin, can i work on this issue?

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by sandeep-red** [comment]
Hi @Dun-sin , i have a doubt. Does userid mean email id of the user ?

**Comment by Dun-sin** [comment]
> Hi @Dun-sin , i have a doubt. Does userid mean email id of the user ?

Which part of the code is this question coming from? Folder and file please

**Comment by sandeep-red** [comment]
> > Hi @Dun-sin , i have a doubt. Does userid mean email id of the user ?
> 
> Which part of the code is this question coming from? Folder and file please

I'm talking about the description of this issue. It says need to encrypt the userids, so what does user id refer to here?

**Comment by Dun-sin** [comment]
> > > Hi @Dun-sin , i have a doubt. Does userid mean email id of the user ?
> > 
> > Which part of the code is this question coming from? Folder and file please
> 
> I'm talking about the description of this issue. It says need to encrypt the userids, so what does user id refer to here?

I know, but I obviously you are asking this question because you say it in a while. So I'm asking you what file is it

**Comment by Dun-sin** [comment]
hi @sandeep-red how's this going?

**Comment by HeetVekariya** [comment]
Hey, @Dun-sin . I have worked has Backend Developer in many projects.
I can work on this if no is working on it.

However i have never worked with socket.io so i don't know where should i apply the hashing for the chat. 
But i can work upon the username/userId hashing part.

While going through the code i am not able to find the code for the user registration. If you want me to work on this userId hashing part then can you please locate the code where you exactly register the user.

Please add the Hactoberfest label to this issue.

**Comment by Dun-sin** [comment]
> Hey, @Dun-sin . I have worked has Backend Developer in many projects. I can work on this if no is working on it.
> 
> However i have never worked with socket.io so i don't know where should i apply the hashing for the chat. But i can work upon the username/userId hashing part.
> 
> While going through the code i am not able to find the code for the user registration. If you want me to work on this userId hashing part then can you please locate the code where you exactly register the user.
> 
> Please add the Hactoberfest label to this issue.

you don't need to know where the users is registered to fix this issue, and did you check for the usermodel and trace from there or even the usercontroller

**Comment by Dun-sin** [comment]
and how would you handle the encryption

**Comment by RiccardoCafa** [comment]
Hello @Dun-sin, for encryption you mean just a simple plaintext to a cipher encryption with a key stored somewhere in the server? Or a complex encryption system?

**Comment by mathiasayivor** [comment]
This is possible, but implementing it means user data can be easily lost should the users forget their keys. It also makes subsequent logins a bit tricky (for email users), since they'd have to in a way enter their key pairs on each login.

The login can be simplified for mobile devices tho using qr codes.

Also, if we're to completely encrypt all user data, then we'd need to implement our own custom auth flow as proposed in #390.

@Dun-sin what do you think?
I'd like to work on this issue tho.

**Comment by Dun-sin** [comment]
> Hello @Dun-sin, for encryption you mean just a simple plaintext to a cipher encryption with a secret key stored somewhere in the server? Or a complex encryption system?

can you talk more on both options?
