### ISSUE TITLE
[FEATURE] Improve on theming

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#258]
### Description

Enable users to switch to dark/light modes easily.
This should be easy to implement with tailwindcss

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by joshi-omkar** [comment]
hey @Dun-sin, Can you assign this issue to me?

**Comment by Dun-sin** [comment]
> hey @Dun-sin, Can you assign this issue to me?

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. 
Good Luck

**Comment by Dun-sin** [comment]
@joshi-omkar an update here please?

**Comment by Dun-sin** [comment]
@joshi-omkar an update here please?

**Comment by mridul891** [comment]
hey @Dun-sin  Can you assign this issue with me ,I will definetly try my level best to complete this in the given time

**Comment by Dun-sin** [comment]
> hey @Dun-sin  Can you assign this issue with me ,I will definetly try my level best to complete this in the given time 

Ok, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Code-Magic/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by Surya-V-28** [comment]
hey @Dun-sin  is the issues is still open , I can try my best to implement the feature , can I get the role for it , Looking forward to you reply 
?

**Comment by Dun-sin** [comment]
@Surya-V-28 it's assigned to @mridul891 I will use this avenue to ask @mridul891 for an update on this and is still working on it and can push anytime soon, if he doesn't I will assign it to you @Surya-V-28

**Comment by Surya-V-28** [comment]
Sure, ping me if its still open @Dun-sin

**Comment by Dun-sin** [comment]
@mridul891 an update on this please?

**Comment by mridul891** [comment]
@Dun-sin i am currently working on it

**Comment by Dun-sin** [comment]
> @Dun-sin i am currently working on it .within a week i will let you know if i am unable to implement the feature
> 

Okay, thanks for the update

**Comment by priyanshtiwari001** [comment]
Hi @Dun-sin , if This issue is still open then please try to assign me I will complete this as soon as possible.Thank you!

**Comment by mridul891** [comment]
@Dun-sin  you can assign this work to someone .

**Comment by Dun-sin** [comment]
> @Dun-sin  you can assign this work to someone .
> 

Okay, @Surya-V-28 do you still want this?

**Comment by Surya-V-28** [comment]
Sure, I will work on it

**Comment by Dun-sin** [comment]
> Sure, I will work on it @Dun-sin 
> 
> 

Okay, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Code-Magic/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.

If npm install doesn't work, remove the mojoauth package on your end, but don't push your package.json.

**Comment by Dun-sin** [comment]
@Surya-V-28 how is this going?
