### ISSUE TITLE
[OTHER] Convert to use Nextjs

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#269]
### What would you like to share?

It's just React, socket and Node.js, would be better if it's with Next.js, makes it cleaner to work with

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by ChavvaNarayana** [comment]
Sounds good to me. I'm willing to contribute.
Please assign it to me.

**Comment by mariamsayeed** [comment]
I want to work on this issue. Could you please assign it to me?
