### ISSUE TITLE
[OTHER] refactor large file

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#272]
### What would you like to share?

We have a large file in chat.jsx, break the file into using helper.js, so we can just call the functions in chat.jsx, if you have a better to do this don't hesitate to tell me, let's have a discussion.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Ravina-Deogadkar** [comment]
Can I work on this?

**Comment by Dun-sin** [comment]
> Can I work on this?

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by Dun-sin** [comment]
hi @Ravina-Deogadkar how's this going?

**Comment by MaybeSHAH** [comment]
@Dun-sin I'm interested in working on this issue. Could you please reassign it to me?

**Comment by Dun-sin** [comment]
> @Dun-sin I'm interested in working on this issue. Could you please reassign it to me?

Hold on, if I don't get a response from @Ravina-Deogadkar then you can have it, just have some patience

**Comment by Ravina-Deogadkar** [comment]
Hi @Dun-sin, Just started with it. Thinking of raising a PR over a weekend.

**Comment by Dun-sin** [comment]
> Hi @Dun-sin, Just started with it. Thinking of raising a PR over a weekend.

Okay

**Comment by Dun-sin** [comment]
@Ravina-Deogadkar it's pass the weekend

**Comment by SneakY-NickY** [comment]
Hi, could you please describe this issue in more detail? I'm not quite sure what the goal here is.

**Comment by Dun-sin** [comment]
> Hi, could you please describe this issue in more detail? I'm not quite sure what the goal here is.

When you have a big function and you want to break it down and make concept more reusable, what do you do?

Read the issue again with this concept in mind

**Comment by MaybeSHAH** [comment]
@Dun-sin Could you please assign it to me?

**Comment by SneakY-NickY** [comment]
> > Hi, could you please describe this issue in more detail? I'm not quite sure what the goal here is.
> 
> When you have a big function and you want to break it down and make concept more reusable, what do you do?
> 
> Read the issue again with this concept in mind

Ah I see, this is something I would like to work on. Could you perhaps assign this to me?

**Comment by Dun-sin** [comment]
> > > Hi, could you please describe this issue in more detail? I'm not quite sure what the goal here is.
> > 
> > When you have a big function and you want to break it down and make concept more reusable, what do you do?
> > 
> > Read the issue again with this concept in mind
> 
> Ah I see, this is something I would like to work on. Could you perhaps assign this to me?

Sadly @MaybeSHAH has been asking for over 2 weeks
