### ISSUE TITLE
[BUG]: in edit message 

### ISSUE THREAD

**Issue by Himanshu-0981** [Dun-sin/Whisper#281]
### Description

Whenever I try to edit my message, I get a whole HTML tag with my current editable message. It's really frustrating for non-tech guys to chat there. It should be without an HTML tag.

### Screenshots

This is how it looks after clicking on edit message.

![Screenshot 2023-09-25 154912](https://github.com/Dun-sin/Whisper/assets/71598691/16d45253-7249-4a01-9ba8-7ace08c6b93f)

This is how it should be.

![Screenshot 2023-09-25 155620](https://github.com/Dun-sin/Whisper/assets/71598691/db31e222-fc7e-4eb6-a301-da4fafd5bc99)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
That's weird, I have always tested the edit feature and have never seen that before. Thanks for raising will look into it👍🏽
