### ISSUE TITLE
[FEATURE] ctrl + enter should send a message

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#288]
### Description

As the title says, on desktop when Ctrl + enter is clicked the message should be sent.

Use the `useKeyPress.js` hook

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by aman44444** [comment]
@Dun-sin I want to work on this feature. Can you please assign this to me?

**Comment by Dun-sin** [comment]
> @Dun-sin I want to work on this feature. Can you please assign this to me?

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by Kapilrohilla** [comment]
Hi, @Dun-sin I want to work on this feature. Can you assign it to me.

**Comment by Dun-sin** [comment]
> Hi, @Dun-sin I want to work on this feature. Can you assign it to me.

already assigned to someone else, you can easily see it in these places, keep that in mind next time, and you can look at other issues or use the app and report whatever problem you find. Thanks for wanting to contribute, hope to keep seeing you around
![image](https://github.com/Dun-sin/Whisper/assets/78784850/2f45ca5c-e367-4b39-99c2-b8cdf01bfb5e)
![image](https://github.com/Dun-sin/Whisper/assets/78784850/7d5b93d2-a7e8-46cb-9a9b-dc1bafa8dcb3)
