### ISSUE TITLE
[BUG]: double menu on receiving message

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#289]
### Description

When a user receives a message, it renders a double menu instead of one,
this is where the bug is coming from, all you have to do is merge the menus for when the user is not the sender, easy to spot when the edit option isn't available
https://github.com/Dun-sin/Whisper/blob/a253b2d624a91237f46a786ef59cece95b0073c2/client/src/components/Chat.jsx#L497-L550

### Screenshots

![image](https://github.com/Dun-sin/Whisper/assets/78784850/fd687a5a-39d0-4323-87f0-c151628be4e3)

### Additional information

# Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules)

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Rhythm-08** [comment]
Hello @Dun-sin I would like to solve this issue , can you assign it to me

**Comment by Hrx4** [comment]
Hey @Dun-sin  assign me the issue , I can fix this

**Comment by Dun-sin** [comment]
> Hello @Dun-sin I would like to solve this issue , can you assign it to me

Definitely, thanks for wanting to contribute, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.

**Comment by Dun-sin** [comment]
hi @Rhythm-08 when you work on this issue actually delete the code for "delete" message when it's not the sender

**Comment by Rhythm-08** [comment]
OK sure
