### ISSUE TITLE
[FEATURE] key shortcut for closing chat should change

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#292]
### Description

The key shortcut for closing a chat is Ctrl + c which is also the copy shortcut, not a good mixture to close a chat should change to `ctrl + shift + c` that we don't have a mismatch.

You can find the code for this here and the hook code at useKeyPress.js
https://github.com/Dun-sin/Whisper/blob/a253b2d624a91237f46a786ef59cece95b0073c2/client/src/components/Anonymous.jsx#L103-L104

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by RiccardoCafa** [comment]
Hi @Dun-sin can I take this issue in charge?

**Comment by Dun-sin** [comment]
> Hi @Dun-sin can I take this issue in charge?

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by RiccardoCafa** [comment]
The shortcut CTRL + SHIFT + C currently opens the developer tools in Google Chrome, specifically activating the "Select Element" tool.
What if we opt for CTRL + SHIFT + X instead?

**Comment by Dun-sin** [comment]
> The shortcut CTRL + SHIFT + C currently opens the developer tools in Google Chrome, specifically activating the "Select Element" tool. What if we opt for CTRL + SHIFT + X instead?

oh for sure, didn't think of that since i use firefox. ctrl+ shift + x works fine

**Comment by Dun-sin** [comment]
> @Dun-sin I noticed that there's a TypeScript version of the useKeyPress hook in this project. However, it appears that the project is configured to use only JavaScript. This file has some purpose?
> 
> Also I was wondering if would be nice if we implement this shortcut feature with a Builder design pattern so it's easy to build and maintain different kind of shortcuts in the future. Let me know what do you think!

Do a git pull,and see some magic😆
