### ISSUE TITLE
[DOCS] wrong command in README.md

### ISSUE THREAD

**Issue by VoidVampire** [Dun-sin/Whisper#295]
### Description

In 7th step of installation, npm dev:docker is wrong command. It should be npm run dev:docker
Tested on both Windows 11 and Fedora 38.

### Screenshots

![image](https://github.com/Dun-sin/Whisper/assets/80760499/65d347fd-ca07-4797-811f-0d2e341e7ed8)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Wonderful, thanks for pointing that out. Will assign you to it.

Please read the contributing.md file for the rules🤝🏽
