### ISSUE TITLE
New Issue / Questions : wrong discord invite link

### ISSUE THREAD

**Issue by VoidVampire** [Dun-sin/Whisper#297]
### Description

KUWjx4fygJ is the discord invite link when we go through Questions while Creating New Issue. I can't find this in readme so I am guessing it can be only resolved by maintainers (not sure how this can be accomplished through PR), but I wanted to bring this issue in light.

I found similar issue (78) but that link was in the README.md

### Screenshots

![image](https://github.com/Dun-sin/Whisper/assets/80760499/2ed195b9-4d80-45aa-849b-ce513ba69eab)

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
It's there, the way links are meant to be on github, click on join us and you go to the server 

![Screenshot_2023-09-27-06-46-01-677_com.github.android-edit.jpg](https://github.com/Dun-sin/Whisper/assets/78784850/5397ce80-0699-49e7-b1db-7a2784712e1c)

**Comment by VoidVampire** [comment]
I understand that and that's how I joined the server.
If you check [New Issue](https://github.com/Dun-sin/Whisper/issues/new/choose) and click on Open next to Questions, it will redirect to invalid server.

**Comment by Dun-sin** [comment]
> I understand that and that's how I joined the server. But if you check [New Issue](https://github.com/Dun-sin/Whisper/issues/new/choose) and click on Open next to Questions, it will redirect to invalid server.

i see your point now, i thought you meant the link in the readme wasn't there and the one in the questions issue template was, i will create the proper issue to fix that
