### ISSUE TITLE
[DOCS] fix invalid discord link 

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#298]
### Description

To fix this, change the URL to this → `https://discord.gg/ufcysW9q23`

https://github.com/Dun-sin/Whisper/blob/4b12bf53561e7c2e5f8188c40c1a7d10eba11978/.github/ISSUE_TEMPLATE/config.yml#L4

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
> Can I work on this issue? @Dun-sin can you assign me this?

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by Mithilesh-create** [comment]
I would like to work on this issue .

**Comment by Dun-sin** [comment]
hi @th-shristi this shouldn't take this long?

**Comment by th-shristi** [comment]
@Dun-sin I am waiting for Oct 1 so as to count this in Hacktoberfest!

**Comment by Dun-sin** [comment]
> @Dun-sin I am waiting for Oct 1 so as to count this in Hacktoberfest!
> 

Make the pull request and I will merge it then👍🏽

**Comment by th-shristi** [comment]
@Dun-sin I have made a PR. there's some error in it, can you tell me what's that?

**Comment by Dun-sin** [comment]
> @Dun-sin I have made a PR. there's some error in it, can you tell me what's that? 

You didn't follow the guidelines [👉🏽here👈🏽](https://github.com/Dun-sin/Code-Magic/blob/main/CONTRIBUTING.md#rules), go read it👍🏽

**Comment by th-shristi** [comment]
@Dun-sin Done with the changes! kindly check it>

**Comment by Dun-sin** [comment]
> @Dun-sin Done with the changes! kindly check it>

already did and left a comment

**Comment by th-shristi** [comment]
@Dun-sin done

**Comment by th-shristi** [comment]
<img width="410" alt="image" src="https://github.com/Dun-sin/Whisper/assets/119031272/408c37fa-ef4b-4118-ba13-9d690aca21b6">
says authorization required! i have already approved it

**Comment by Dun-sin** [comment]
> <img width="410" alt="image" src="https://github.com/Dun-sin/Whisper/assets/119031272/408c37fa-ef4b-4118-ba13-9d690aca21b6">
> says authorization required! i have already approved it

Don't worry about that👍🏽 it's fine, it's because I haven't approved the PR yet

**Comment by th-shristi** [comment]
Okay! i have made a PR kindly check it
