### ISSUE TITLE
[BUG]: other issue template not showing up

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#299]
### Description

To fix this, remove the commas at the end of this two lines
https://github.com/Dun-sin/Whisper/blob/4b12bf53561e7c2e5f8188c40c1a7d10eba11978/.github/ISSUE_TEMPLATE/other.yml#L3-L4

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by ronisarkarexe** [comment]
@Dun-sin can you assign me this task?

**Comment by Dun-sin** [comment]
> @Dun-sin can you assign me this task?

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by yashwanthvarma18** [comment]
Hello @Dun-sin, I'm eager to contribute. Please assign me

**Comment by Dun-sin** [comment]
> Hello @Dun-sin, I'm eager to contribute. Please assign me

already assigned, next time check that first

**Comment by Dun-sin** [comment]
@ronisarkarexe this shouldn't take this long
