### ISSUE TITLE
App not redirecting to auth page after logout

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#301]
### Description

After I log out, I'm redirected to Kinde's logout success page. I don't know if that's intentional, but I expected to be redirected back to Whisper's auth page.

### Screenshots

![Screenshot from 2023-09-27 08-42-23](https://github.com/Dun-sin/Whisper/assets/74247733/4d7d72df-93a6-4cb2-8d91-9e98dd7e7c27)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
It's intentional if you use login, but if it's anonymous it shouldn't do that. I'm thinking to find how to fix that. Thanks for creating an issue tho, I'm aware.

**Comment by mathiasayivor** [comment]
If it's intentional, I suggest there should be a link that redirects back to the apps auth page.

**Comment by Dun-sin** [comment]
> If it's intentional, I suggest there should be a link that redirects back to the apps auth page.

I don't think it's necessary, as if a user logout it most likely means they want to leave and close the application, the only reason you're complaining because you are using it to test something. 

But there is a logout url callback, should work

**Comment by Dun-sin** [comment]
> @Dun-sin i think it would be better to place a button "Home" to get back to auth page. you can assign it to me .

you can't do that because kinde doesn't allow you to edit their pages

**Comment by ChavvaNarayana** [comment]
Sounds good to me. I'm willing to contribute.
Please assign it to me.

**Comment by aman1205** [comment]
Hey i would like work on this .can you assign me task

**Comment by Dun-sin** [comment]
> Hey i would like to  work on this . can you please  assign me the  task 

Sorry this isn't up for working on
