### ISSUE TITLE
[FEATURE] Auto increase message input height for multi-line messages

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#302]
### Description

The message input field does not auto-expend when typing multi-line messages, which makes viewing long messages before sending them hard.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by NEMYSESx** [comment]
Hey I would like to contribute to this issue. Please assign me this

**Comment by Dun-sin** [comment]
> Hey I would like to contribute to this issue. Please assign me this

can you tell me how you would?

**Comment by bintus-ux** [comment]
I would love to handle this, please assign me the task

**Comment by bintus-ux** [comment]
This can be achieved by using a textarea element that will readjust dynamically its height based on the text content. By updating the height of the text input field based on its scroll height

**Comment by Dun-sin** [comment]
> This can be achieved by using a textarea element that will readjust dynamically its height based on the text content. By updating the height of the text input field based on its scroll height

sounds good, you got it, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by NEMYSESx** [comment]
> > Hey I would like to contribute to this issue. Please assign me this
> 
> can you tell me how you would?

I will basically add a javascript logic which will be a event listener. Inside that function I will set the textarea element height to 'auto'. This step will allow the textarea element to expand or shrink based on its content.
And then I will use another property called 'scrollHeight' and equate it to the textarea element height to match the 'scrollHeight'.
At the very end I will set it's unit to px.

So the logic will be something like this

textarea.addeventListener('change',()=>{
 textarea.style.height= 'auto';
 textarea.style.height= c.textarea.scrollHeight + 'px';
}):

**Comment by Dun-sin** [comment]
> > > Hey I would like to contribute to this issue. Please assign me this
> > 
> > can you tell me how you would?
> 
> I will basically add a javascript logic which will be a event listener. Inside that function I will set the textarea element height to 'auto'. This step will allow the textarea element to expand or shrink based on its content.
> And then I will use another property called 'scrollHeight' and equate it to the textarea element height to match the 'scrollHeight'.
> At the very end I will set it's unit to px.
> 
> So the logic will be something like this
> 
> textarea.addeventListener('change',()=>{
>  textarea.style.height= 'auto';
>  textarea.style.height= c.textarea.scrollHeight + 'px';
> }):
> 

Sorry you replied a little too late, but don't let that stop you from contributing, there are other issues still available and new ones coming soon🤝🏽

**Comment by Dun-sin** [comment]
@bintus-ux how's this going?

**Comment by bintus-ux** [comment]
Yeah it’s going fine, previously had issues connecting to my MongoDB but resolving it, should be done soonest

**Comment by prafull904434** [comment]
sir,
may i work with this issue ,
can you assign to me
