### ISSUE TITLE
[FEATURE] Auto close chat when user logs out

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#303]
### Description

my chat is not being closed when my buddy logs out. When my buddy log out, I expect the chat to be closed, and a confirmation dialog asking me if I would like to find a new buddy (just like the one I get when my buddy closes their chat) except if my buddy is logged in on multiple devices.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
it's not related to #211

**Comment by pateldivyesh1323** [comment]
@Dun-sin I would like to work on this.

**Comment by Dun-sin** [comment]
> @Dun-sin I would like to work on this.

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by t-trafer** [comment]
Hey @Dun-sin, i can work on this if it's still up for grab

**Comment by Dun-sin** [comment]
> Hey @Dun-sin, i can work on this if it's still up for grab

Definitely, thanks for wanting to contribute, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.

**Comment by t-trafer** [comment]
seems like the issue was with backend server infact and client's behaviour was properly implemented..
some dependencies were just not imported because of which the server kept crashing.

@Dun-sin raising the PR for this, you might want to update the issue reflecting these for better tracking.

PS: this will not  show "find a new buddy" but instead "Search for Someone".. which is consistent with other ways of closing the chat - let me know if you would still want the "find new buddy" dialogue instead.

**Comment by t-trafer** [comment]
would also suggest to add eslint precommit hook - so these mistakes get caught early on.

**Comment by Dun-sin** [comment]
> seems like the issue was with backend server infact and client's behaviour was properly implemented..
> some dependencies were just not imported because of which the server kept crashing on logout.
> 
> @Dun-sin raising the PR for this, you might want to update the issue reflecting these for better tracking.
> 
> PS: this will not  show "find a new buddy" but instead "Search for Someone".. which is consistent with other ways of closing the chat - let me know if you would still want the "find new buddy" dialogue instead.

Just keep things your issue, so no for the P.S
