### ISSUE TITLE
[BUG]: `prop-types` devDependency not in package.json

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#304]
### Description

The package `prop-types`, which is used for prop validation is not added to package.json, and when running in the dev mode (e.g running `pnpm start`) throws an error:

```bash
Error: The following dependencies are imported but could not be resolved:

  prop-types (imported by /.../whisper/client/src/components/MessageStatus.jsx)
```

### Additional information

To fix this, just run `npm i -D prop-types` in the client folder
```
npm i -D prop-types
```

### 🥦 Browser

Other

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Intekhabilyas** [comment]
@Dun-sin  can you assign this to me??

**Comment by Chetax** [comment]
Hello @Dun-sin ! ! ! Just a quick heads up. I'm interested in solving this :D Can You Please Assign Me.

**Comment by Dun-sin** [comment]
> Hello @Dun-sin ! ! ! Just a quick heads up. I'm interested in solving this :D Can You Please Assign Me.

looks like you are spamming everywhere, do you even read the issues?

**Comment by Chetax** [comment]
Yes Sir ,In Previous Issue Someone want to work so i try to find new issue so i get this and that's why i say to you.
i am not spamming sir .

**Comment by Chetax** [comment]
@Dun-sin mam can you please see my pull request what is wrong or what to be changes done ..please mam

**Comment by Dun-sin** [comment]
> @Dun-sin mam can you please see my pull request what is wrong or what to be changes done ..please mam

check the PR for my comment

**Comment by Divyesh1511** [comment]
hey @Dun-sin, I hope you are doing well. Is this issue still open? if it is I would like to solve the issue if you can assign it to me.

**Comment by Dun-sin** [comment]
> hey @Dun-sin, I hope you are doing well. Is this issue still open? if it is I would like to solve the issue if you can assign it to me.

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by Divyesh1511** [comment]
> > hey @Dun-sin, I hope you are doing well. Is this issue still open? if it is I would like to solve the issue if you can assign it to me.
> 
> Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

@Dun-sin can you please help me with the "git cz" command, in my git it's showing that there is no such command and if i do git commit it will commit package.json and package-lock.json file too.

**Comment by Dun-sin** [comment]
> > > hey @Dun-sin, I hope you are doing well. Is this issue still open? if it is I would like to solve the issue if you can assign it to me.
> > 
> > Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
> 
> @Dun-sin can you please help me with the "git cz" command, in my git it's showing that there is no such command and if i do git commit it will commit package.json and package-lock.json file too.

Read the readme
