### ISSUE TITLE
[FEATURE] send notification when paired

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#305]
### Description

Send a browser notification when a user gets paired, call the function for the sending notification here
https://github.com/Dun-sin/Whisper/blob/4b12bf53561e7c2e5f8188c40c1a7d10eba11978/client/src/components/BuddyMatcher.jsx#L118-L123

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by dhananjay-Byte** [comment]
browser notification means like an alert?

**Comment by dhananjay-Byte** [comment]
i am willing to work on this feature just need some clarification.

**Comment by Dun-sin** [comment]
> browser notification means like an alert?

what kind of alert, if you thinking of a modal or the alert in javascript then no

**Comment by dhananjay-Byte** [comment]
ok got it now. I would like to work on this

**Comment by Dun-sin** [comment]
> ok got it now. I would like to work on this

sounds good, can you tell me how you would go about it?

**Comment by dhananjay-Byte** [comment]
i can create an custom event in the socket and emit an message to that roomID when user get paired.

**Comment by Dun-sin** [comment]
> i can create an custom event in the socket and emit an message to that roomID when user get paired.

What will you do with it, there's already a socket that does that, which is what is in the issue description

**Comment by dhananjay-Byte** [comment]
i can list an another notification event in the notification.js lib file which will called in the socket joined event and return the popup message on the screen.

**Comment by Dun-sin** [comment]
> i can list an another notification event in the notification.js lib file which will called in the socket joined event and return the popup message on the screen.

Exactly that's what I want to know, how would you do that. What will you do in the function

**Comment by dhananjay-Byte** [comment]
I can return a boolean state in the function which will be initialized as false but when you call the function it will be true and once it is true we can display notification on the screen using { } and we can also an useeffect hook to listen on state variable and once it is set to true then again using settimeout in useEffect we can set the state to false. 

also we can use the switch cases to declare different switch cases for different types of notification and state will be initialized as different objects each representing the state for each notification.

**Comment by Dun-sin** [comment]
> I can return a boolean state in the function which will be initialized as false but when you call the function it will be true and once it is true we can display notification on the screen using { } and we can also an useeffect hook to listen on state variable and once it is set to true then again using settimeout in useEffect we can set the state to false. 
> 
> also we can use the switch cases to declare different switch cases for different types of notification and state will be initialized as different objects each representing the state for each notification.

Not the answer I'm looking for, how would you send the notification in the function, all this is related to how you will implement the function so it's a given, what I want to know is how you will send the notification

**Comment by dhananjay-Byte** [comment]
once the users matched there will be a notification method on the top right of the chat box below anonymous user section.

**Comment by Dun-sin** [comment]
> once the users matched there will be a notification method on the top right of the chat box below anonymous user section.

From every you've said, it's clear you don't the issue

**Comment by Dun-sin** [comment]
> once the users matched there will be a notification method on the top right of the chat box below anonymous user section.

From every you've said, it's clear you don't the issue

**Comment by dhananjay-Byte** [comment]
thank you for this resource. i believe i got the solution now and what you are looking for. i can work on this.

**Comment by dhananjay-Byte** [comment]
i was not aware there exits a notification web api. its not a complex implementation. i just need to ask the user for the permission and if it granted then need to display the "title" , "body" or "icon" on the browser.

**Comment by Dun-sin** [comment]
> i was not aware there exits a notification web api. its not a complex implementation. i just need to ask the user for the permission and if it granted then need to display the "title" , "body" or "icon" on the browser. 

Yes pretty much, but hold on for a while I want to see how #309 is solved, so it can be the standard.

Check this issue -> #309 and see what we talked about while you wait also check the contributing guidelines

**Comment by dhananjay-Byte** [comment]
alright fair enough

**Comment by Dun-sin** [comment]
@dhananjay-Byte you can go ahead with this now

**Comment by dhananjay-Byte** [comment]
hey @Dun-sin , actually i need your opinion on notification text that user will see.
here is my version:
![Screenshot (452)](https://github.com/Dun-sin/Whisper/assets/82323909/b5b24bc4-351f-4d52-bcbf-da5e42f00308)

**Comment by dhananjay-Byte** [comment]
also if one is assigned to #307 i am willing to work on this too.

**Comment by Dun-sin** [comment]
> hey @Dun-sin , actually i need your opinion on notification text that user will see.
> here is my version:
> ![Screenshot (452)](https://github.com/Dun-sin/Whisper/assets/82323909/b5b24bc4-351f-4d52-bcbf-da5e42f00308)
> 

Better to use "You've found a match, don't keep your partner waiting"
Title should be more different from great news. Something simple like "Paired", "Get chatting" something more related to the context, saying "Great news" sounds like something an ad will say

**Comment by dhananjay-Byte** [comment]
@Dun-sin  i got your point. how about this one?
![Screenshot (455)](https://github.com/Dun-sin/Whisper/assets/82323909/28b63081-1056-45bc-8d4a-a9bb4f56e52b)

**Comment by Dun-sin** [comment]
> @Dun-sin i got your point. how about this one? ![Screenshot (455)](https://user-images.githubusercontent.com/82323909/272803447-28b63081-1056-45bc-8d4a-a9bb4f56e52b.png)

looks good

**Comment by dhananjay-Byte** [comment]
@Dun-sin instead partner why dont we use friend. it will be like  "dont keep your friend waiting".

**Comment by Dun-sin** [comment]
> @Dun-sin instead partner why dont we use friend. it will be like "dont keep your friend waiting".
no, please raise a PR
