### ISSUE TITLE
[FEATURE] send notification for new message

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#306]
### Description

Send a browser notification when a user gets a message, should be called here
https://github.com/Dun-sin/Whisper/blob/4b12bf53561e7c2e5f8188c40c1a7d10eba11978/client/src/components/Chat.jsx#L375-L382

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Kabewh** [comment]
picking this up

**Comment by nkBrew** [comment]
I'd like to try working on this. 

My plan would be to request permissions for the Notifications api on the main dashboard ( the page after you login), and then raise the Notification exactly where you're referring to.

What would you like in the Notification itself? Like the title, body, and would you like the icon changed? 
I thought the title could either be `Whisper` or the `UserName` of the sender, but I'm having trouble finding a method or context that maps SocketIds to UserNames client side. 
The body I thought could either be something like `You received a new message` or the message itself. 
Other than the favicon.ico, I'm not seeing a Whisper logo and I actually don't know if `.ico` is suitable for the Notifications API. I'll look into it. 

Let me know your thoughts.

**Comment by Dun-sin** [comment]
> I'd like to try working on this. 
> 
> My plan would be to request permissions for the Notifications api on the main dashboard ( the page after you login), and then raise the Notification exactly where you're referring to.
> 
> What would you like in the Notification itself? Like the title, body, and would you like the icon changed? 
> I thought the title could either be `Whisper` or the `UserName` of the sender, but I'm having trouble finding a method or context that maps SocketIds to UserNames client side. 
> The body I thought could either be something like `You received a new message` or the message itself. 
> Other than the favicon.ico, I'm not seeing a Whisper logo and I actually don't know if `.ico` is suitable for the Notifications API. I'll look into it. 
> 
> Let me know your thoughts.

Na you slayed.

A few things, yes let's keep the icon it's in the public folder in clients, the app is not a friends app fully so people don't have user name in while anonymously chatting, you missed that part. So instead of username it's just going to be "Anonymous Partner".

The body content made me think why don't you make that the title.

In conclusion,
- you will find the fav icon in public folder in the client
- the title should be "You received a new message on Whisper"
- the body is the message itself

**Comment by Dun-sin** [comment]
So @nkBrew I will be assigning it you,  Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Code-Magic/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by nkBrew** [comment]
Wanted to give an update since I've been a bit quiet. 

Have worked on this, had work and some family stuff this weekend. Here's a preview of the commit + changes
https://github.com/Dun-sin/Whisper/compare/main...nkBrew:Whisper:BrowserNotificationMessage

Will be making a proper pull request tomorrow, to get hacktoberfest credit,  unless you have major complaints @Dun-sin.

**Comment by Dun-sin** [comment]
> Wanted to give an update since I've been a bit quiet. 
> 
> Have worked on this, had work and some family stuff this weekend. Here's a preview of the commit + changes
> https://github.com/Dun-sin/Whisper/compare/main...nkBrew:Whisper:BrowserNotificationMessage
> 
> Will be making a proper pull request tomorrow, to get hacktoberfest credit,  unless you have major complaints @Dun-sin. 

Hacktoberfest started hours ago

**Comment by Dun-sin** [comment]
> Wanted to give an update since I've been a bit quiet. 
> 
> Have worked on this, had work and some family stuff this weekend. Here's a preview of the commit + changes
> https://github.com/Dun-sin/Whisper/compare/main...nkBrew:Whisper:BrowserNotificationMessage
> 
> Will be making a proper pull request tomorrow, to get hacktoberfest credit,  unless you have major complaints @Dun-sin. 

I can't have complaints until you create a PR
