### ISSUE TITLE
[FEATURE] send notification for user inactivity

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#308]
### Description

Send a browser notification if the partner the user is talking to hasn't response, we send a reminder notification like “your partner isn't responding, want to leave?”

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Intekhabilyas** [comment]
@Dun-sin Please assign this to me

**Comment by Dun-sin** [comment]
> @Dun-sin Please assign this to me

I'm sensing some spamming activity from you, pick one issue and let me know which you actually want right now

**Comment by Intekhabilyas** [comment]
@Dun-sin can you assign this [BUG]: prop-types devDependency not in package.json #304 to me?

**Comment by Dun-sin** [comment]
> @Dun-sin can you assign this [BUG]: prop-types devDependency not in package.json #304 to me?

Already assigned

**Comment by harrylongia** [comment]
I can do this. If it is not assigned. assign it to me

**Comment by Dun-sin** [comment]
> I can do this. If it is not assigned. assign it to me

how would you do this?

**Comment by Dun-sin** [comment]
> We already have chat context that can store the time when the user last sent a message and if after a set interval we can check whether the user has responded or not. if the user selects disconnect then we can disconnect or else reset the interval back to zero. If you have a better approach or if I missed anything. would be glad to hear

your method work, will assign it to you. Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
