### ISSUE TITLE
[FEATURE] [REFACTOR]: Move all socket events into constant variables

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#310]
### Description

Currently, all socket events a used as is in strings, which means there are more chances for bugs should there be a change in the event name for an event that is listened to at multiple places. It would be better to move all socket events into constants, located in one place. This also gives room for code documentation. i.e. we can add comments to each variable, explaining what the particular event does.

E.g:

Assuming I'm listening to `receive_message` event in two files `A.jsx` and `B.jsx`, this is how I'd do it currently:

```js
// A.jsx
socket.on('receive_message', onReceiveMessage);
```
```js
// B.jsx
socket.on('receive_message', onReceiveMessage);
```

Now, this works, but should in case we later decide to change the event name from `receive_message` to something like `new_message`, we'd have to go through every file containing `receive_message`, which is prone to errors. Plus, it becomes difficult to understand what `receive_message` does.

Instead, it would be best to do this:

```js
// constants.js

// Emitted when a new message is sent
export const NEW_MESSAGE_EVENT = 'receive_message'
```

```js
// A.js
socket.on(NEW_MESSAGE_EVENT, onNewMessage)
```
```js
// B.js
socket.on(NEW_MESSAGE_EVENT, onNewMessage)
```

With this restructuring, we get documentation on what `NEW_MESSAGE_EVENT` is, plus changing the actual event name becomes easier, and less prone to errors

### Additional information

This applies to the whole codebase (backend & frontend),
if you want to work on this create the file outside the client/server it should be under the same level as the folder itself
for example:
|- client
|- server
|- constant.js
### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
good idea

**Comment by mathiasayivor** [comment]
It can be located withing a shared directory like `shared` or `common` at root level

**Comment by govardhanshah456** [comment]
hey there, I would like to work on this issue.

**Comment by Dun-sin** [comment]
> hey there, I would like to work on this issue.

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by MaybeSHAH** [comment]
hey there, I would like to work on this issue.

**Comment by Dun-sin** [comment]
> hey there, I would like to work on this issue.

It's clearly already assigned, always check that first
