### ISSUE TITLE
Wrong positioning of placeholder text

### ISSUE THREAD

**Issue by bintus-ux** [Dun-sin/Whisper#313]
### Description

Placeholder for inputting message(s) in chat is positioned wrongly, it was not centered right.

### Screenshots

![whisper img](https://github.com/Dun-sin/Whisper/assets/122406759/a7b9a056-8b01-44ef-ba22-eae85c9329ed)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by mathiasayivor** [comment]
I think this should be resolved in #302.

**Comment by Dun-sin** [comment]
> I think this should be resolved in #302.

exactly, but will leave it open just in case

**Comment by bintus-ux** [comment]
Can I be assigned the task?

**Comment by Dun-sin** [comment]
> Can I be assigned the task?

i assigned you the other, so just fix it there, then call both issue numbers

**Comment by bintus-ux** [comment]
Alright, on it!

**Comment by Dun-sin** [comment]
> Sounds good to me. I'm willing to contribute.
> Please assign it to me.

You are spamming, stop or you'll be blocked

**Comment by bishwobista** [comment]
@Dun-sin since, I am not working on anything, can I get this one?

**Comment by bintus-ux** [comment]
I’m on it bro.

**Comment by bishwobista** [comment]
> I’m on it bro.

You are not assigned tho

**Comment by Dun-sin** [comment]
> @Dun-sin since, I am not working on anything, can I get this one?

Already assigned

**Comment by bishwobista** [comment]
Oh sorry, It showed No one assigned. so

**Comment by Dun-sin** [comment]
> Oh sorry, It showed No one assigned. so
> 

I understand my bad here and also next time read the past comments in a issue, if you did you would have known he was working on it👍🏽

**Comment by ArnabBCA** [comment]
> > Oh sorry, It showed No one assigned. so
> 
> I understand my bad here and also next time read the past comments in a issue, if you did you would have known he was working on it👍🏽

Hey Can i Work on this issue?
