### ISSUE TITLE
[FEATURE] give an indication when profile is updated

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#317]
### Description

When a user updates their profile, they get an indication that it's updated, just a text under the delete account button.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by 9josky** [comment]
Hi @Dun-sin kindly assign this to me

**Comment by Dun-sin** [comment]
> Hi @Dun-sin kindly assign this to me
> 

Sure, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
