### ISSUE TITLE
[FEATURE] [CHORE] Add `.eslintcache` to gitignore

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#318]
### Description

This file contains nothing useful rather than cache, and it's causing unnecessary git errors/warnings. It would be better to add it to gitignore

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Won't assign this to you as it's a good first issue

**Comment by ShatilKhan** [comment]
Hi @Dun-sin , can you assign this one to me?
I am new to open source & have done some contributions

**Comment by Dun-sin** [comment]
> Hi @Dun-sin , can you assign this one to me?
> I am new to open source & have done some contributions
> 

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by ShatilKhan** [comment]
Sure! thanks for the guidance!
