### ISSUE TITLE
[BUG]: Error in message normalisation

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#319]
### Description

I don't know if this is intentional, but it seems I can't type certain characters. E.g I can't send a message like "vim >>> emacs". It gets replaced with "vim emacs" when I send the message.

When I checked, it's coming from here:
https://github.com/Dun-sin/Whisper/blob/23fe79f946e8b1e5a67c8592bd778ef23100fa35/client/src/components/Chat.jsx#L218-L221

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
Not a bug but intentional.

**Comment by mathiasayivor** [comment]
Why is that? I mean it prevents me from expressing myself.
