### ISSUE TITLE
[BUG] Error in parsing messages containing bad words

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#320]
### Description

When I send a message that contains a bad word, the app crashes for me and my buddy, I expect a warning message, not a crashed app.

The bug is coming from this line:
https://github.com/Dun-sin/Whisper/blob/23fe79f946e8b1e5a67c8592bd778ef23100fa35/client/src/components/Chat.jsx#L441

This is in the same group as #319, perhaps creating a new milestone would be great.

### 🥦 Browser

Other

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by VaibhavKVerma** [comment]
Hi @Dun-sin @mathiasayivor.Can you assign this issue to me?

**Comment by Dun-sin** [comment]
> Hi @Dun-sin @mathiasayivor .Can you assign this issue to me?

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
