### ISSUE TITLE
[FEATURE] Indicate particular message being replied

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#321]
### Description

Currently, messages can only be quoted. Which makes it sometimes hard to know which message is being replied. It would be great to indicate which message is being replied to, and the user should be able to scroll to the original message by clicking on it in the reply.

It would also be very helpful if the original message is animated after the scroll.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
Still thinking if I want this one, will Keep it inactive

**Comment by mathiasayivor** [comment]
Do you want it added now?

**Comment by Aadilmalik70** [comment]
@Dun-sin sir can yo uplease assign this task to me

**Comment by Dun-sin** [comment]
> Do you want it added now?

Yes

**Comment by mathiasayivor** [comment]
🤣 @Dun-sin what's up with people calling you sir?

**Comment by Dun-sin** [comment]
> 🤣 @Dun-sin what's up with people calling you sir?

Two things happen when they do, I ignore it or I correct them. Right now, I don't have the energy to correct them so the former is the default😂

**Comment by Aadilmalik70** [comment]
Can i work on this issue @Dun-sin

**Comment by mathiasayivor** [comment]
@Dun-sin anyone working on this?

**Comment by Dun-sin** [comment]
> @Dun-sin anyone working on this?

no

**Comment by mathiasayivor** [comment]
Ok. I'd like to work on this.
