### ISSUE TITLE
[FEATURE] allow anonymous user to create an account

### ISSUE THREAD

**Issue by dhananjay-Byte** [Dun-sin/Whisper#331]
### Description

In the profile section if user is logged anonymously we can add a link or button which will navigate the user to the login page if they want to create their profile. This can improve the overall user experience.

### Additional information

Here's what you need to do for this issue:
- [ ] prompt anonymous user to create an account by asking them to input their email. 
- [ ] use the current loginID to register the user in Mongodb. Replace the objectid default from Mongodb to the current loginID
- [ ] update the auth for the user, in auth Context
- [ ] use kinde.com api to add the user to kinde after the successful register

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

none

**Comment by bishwobista** [comment]
can you assign this to me

**Comment by Dun-sin** [comment]
Good idea, I will assign it to someone else as it's a good first issue material.

**Comment by Dun-sin** [comment]
> can you assign this to me

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by bishwobista** [comment]
I added a link that points to /login. But It does not redirect to /login because the user is still logged as auth. Should I log the user out when they click on login?

**Comment by Dun-sin** [comment]
> I added a link that points to /login. But It does not redirect to /login because the user is still logged as auth. Should I log the user out when they click on login?

actually there's more that should go into this, i just realized it's not that simple

**Comment by Dun-sin** [comment]
if you still want it, i can still guide you

**Comment by bishwobista** [comment]
Yes please, I will try my best.

**Comment by Dun-sin** [comment]
> Yes please, I will try my best.

let's move this conversation to the discord

**Comment by Dun-sin** [comment]
@bishwobista tag me on discord

**Comment by azr-arch** [comment]
@Dun-sin hey man can i give this a go ?

**Comment by Dun-sin** [comment]
> @Dun-sin hey man can i give this a go ?
> 

I updated the issue description with what you should do, if it's something you can do indicate. It's a full stack issue so you'll be working with the frontend and backend

**Comment by shivamsethi** [comment]
@Dun-sin - I can work on this. Can you assign this to me?

**Comment by Dun-sin** [comment]
> @Dun-sin - I can work on this. Can you assign this to me?

Did you read the issue description carefully?

**Comment by shivamsethi** [comment]
@Dun-sin  - Yes. Seen additional info steps too.

**Comment by Dun-sin** [comment]
> @Dun-sin  - Yes. Seen additional info steps too.

Ok, will assign it to you, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Code-Magic/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by Dun-sin** [comment]
@shivamsethi it's been too long since an update for this, kindly raise a PR

**Comment by shivamsethi** [comment]
Hey @Dun-sin  - Was working on weekend only on this one. I can raise the PR sometime this week. Does that work for you?

**Comment by Dun-sin** [comment]
> Hey @Dun-sin - Was working on weekend only on this one. I can raise the PR sometime this week. Does that work for you?

sure, please don't let it pass this week.

**Comment by shivamsethi** [comment]
@Dun-sin - One question regarding _**prompt anonymous user to create an account by asking them to input their email.**_

How and when to prompt the user? Should we present an input box right on the page where we are currently showing the **Please create an account** message?

**Comment by Dun-sin** [comment]
> @Dun-sin - One question regarding _**prompt anonymous user to create an account by asking them to input their email.**_
> 
> How and when to prompt the user? Should we present an input box right on the page where we are currently showing the **Please create an account** message?

yes

**Comment by mathiasayivor** [comment]
Can the title of the issue be updated to properly describe what it's trying to solve?

**Comment by mathiasayivor** [comment]
> Can the title of this issue be updated to properly describe what it's trying to solve?

@Dun-sin @shivamsethi

**Comment by Dun-sin** [comment]
@shivamsethi a little note, you have 7 days for this PR🙌🏽

**Comment by shivamsethi** [comment]
@Dun-sin  - Sure :)

**Comment by Dun-sin** [comment]
@shivamsethi 7 days are up, if there's no PR by the end of today, you will have to be unassigned

**Comment by mathiasayivor** [comment]
@Dun-sin can the title of this issue be updated to reflect what it's trying to solve?

**Comment by mathiasayivor** [comment]
I have a question. Is the goal to just add a link, that redirects the user to auth page to login with their email, or to enable users update their email without losing their data + current session?

**Comment by Dun-sin** [comment]
> I have a question. Is the goal to just add a link, that redirects the user to auth page to login with their email, or to enable users update their email without losing their data + current session?

read the issue description

**Comment by mathiasayivor** [comment]
I did read the description, but it's unclear. Redirecting to login page means user would be logged out, which means session data would be automatically lost. Otherwise, the issue description didn't explicitly mention the users state to be maintained.

**Comment by Dun-sin** [comment]
> I did read the description, but it's unclear. Redirecting to login page means user would be logged out, which means session data would be automatically lost. Otherwise, the issue description didn't explicitly mention the users state to be maintained.

Are we reading the same thing? 
![Screenshot_2023-10-22-08-59-47-717_com.github.android-edit.jpg](https://github.com/Dun-sin/Whisper/assets/78784850/b8a914de-280b-4bf5-9ed6-86a968048b2a)
