### ISSUE TITLE
[FEATURE] Enable user play fun games whiles waiting to be paired with a new buddy

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#333]
### Description

This could keep users on the app for some time, and make the waiting time less boring and more fun.
 
The game doesn't have to be complex.

Users may even choose the type of game they'd like to play from the list of available options.

And maybe somewhere in the future, they can play it with their buddy?

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
good idea, but no
