### ISSUE TITLE
[FEATURE] Profile picture

### ISSUE THREAD

**Issue by kom-senapati** [Dun-sin/Whisper#343]
### Description

I wanted to change my profile pic in the "My Profile" section.

### Screenshots

![image](https://github.com/Dun-sin/Whisper/assets/92045934/5143ea8b-473a-471c-b7a6-d3a56c23205c)

### Additional information

An avatar picker can also be added so that it would be easy to just pick an avatar rather than search for a profile picture elsewhere.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
Good idea

**Comment by pateldivyesh1323** [comment]
@Dun-sin Gravatar provides avatar from user's email id, it will return the current image which user uses on his email id.

**Comment by Dun-sin** [comment]
> @Dun-sin Gravatar provides avatar from user's email id, it will return the current image which user uses on his email id.

Not a good idea, users won't want that especially on an anonymous app, there also needs to be a way to avoid nude/unsafe images

**Comment by Haris-Mohanty** [comment]
Hi @Dun-sin,  Could you please assign me this issue?

**Comment by Dun-sin** [comment]
> Hi @Dun-sin, Could you please assign me this issue?

how would you fix this?

**Comment by Haris-Mohanty** [comment]
@Dun-sin, Ask the user to upload their profile pic and store in database then fetching from database and showing in UI.

**Comment by Dun-sin** [comment]
> @Dun-sin, Ask the user to upload their profile pic and store in database then fetching from database and showing in UI.

how would you detect nude photos

**Comment by Haris-Mohanty** [comment]
Employ object detection models to identify objects commonly found in explicit content, such as nudity-related objects or sexual acts.

**Comment by Dun-sin** [comment]
> Employ object detection models to identify objects commonly found in explicit content, such as nudity-related objects or sexual acts.

how?

**Comment by darknight2135** [comment]
[this](https://github.com/infinitered/nsfwjs) can work i guess

**Comment by Dun-sin** [comment]
> [this](https://github.com/infinitered/nsfwjs) can work i guess

how would you?

**Comment by afeefuddin** [comment]
Hey @Dun-sin we can add an avatar picker instead of letting user to upload the image. I would like to work on this issue

**Comment by Dun-sin** [comment]
> Hey @Dun-sin we can add an avatar picker instead of letting user to upload the image. I would like to work on this issue

I do not agree with that change, because it has to be both options or users upload theirs, mainly because it doesn't how at the anonymous part of chatting, but it will when they get added as friends, see my point?

**Comment by ashurohilla** [comment]
hey @Dun-sin  can we use light weight  ml model to review the uploaded image and show on the ui after finding the image is relevant  or not

**Comment by shivaY0** [comment]
Hi @Dun-sin,
I like to work on this issue.
Our main problem is to detect the nudity/unsafe images that can be done using API eg : google cloud vision api* , AWS Rekognition*, Microsoft Azure Content Moderator etc...
I'm familiar with * marked APIs.
There is a link might be help : https://cloud.google.com/vision/docs/detecting-safe-search#vision_safe_search_detection-nodejs
And also there are so many docs to help me to solve this issue.
If you think its good way to approach, Please assign me!
Thank you!

**Comment by hubsMIT1** [comment]
Hi @Dun-sin,
I like to work on this issue.
Our main problem is to detect the nudity/unsafe images that can be done using API eg : google cloud vision api* , AWS Rekognition*, Microsoft Azure Content Moderator etc...
I'm familiar with * marked APIs.
There is a link might be help : https://cloud.google.com/vision/docs/detecting-safe-search#vision_safe_search_detection-nodejs
And also there are so many docs to help me to solve this issue.
If you think its good way to approach, Please assign me!
Thank you!

**Comment by Dun-sin** [comment]
> Hi @Dun-sin,
> I like to work on this issue.
> Our main problem is to detect the nudity/unsafe images that can be done using API eg : google cloud vision api* , AWS Rekognition*, Microsoft Azure Content Moderator etc...
> I'm familiar with * marked APIs.
> There is a link might be help : https://cloud.google.com/vision/docs/detecting-safe-search#vision_safe_search_detection-nodejs
> And also there are so many docs to help me to solve this issue.
> If you think its good way to approach, Please assign me!
> Thank you!

Sounds good, you've got it, Sure, thanks for wanting to contribute.  Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
