### ISSUE TITLE
Adding an emoji feature in chat section 

### ISSUE THREAD

**Issue by AyushPathak7074** [Dun-sin/Whisper#347]
### Description

To express ourselves more clearly , we often use emoji so involving a emoji feature will help to communicate better

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
this is pretty huge for your first issue, you will have to work on implementing it and saving it in the backend too
