### ISSUE TITLE
Empty Message passed in the chat

### ISSUE THREAD

**Issue by ArnabBCA** [Dun-sin/Whisper#348]
### Description

The Input field is not checking whether the input message is empty. 

### Screenshots

![Empty](https://github.com/Dun-sin/Whisper/assets/113178195/32f0bfdb-c226-464e-aa13-1e356e37707e)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by ArnabBCA** [comment]
I want to work on this issue :)

**Comment by Dun-sin** [comment]
> I want to work on this issue :)

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
