### ISSUE TITLE
[OTHER] : The bad words that are not allowed, That are very limited in the `badWords.js` file

### ISSUE THREAD

**Issue by Devanshukoli** [Dun-sin/Whisper#352]
### What would you like to share?

* I have noticed that `badWords.js` file, There are some listed badwords that are generally not allowed to chat. And I have find it limited.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
if you are willing to make a pr you have to tell me what you are going to do, you are just telling me the problem

**Comment by Devanshukoli** [comment]
I am going to add more bad words. ( I mean in the `badWords.js` file). 
Such that the chatting experience can be more peaceful and healty.

**Comment by Dun-sin** [comment]
> I am going to add more bad words. ( I mean in the `badWords.js` file). Such that the chatting experience can be more peaceful and healty.

yeah obviously but which

**Comment by Devanshukoli** [comment]
Let me give you a file, 

[swear.txt](https://github.com/Dun-sin/Whisper/files/12779781/swear.txt)

**Comment by Dun-sin** [comment]
will actually close this, check out the new one i'm going to create soon

**Comment by Devanshukoli** [comment]
ok
