### ISSUE TITLE
[OTHER] delete the gitignore in the root folder

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#353]
### What would you like to share?

delete this
https://github.com/Dun-sin/Whisper/blob/main/.gitignore

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by vamsi-spoidey7** [comment]
i would like to work on this. please assign to me

**Comment by SiddharthaKR** [comment]
Hi there, I'd be happy to look into the mentioned bug. Please assign this to me

**Comment by Dun-sin** [comment]
> i would like to work on this. please assign to me

Definitely, thanks for wanting to contribute, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.
