### ISSUE TITLE
[FEATURE] better implementation for bad words

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#355]
### Description

We are manually checking the bad words and once it's found we don't send the message which isn't a good UX, there's a better way, here's the task for this issue:
- use this NPM package instead -> [bad-words-next](https://www.npmjs.com/package/bad-words-next).
- instead of replacing the message like it's done here, use the package to add a filler to the message
https://github.com/Dun-sin/Whisper/blob/97c07854cc7a804d4274ef2fefee91fcea114b88/client/src/components/Chat.jsx#L192-L210
- use socketio to let the partner know if that the user was trying to send a bad word, but don't replace the message just put a small text under the message of the sender of the bad word, with the warning message.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
@Devanshukoli

**Comment by Devanshukoli** [comment]
I can't say until I try. Please assign it to me. I want to work  on it.

**Comment by Dun-sin** [comment]
> I can't say until I try. Please assign it to me. I want to work on it.

okay, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Code-Magic/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by Dun-sin** [comment]
> I apologize. There's so much going on with me. And Now I have to take rest.
> 
> I am really sorry for not informing you in advance.

when can you be back? this week?

**Comment by Devanshukoli** [comment]
Hello, @Dun-sin Hey I am messaging you to letting you know that I am not feeling well so I might not be able to complete this  
assigned issue. Please go ahead and assign someone else. 

@mariamsayeed  can you take it ?

**Comment by apikmeister** [comment]
Hi, I would like to try and work and this. Can you assign this to me?

**Comment by Dun-sin** [comment]
> Hi, I would like to try and work and this. Can you assign this to me?

Sure, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by Dun-sin** [comment]
@apikmeister your 7 days is up according to the contributing guideline, today is the last day, if there's no pull request you will be unassigned
