### ISSUE TITLE
[BUG] don't allow empty quote

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#356]
### Description

if a quote reply is empty, a message shouldn't be sent

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Pushkarm029** [comment]
can you assign me this issue? @Dun-sin

**Comment by Dun-sin** [comment]
> can you assign me this issue? @Dun-sin

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
