### ISSUE TITLE
[FEATURE] add spam detection

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#357]
### Description

We need a way to detect spam, block the user and their IP with the user email if it has one

### Additional information

- [ ] have a schema to store all blocked IPs with the user email if it has one

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by aswin2108** [comment]
This is an interesting issue! Never done it before, so I would love to take this up! Can you assign me the issue?

**Comment by Dun-sin** [comment]
> This is an interesting issue! Never done it before, so I would love to take this up! Can you assign me the issue?

you sure you're up for the challenge?

**Comment by aswin2108** [comment]
Yeah lets try it out! Do you have any resource one where I can read on this? Else I'll find it myself!

**Comment by Dun-sin** [comment]
> Yeah lets try it out! Do you have any resource one where I can read on this? Else I'll find it myself! 

I've got nothing, but good luck, will assign it to you, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by aswin2108** [comment]
@Dun-sin Forgot to ask you, is this going to be like a report button? So after reporting a person the blocking should happen??? I think this is for random buddies mode right? If blocking happens instantaneously then people can misuse it. So how would this look like according to your plan?

**Comment by Dun-sin** [comment]
@aswin2108 been inactive for too long as per the rules you are unassigned

**Comment by mathiasayivor** [comment]
Is blocking the user's IP a good idea?

**Comment by Dun-sin** [comment]
> Is blocking the user's IP a good idea?

yep

**Comment by Dun-sin** [comment]
> Is blocking the user's IP a good idea?

yep

**Comment by mathiasayivor** [comment]
I mean it's possible multiple using may be sharing the same ip

**Comment by Dun-sin** [comment]
> I mean it's possible multiple using may be sharing the same ip

will cross that bridge when we get there
