### ISSUE TITLE
[FEATURE] add SEO

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#358]
### Description

if you type Whischat on Google this app is number 1 but when it's a keyword it's no where ranking

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Alkaison** [comment]
Hi @Dun-sin, I would like to work on this issue and help resolve the SEO problem by implementing the following things:

- better `meta` tags content (improving the description and keywords).
- adding `Open Graph meta data` to increase indexing score.
- adding `structured data for google search`.

I have previously worked on SEO for my portfolio to increase its ranking on search engines like Google, Bing. I would be contributing under the Hacktoberfest. Please assign it to me.
