### ISSUE TITLE
[OTHER] Request to rewrite schemas

### ISSUE THREAD

**Issue by drvnprgrmr** [Dun-sin/Whisper#362]
### What would you like to share?

I've checked and the current schemas used in this project doesn't look like it will scale well and there are also some redundancies and inefficiencies. 

Now of course rewriting the schemas would also mean changing a lot of the current structure of the code base (which I think is really necessary) but I am willing to dedicate some time to that.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Be more specific about the problem and possible solutions

**Comment by drvnprgrmr** [comment]
Okay, sorry about that.

![image](https://github.com/Dun-sin/Whisper/assets/67306305/4b5a6ea0-f585-46a1-a0d2-9629a07fa80b)

For one I feel like the message model needs to have a receiver field to specify the recipient of the message (even if it's an anonymous user).

**Comment by drvnprgrmr** [comment]
![image](https://github.com/Dun-sin/Whisper/assets/67306305/e54747e7-1e3c-4037-aeb5-b7a1df424805)

Also, while storing all message ids in the chat model might work for anonymous chats which are short lived it likely won't scale well for users with accounts majorly because the list will keep growing and mongodb imposes a 16mb limit per document hence sooner or later you'll get errors from mongodb. 

I suggest to remove this list and instead index the sender and receiver on the message and then query the messages collection when you want to get chat messages.

**Comment by drvnprgrmr** [comment]
As an aside, I noticed 'mongodb' is listed as a dependency in package.json but that's not required as it's a required dependency of 'mongoose'. Just saying :)

**Comment by Dun-sin** [comment]
> Okay, sorry about that.
> 
> ![image](https://github.com/Dun-sin/Whisper/assets/67306305/4b5a6ea0-f585-46a1-a0d2-9629a07fa80b)
> 
> For starters I feel like the message model needs to have a receiver field to specify the recipient of the message (even if it's an anonymous user).

Good spot, but i disagree

**Comment by Dun-sin** [comment]
> 
> ![image](https://github.com/Dun-sin/Whisper/assets/67306305/e54747e7-1e3c-4037-aeb5-b7a1df424805)
> 
> Also, while storing all message ids in the chat model might work for anonymous chats which are short lived it likely won't scale well for users with accounts majorly because the list will keep growing and mongodb imposes a 16mb limit per document hence sooner or later you'll get errors from mongodb. 
> 
> I suggest to remove this list and instead index the sender and receiver on the message and then query the messages collection when you want to get chat messages.
> 
> 
> 

We'll cross that when we get there, no need to "scale" before we need to scale. Just over engineering at that moment

**Comment by drvnprgrmr** [comment]
> > Okay, sorry about that.
> > ![image](https://user-images.githubusercontent.com/67306305/272040499-4b5a6ea0-f585-46a1-a0d2-9629a07fa80b.png)
> > For starters I feel like the message model needs to have a receiver field to specify the recipient of the message (even if it's an anonymous user).
> 
> Good spot, but i disagree

Hi @Dun-sin! I would like to know why you disagree with this.

**Comment by Dun-sin** [comment]
> > > Okay, sorry about that.
> > > ![image](https://user-images.githubusercontent.com/67306305/272040499-4b5a6ea0-f585-46a1-a0d2-9629a07fa80b.png)
> > > For starters I feel like the message model needs to have a receiver field to specify the recipient of the message (even if it's an anonymous user).
> > 
> > Good spot, but i disagree
> 
> Hi @Dun-sin! I would like to know why you disagree with this.

It's not needed, would be when we are doing the friends section, but anonymous section not needed👍🏽

**Comment by drvnprgrmr** [comment]
Okay thanks.

**Comment by drvnprgrmr** [comment]
Also since this repo contains both the server and client code, is it possible for there to be an extra tag indicating which one the issue addresses?

**Comment by Dun-sin** [comment]
Doing it right away
