### ISSUE TITLE
[FEATURE] <A feature to chat with ai profiles>

### ISSUE THREAD

**Issue by irfan-iiitr** [Dun-sin/Whisper#364]
### Description

As there are not many users available on the webiste ..the project remains unsucccessful ..
when a user comes and fines no other users online....he quits.
We can add chat with random ai with some given personality to attract more users.
Please assign me this task

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
chatgpt is literally there lol, if your solution to lack of users is add ai profiles that doesn't solve the lack of users, and it makes no sense, good idea but unrelated to this project, use chatgpt or other ai profiles
