### ISSUE TITLE
UI Flickering on start search

### ISSUE THREAD

**Issue by dudupopkhadze** [Dun-sin/Whisper#370]
### Description

When starting search for a buddy chat UI renders for a brief moment before showing the loading screen

### Screenshots

https://github.com/Dun-sin/Whisper/assets/48488310/e87fc9ec-572e-4199-8d6f-df5ad1faf6bb

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
How would you fix that?

**Comment by dudupopkhadze** [comment]
> How would you fix that?

From my current understanding `app.currentChatId` represents current active thread. So rendering loader conditionally with `app.isSearching || !app.currentChatId` would be enough for this issue to be resolved.

**Comment by Dun-sin** [comment]
> > How would you fix that?
> 
> From my current understanding `app.currentChatId` represents current active thread. So rendering loader conditionally with `app.isSearching || !app.currentChatId` would be enough for this issue to be resolved.

Alright, give it a go. Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
