### ISSUE TITLE
MongoDb Error Fixed in development Stage

### ISSUE THREAD

**Issue by Ayushpanditmoto** [Dun-sin/Whisper#371]
### Description

The `uri` parameter to `openUri()` must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()

### Screenshots

![Screenshot_3](https://github.com/Dun-sin/Whisper/assets/31253617/bd67cb8f-9d96-4000-b9c8-b2ac7847ca6c)
I have Fixed this error

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
i don't know what this is about

**Comment by Ayushpanditmoto** [comment]
@Dun-sin bruh mongodb not able to detect the path

**Comment by Ayushpanditmoto** [comment]
its resolves The uri parameter to openUri() must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()

**Comment by Dun-sin** [comment]
> its resolves The uri parameter to openUri() must be a string, got "undefined". Make sure the first parameter to `mongoose.connect()

sounds like a problem only on your PC
