### ISSUE TITLE
[FEATURE] save settings to the backend

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#380]
### Description

When a user logs out, the settings are gone, which isn't good.
tasks:
- [ ] save it to the database
- [ ] retrieve it when user logs in (only) and save it in local storage
- [ ] Every time the user goes to the settings page, retrieve the saved data from local storage

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by VaibhavKVerma** [comment]
Hey @Dun-sin can you assign this to me?

**Comment by Dun-sin** [comment]
> Hey @Dun-sin can you assign this to me?

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Code-Magic/blob/main/CONTRIBUTING.md#guidelines), else your PR will not be accepted and will be closed. Good Luck

**Comment by VaibhavKVerma** [comment]
Hey @Dun-sin should I save settings data in User DB Schema?

**Comment by Dun-sin** [comment]
> Hey @Dun-sin should I save settings data in User DB Schema?

Yes
