### ISSUE TITLE
[ENHANCEMENT] Separate middleware for Email Validation

### ISSUE THREAD

**Issue by destryptor** [Dun-sin/Whisper#381]
### What would you like to share?

In the userController.js file, the email validation is being carried out numerous times by defining it again and again in various POST requests. I believe it's a good practice to centralize validation logic to avoid duplication. I suggest defining a separate middleware like "validateEmail" and pass it onto the POST requests (or any other request) where the email validation needs to be carried out. Error handling can be modified similarly. 

I'd like to work on this enhancement issue myself. I am a beginner using Express, Node.Js and JS. This will be a great experience for me. So if you want, please assign this issue to me. Thanks :)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Cstrp** [comment]
Hi, I would like to work on this issue, could you assign this issue to me.

**Comment by Dun-sin** [comment]
@destryptor thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
