### ISSUE TITLE
[BUG] Stale app state

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#388]
### Description

The use effect here (BuddyMatcher.jsx line 99 - 216): https://github.com/Dun-sin/Whisper/blob/e2b4d414f726b8a177b0a753722cad7a6ac2790c/client/src/components/BuddyMatcher.jsx#L99 depends on `app.currentChatId`, which is not in its dependency array. This is causing unexpected behaviours.

### Additional information
Task:

- [ ] add `app.currentChatId` to the useEffect

### 🥦 Browser

Other

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by coolsyntax** [comment]
I would like to work on this issue. Could you please assign it to me?
Thanks

**Comment by Dun-sin** [comment]
> I would like to work on this issue. Could you please assign it to me?
> Thanks

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
