### ISSUE TITLE
[DOCS] Enhancing's the tagline in README.md

### ISSUE THREAD

**Issue by btrezzy** [Dun-sin/Whisper#389]
### Description

**Title:**
Proposing a New Tagline for Whisper

**Issue Description:**
 I believe that a catchy and memorable tagline could help convey the essence of the app more effectively and attract even more users.

I'd like to propose a new tagline for Whisper and I'd love to hear your thoughts on it. Here's the tagline suggestion:

"Whisper : Where Words are Heard, but Never Seen" instead of "An app to help you chat in secret"

I believe this tagline encapsulates the unique value and purpose of Whisper. It's concise, engaging, and reflects the app's core features and benefits.

Please consider this suggestion, and if you have any feedback or would like to discuss it further, I'd be more than happy to collaborate. If you decide to use it, it could potentially enhance the app's branding and user engagement.

Thank you for your time and consideration!

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
you believe wrong
