### ISSUE TITLE
[PROPOSAL] Implement custom email auth flow

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#390]
### Description

We currently depend on Kinde for passwordless logins, but this means user data (email) is being shared with a third party, hence violating anonymity and privacy policy of the app. Using Kinde also limits us to only a certain level of customisation (e.g we can't provide links for users to go back to whisper after logouts).

It would be great to implement our own custom auth flow, where an otp would be sent to the user, and verification is done in-app.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
doesn't violate any policy if you don't want your email shared that's why there's the anonymous option, thanks for raising tho
