### ISSUE TITLE
[FEATURE] better UI for the settings page

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#391]
### Description

The settings page looks a little clustered, we need a better design

### Screenshots

![image](https://github.com/Dun-sin/Whisper/assets/78784850/053c24de-675b-45e1-97d3-98577ee6f7d6)

### Additional information

if you want to work on this issue, make a figma design of what you could do better.
please don't create one if you aren't good at design

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Mansi782** [comment]
@Dun-sin i would like work on this can you please assign this to me

**Comment by Shreya-0999** [comment]
Hey @Dun-sin, I would like to work on the issue, Please go through the Figma design I have created and let me know if you have any suggestions. 
[Design](https://www.figma.com/file/VqRwcJdAITUsc7dzfgGK0y/Untitled?type=design&node-id=0%3A1&mode=design&t=CJ3yzclBgG8KWalQ-1)

**Comment by Dun-sin** [comment]
> Hey @Dun-sin, I would like to work on the issue, Please go through the [Figma](https://www.figma.com/file/VqRwcJdAITUsc7dzfgGK0y/Untitled?type=design&node-id=0%3A1&mode=design&t=CJ3yzclBgG8KWalQ-1) design I have created and let me know if you have any suggestions. 

Looks good, i just have one quick change, dark mode settings just got added so you should put it in your PR.

I will assign the PR to you, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#guidelines), else your PR will not be accepted and will be closed. Good Luck
