### ISSUE TITLE
Chat is not closing for other user if one user logout

### ISSUE THREAD

**Issue by afeefuddin** [Dun-sin/Whisper#396]
### Description

If two users has logged in anonymously for chat let us say X and Y, if X logout without closing the chat, the chat is not closing automatically for Y and they will never know if the X has logged out.

Ideally if the X has logged out it should close the chat for Y also, if the login is anonymously.

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by GeorgeET15** [comment]
Hi, I'd like to work on this issue can you please assign this to me

**Comment by Dun-sin** [comment]
well give it a go @afeefuddin, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by afeefuddin** [comment]
@Dun-sin Thanks for assigning the issue, I will follow all the guidelines.
