### ISSUE TITLE
[DOCS] Improve directory structure for the app

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#40]
### Description

I think it's better and a good practice to organize directories in a self-describing manner.
Currently, we can't distinguish between *Components*, *Pages* and *Routes* cos of the directory structure (i.e Everything is placed in the `components` directory).
I'm suggesting we re-structure it to something like this:
```
src
 +- app // Contains pure js files (i.e services, helpers)
 +- components // Self explanatory
 +- redux // Self explanatory
 +- pages // Self explanatory
 +- routes
     -- index.jsx // Default routes would be located here. This gives us the chance to split routes i guess-ish?
 -- App.css
 -- App.js
 -- index.js
 -- index.(css|scss)
// Other config/important files goes here
```
I think this is somehow related to #15 , but this is more of like the directory structuring

**Comment by mathiasayivor** [comment]
Also, we'd need to restructure the `server` directory but that'd be for later/when we're implementing the chatting features.
Perhaps I'd just open up a new issue for that as well

**Comment by Dun-sin** [comment]
thanks for this, I didn't know about proper structure. I will wait for someone else who wants to work on this since you work on a lot already.

Thanks for pointing this out

**Comment by mathiasayivor** [comment]
> @Dun-sin @renzil @Pradumnasaraf @Dharmik48 What are your thoughts? How do we go about this?

I think this would be necessary before we begin implementing the main features of the system...

**Comment by Dun-sin** [comment]
It's just directory structure, won't hinder much of the work to be done.

I will still leave it open for anyone else who wants to work on it

**Comment by mathiasayivor** [comment]
Then I'll work on it... may I?
