### ISSUE TITLE
[OTHER] Color of the text on the setting page should be more bright

### ISSUE THREAD

**Issue by AaadityaG** [Dun-sin/Whisper#401]
### What would you like to share?

Below I underlined the text with yellow line

![Capture](https://github.com/Dun-sin/Whisper/assets/114663382/fb4a4a07-8252-46f7-957f-0530c0df8925)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Pushkarm029** [comment]
please assign me this issue

**Comment by AaadityaG** [comment]
Yeah

**Comment by Shashankpantiitbhilai** [comment]
assign it to me

**Comment by Dun-sin** [comment]
> assign it to me

Be polite, don't spam until you get a response stick to one issue else you will be blocked

**Comment by Dun-sin** [comment]
@AaadityaG I will assign it to you but you will have to wait for this PR to be merged -> #397

**Comment by AaadityaG** [comment]
Thank you! @Dun-sin

**Comment by Dun-sin** [comment]
@AaadityaG you can start this

**Comment by AaadityaG** [comment]
OK
