### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by SusheelThapa** [Dun-sin/Whisper#403]
### What would you like to share?

I have looked into the readme section of the repository and i happen to figure out that some of the code block aren't aligned as they should apppear.

![image](https://github.com/Dun-sin/Whisper/assets/83917129/e630c795-a9e1-45fc-a946-6fa9cb4502e6)

As in above image we can see the align of the code blocks of `4` isn't aligned properly.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Keep in mind this won't count for hacktoberfest

**Comment by SusheelThapa** [comment]
@Dun-sin sure, please asign me

**Comment by Dun-sin** [comment]
> @Dun-sin sure, please asign me

Ok, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
