### ISSUE TITLE
[IMPROVEMENT] Replace Hard-Coded Status Codes for Improved Code Quality

### ISSUE THREAD

**Issue by hijal** [Dun-sin/Whisper#404]
### What would you like to share?

**Description**:
The current codebase hard-codes client response status codes, such as `200` and `404`, throughout the project. This approach can lead to maintainability challenges and make it harder for developers to understand the meaning of these status codes. I propose enhancing the codebase by introducing constant variables for these status codes, resulting in improved code readability and maintainability.

**Examples**:
Here is an example of how the code will change after implementing this improvement:

Before:
```javascript
res.status(406).json({ message: 'Email is invalid' });
```
**Add Constant variable**
```javascript
{

   .....,
   .....,
   NOT_ACCEPTABLE: 406
}
```
After:
```javascript
const { NOT_ACCEPTABLE } = require("../../constants.json");
```

```javascript
res.status(NOT_ACCEPTABLE).json({ message: 'Email is invalid' });
```

### Additional information

- This change will not only improve code quality but also make it easier to update or add new status codes in the future.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Shashankpantiitbhilai** [comment]
please assign it o me,i am interested

**Comment by Dun-sin** [comment]
Your concern is the backend right? So we can just use a js file instead of a json like in constants.

**Comment by Dun-sin** [comment]
I'm assigning it to you @hijal, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
