### ISSUE TITLE
[OTHER]

### ISSUE THREAD

**Issue by Sandesh-Pyakurel** [Dun-sin/Whisper#406]
### What would you like to share?

I looked into the readme section and found that the comment block on step 7 had mismatched indentation relative to step 6.

![Screenshot from 2023-10-12 12-20-27](https://github.com/Dun-sin/Whisper/assets/82999440/00b1f615-133a-4ebe-aa10-bf377e33a328)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Please use PR titles, will ignore any that doesn't have one in the future.

Your issue doesn't explain the issue

**Comment by varundhand** [comment]
Hi @Dun-sin , I'd like to work on this issue. Could you please assign it to me? Thanks!
