### ISSUE TITLE
Add Age Validation in Profile Section

### ISSUE THREAD

**Issue by varundhand** [Dun-sin/Whisper#410]
### Description

In the profile section's form, there is a label for "age", which allows users to update their age. However, currently, there is **no validation** in place, and **users can enter negative values**. To ensure data accuracy and consistency, we need to add age validation to ensure that **only positive values are accepted**.

### Screenshots

![Screenshot 2023-10-13 at 1 55 22 PM](https://github.com/Dun-sin/Whisper/assets/110025628/284ca01a-0f09-42bd-bb9b-437c621c17ac)
_Age shouldn't be negative._

### Additional information

- We should add client-side validation to prevent users from entering negative values for age. This can be achieved using HTML5 input attributes or JavaScript validation.

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Thilagavathi1** [comment]
Hi @varundhand i would like to work on this issue?could u please assign to me

**Comment by mit-anuj** [comment]
Hi @varundhand  I have worked on this tech stack and i can fix this issue within a day so please assign me this issue

**Comment by Dun-sin** [comment]
Good spot @varundhand assigned it to you, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by varundhand** [comment]
Hi @Dun-sin ,

I hope this message finds you well. I'm currently experiencing an issue with the **local setup of the project** and I could use some guidance.

I've followed the installation instructions outlined in the README file, and everything seems to be in order. However, when I attempt to login locally, I encounter an **"Invalid callback URL"** error. The specific error message is:

![Screenshot 2023-10-14 at 2 04 30 AM](https://github.com/Dun-sin/Whisper/assets/110025628/5fbf0438-0479-4033-ad3d-3924c617d8e0)

I believe there might be an issue with my **Kinde setup**, causing this problem.

And these are my Kinde app credentials:

![Screenshot 2023-10-14 at 2 07 10 AM](https://github.com/Dun-sin/Whisper/assets/110025628/700b80cc-6bed-4d7f-88ab-7ff6e8cd8a04)

I would greatly appreciate your assistance in troubleshooting this issue. 
Thank you in advance for your help!

Best regards,
varundhand

**Comment by Dun-sin** [comment]
> Hi @Dun-sin ,
> 
> I hope this message finds you well. I'm currently experiencing an issue with the **local setup of the project** and I could use some guidance.
> 
> I've followed the installation instructions outlined in the README file, and everything seems to be in order. However, when I attempt to login locally, I encounter an **"Invalid callback URL"** error. The specific error message is:
> 
> ![Screenshot 2023-10-14 at 2 04 30 AM](https://github.com/Dun-sin/Whisper/assets/110025628/5fbf0438-0479-4033-ad3d-3924c617d8e0)
> 
> I believe there might be an issue with my **Kinde setup**, causing this problem.
> 
> And these are my Kinde app credentials:
> 
> ![Screenshot 2023-10-14 at 2 07 10 AM](https://github.com/Dun-sin/Whisper/assets/110025628/700b80cc-6bed-4d7f-88ab-7ff6e8cd8a04)
> 
> I would greatly appreciate your assistance in troubleshooting this issue. 
> Thank you in advance for your help!
> 
> Best regards,
> varundhand
> 
> 

You can text normally and not talk like it's a formal letter, drop the chatGPT it's hard for me to read everything when you are just asking a simple question.

It should be the localhost/login.

Did you read the docs for how to implement it, just changing the name won't do, read their docs and use the necessary keys.

I can't help you past that I'm off the grid.
