### ISSUE TITLE
Update Tailwind CSS Classes for 'Save Changes' Button Color in Profile Section

### ISSUE THREAD

**Issue by varundhand** [Dun-sin/Whisper#412]
### Description

In the profile section, the **"Save Changes"** button should have a **green colour** according to the code. However, the current code in the repo uses **incorrect Tailwind CSS classes** for the button colour.

### Screenshots

**Incorrect Tailwind classes used:**

![Screenshot 2023-10-15 at 12 55 14 AM](https://github.com/Dun-sin/Whisper/assets/110025628/da3b6bef-c091-431b-9eed-44ba496a6905)

**before:**

![Screenshot 2023-10-15 at 12 47 09 AM](https://github.com/Dun-sin/Whisper/assets/110025628/ff3af3f8-a008-4db1-9f24-179d6aa512cb)

**after** (on using correct tailwind classes):

![Screenshot 2023-10-15 at 12 47 16 AM](https://github.com/Dun-sin/Whisper/assets/110025628/886535f0-15b5-4a44-b4d5-e8847e42a201)

### Additional information

We need to use `text-green-500`

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Thanks for raising, will make this a good first issue.

**Comment by varundhand** [comment]
sure, can you assign it to me? I ll raise the pr right away

**Comment by Dun-sin** [comment]
> sure, can you assign it to me? I ll raise the pr right away

Won't be assigning you as it's a good first issue and your previous PR isn't merged, read the project guidelines

**Comment by LintangDev** [comment]
can you assign me on these? thank you.

**Comment by kristenking** [comment]
Hello @Dun-sin! Could I work on this issue, please?

**Comment by Mohit-Vaswani** [comment]
Hello @Dun-sin I am good at Tailwind Css, assign it to me.

**Comment by tvermaashutosh** [comment]
@Dun-sin Please assign me this issue.

**Comment by harjotjuneja6** [comment]
Hello @Dun-sin can you assign this to me

**Comment by Dun-sin** [comment]
> Hello @Dun-sin! Could I work on this issue, please?

@kristenking 
Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
