### ISSUE TITLE
Bug in Friends section on Anonymous login

### ISSUE THREAD

**Issue by afeefuddin** [Dun-sin/Whisper#415]
### Description

If a user is logging in anonymously, the friends option should either be disabled or should ask user to create an account. 
Currently it shows "Feature coming soon".

### Screenshots

![Screenshot (51)](https://github.com/Dun-sin/Whisper/assets/126336384/e8815c4c-9612-45b7-b5f4-b150a5141514)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by afeefuddin** [comment]
Hey @Dun-sin Can you assign me this issue

**Comment by Dun-sin** [comment]
it's showing coming soon for a reason because the future is coming soon
