### ISSUE TITLE
[BUG] Settings page doesn't look good on mobile screens

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#416]
### Description

The Settings UI doesn't look good on mobile screens

### Screenshots

![Screen Shot 2023-10-15 at 11 17 42](https://github.com/Dun-sin/Whisper/assets/74247733/feae5b2b-4574-4ddc-9366-14b4134036b1)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by amitabh-sahu** [comment]
This issue can be resolved by either a different width on mobile or by adding a minimum width.
Please assign it to me, so I can go ahead with the changes.

**Comment by Dun-sin** [comment]
> This issue can be resolved by either a different width on mobile or by adding a minimum width. Please assign it to me, so I can go ahead with the changes.

sure, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by amitabh-sahu** [comment]
This issue can be closed as it is already resolved in the pull request [https://github.com/Dun-sin/Whisper/pull/424](#424)

**Comment by Dun-sin** [comment]
thanks for letting me know @amitabh-sahu
