### ISSUE TITLE
[BUG] Message Input not cleared after message is sent

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#417]
### Description

Message Input is not cleared after message is submitted/sent

### Screenshots

[Screencast from 15-10-23 11:26:40.webm](https://github.com/Dun-sin/Whisper/assets/74247733/d58e5543-052f-479c-86fb-7ee97fbcc51b)

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by dev-palwar** [comment]
can i work on this issue?

**Comment by Dun-sin** [comment]
> can i work on this issue?

sure, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whispr/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by dev-palwar** [comment]
Your "here" URL" is not found. I want to read the rules

**Comment by Dun-sin** [comment]
> Your "here" URL is not found. I want to read the rules

Fixed, try again

**Comment by dev-palwar** [comment]
hey, how do I test it? I have the same URL 'http://localhost:5173/founduser' running in a different browser, but I am unable to connect with myself. It takes too long and is not responding. MongoDB is also connected

**Comment by Dun-sin** [comment]
> hey, how do I test it? I have the same URL 'http://localhost:5173/founduser' running in a different browser, but I am unable to connect with myself. It takes too long and is not responding. MongoDB is also connected

Did you fill in the env for both frontend and backend?

**Comment by Shariar-Hasan** [comment]
can i get asigned?
i have fixed it.
i would like too be assigned to make a pull request 😀😀

**Comment by dev-palwar** [comment]
> can i get asigned?
> i have fixed it.
> i would like too be assigned to make a pull request 😀😀

If you've fixed it already then make make a PR

**Comment by Shariar-Hasan** [comment]
> > can i get asigned?
> > i have fixed it.
> > i would like too be assigned to make a pull request 😀😀
> 
> If you've fixed it already then make make a PR

it wont get merged as i am not who is assigned to do it 😓

**Comment by Shariar-Hasan** [comment]
> > can i get asigned?
> > i have fixed it.
> > i would like too be assigned to make a pull request 😀😀
> 
> If you've fixed it already then make make a PR

bro you fix it, as you are assigned ❤️
