### ISSUE TITLE
[FEATURE] Display instructions for shortcuts

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#419]
Tasks for this:
- [ ] for the input box when chatting, replace the placeholder with `press ctrl + enter to send message`
https://github.com/Dun-sin/Whisper/blob/c7c0e4ddafcf7babe12d2f22ccd3ccbdfb2f1ec2/client/src/components/Chat.jsx#L616-L622
- [ ] on the drop-down when chatting, for the close chat add the shortcut to the name which is `ctrl + shift + x`, add an element like this `div(parent element) > p(function e.g close chat) + p(shortcut)` with a tailwind class for the div of `flex space-between items-center`
https://github.com/Dun-sin/Whisper/blob/ab1a0caa53579a1eb931aa319b2f5ecd32987561/client/src/components/Anonymous.jsx#L211-L217
- [ ] for the second content of the drop-down, repeat the `div > p + p` format, but the shortcut for the find a new buddy is `ctrl + alt + n`
https://github.com/Dun-sin/Whisper/blob/ab1a0caa53579a1eb931aa319b2f5ecd32987561/client/src/components/Anonymous.jsx#L215-L217

### Are you willing to work on this issue ?

None

**Comment by aakash-gorai** [comment]
Hey @Dun-sin Greetings,
I am very new to Open Source, I want work on this issue, can you please assign this issue to me ?
Thank You

**Comment by sahilrohera10** [comment]
Hii @mathiasayivor @Dun-sin 
I am interested in this issue, i can add a tooltip for displaying the shortcuts or i can also have a new page, where we can show all the shortcuts for this application, i can proceed in either way, which suits best.
Please assign this issue to me.
Thanks

**Comment by Dun-sin** [comment]
> Hey @Dun-sin @mathiasayivor Greetings, I am very new to Open Source, I want work on this issue, can you please assign this issue to me ? Thank You

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by aakash-gorai** [comment]
Hey @Dun-sin, I was trying to understand the codebase. I want to know where will I find the message box component(file name), so that I could apply the changes to it?
Thank You.

**Comment by Dun-sin** [comment]
> Hey @Dun-sin, I was trying to understand the codebase. I want to know where will I find the message box component(file name), so that I could apply the changes to it? Thank You.

it's in the chat.jsx, here's a tip for next time learn how to use `react dev tools` it's a web extension:
https://github.com/Dun-sin/Whisper/blob/c7c0e4ddafcf7babe12d2f22ccd3ccbdfb2f1ec2/client/src/components/Chat.jsx#L616-L622

**Comment by avibiradar100** [comment]
Hey @Dun-sin  could you please assign me to this issue

**Comment by Dun-sin** [comment]
> Hey @Dun-sin could you please assign me to this issue

sure, follow the issue description and make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by avibiradar100** [comment]
Hey @Dun-sin Greetings,
This is my first open source contribution. Hope this PR looks all good. If there is any issue please inform me so that I can rework on it.
Thank You.

**Comment by Dun-sin** [comment]
> Hey @Dun-sin Greetings,
> This is my first open source contribution. Hope this PR looks all good. If there is any issue please inform me so that I can rework on it.
> Thank You.

keep in mind in the future you don't need to comment back on the Issue, it's not my first rodeo, so I see your PR and will definitely do the necessary. It will just cause unnecessary notifications for me and others.
