### ISSUE TITLE
[FEATURE] Add `Message Seen` indicator

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#420]
### Description

Currently, users are unable to know if their buddy has seen their message or not. It would be nice to be able to know whether your buddy has seen your message yet or not.

This may also help users decide if they should continue chatting or not.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by NEMYSESx** [comment]
hello I want to work on this

**Comment by nayakswadhin** [comment]
Hii I want to work on this issue, can you assign this issue to me

**Comment by Dun-sin** [comment]
> hello I want to work on this

how would you?

**Comment by NEMYSESx** [comment]
Creating new prop named "seen"
Purpose: The "seen" prop serves as a flag that indicates whether a message has been seen by the recipient.

When the sender sends a message, the recipient's client can send an acknowledgment back to the server, confirming that the message has been received. The server can then notify the sender that the message has been delivered and I will mark seen prop as true when I get a positive ACK

**Comment by NEMYSESx** [comment]
OR we can implement real-time communication using WebSocket to provide instant updates when a message is acknowledged or read. I will use the socket.io library for both the client and server sides

**Comment by Dun-sin** [comment]
Did you read the Readme of this project? You clearly didn't😆

**Comment by Dun-sin** [comment]
> is this really needed ? @Dun-sin 

Your question is unclear

**Comment by azr-arch** [comment]
> > is this really needed ? @Dun-sin
> 
> Your question is unclear

nvm
