### ISSUE TITLE
[BUG] Message Input height not corresponding to message content

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#421]
### Description

The message input height increases when the text grows, but does not decrease when the text length reduces (i.e when user deletes text, or clears the message entirely)

### Screenshots

[Screencast from 15-10-23 11:42:23.webm](https://github.com/Dun-sin/Whisper/assets/74247733/d5401f9b-9eff-4bb5-bfe8-20fd8ea2e1c9)

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by JatinPhogat** [comment]
Hii @Dun-sin @mathiasayivor  , i can fix it . can you please assign this issue it to me.

**Comment by Dun-sin** [comment]
> Hii @Dun-sin @mathiasayivor , i can fix it . can you please assign this issue it to me.

Sure, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by Dun-sin** [comment]
@JatinPhogat according to the guideline your time is up and if there's no PR by the end of the day, you will be unassigned

**Comment by Aryakoste** [comment]
Hii @Dun-sin. I can fix this, can you assign me this issue.

**Comment by Dun-sin** [comment]
> Hii @Dun-sin. I can fix this, can you assign me this issue.

Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
