### ISSUE TITLE
[FEATURE] Enable Users send emojis

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#423]
### Description

Currently, emojis can only be sent on mobile devices (possible due to emoji keyboard thingy), but not possible on Desktops (unless copied and pasted). It would be great to be able to send emojis in messages by picking the from a menu

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by nishitxmehta** [comment]
Hi @mathiasayivor, please assign me this issue. I can do this for you.

**Comment by amitabh-sahu** [comment]
Although there is the option to add emojis with shortcuts like "Command + Control + Space" on Mac and "Windows + ; (semi-colon)" or "Windows +. (period)" on Windows.

It can be done by using a library like "emoji-picker-react" or something else.

I also found this [blog](https://www.tiny.cloud/blog/build-a-chat-app-with-our-wysiwyg-editor/) which can be used to add some more options other than emojis.

Please assign me this issue and let me know what should be done.

**Comment by Dun-sin** [comment]
> Although there is the option to add emojis with shortcuts like "Command + Control + Space" on Mac and "Windows + ; (semi-colon)" or "Windows +. (period)" on Windows.
> 
> It can be done by using a library like "emoji-picker-react" or something else.
> 
> I also found this [blog](https://www.tiny.cloud/blog/build-a-chat-app-with-our-wysiwyg-editor/) which can be used to add some more options other than emojis.
> 
> Please assign me this issue and let me know what should be done.

What the issue says to be done is what should be done.

**Comment by Dun-sin** [comment]
assigned it to you @amitabh-sahu Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
