### ISSUE TITLE
[BUG] The default mode in the light/dark mode toggle is light

### ISSUE THREAD

**Issue by ahmed-bentajhamyani** [Dun-sin/Whisper#426]
### Description

The web site default mode is dark but in the light/dark mode toggle is light

### Screenshots

![image](https://github.com/Dun-sin/Whisper/assets/101653735/955afb27-2c58-4289-8116-5dd93770353c)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by itsankitbhusal** [comment]
can i work on this issue ? @ahmed-bentajhamyani

**Comment by ahmed-bentajhamyani** [comment]
I am willing to work on it

**Comment by itsankitbhusal** [comment]
okey @ahmed-bentajhamyani

**Comment by Dun-sin** [comment]
will give it to @itsankitbhusal, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by itsankitbhusal** [comment]
started working on this issue. @Dun-sin

**Comment by ahmed-bentajhamyani** [comment]
@Dun-sin why wouldn't you give it to me?

**Comment by Dun-sin** [comment]
> @Dun-sin why wouldn't you give it to me?

You just worked on something similar, I'm giving someone else a chance

**Comment by ahmed-bentajhamyani** [comment]
Fair enough 👍🏻

**Comment by JatinPhogat** [comment]
Hii can i work on this issue . If yes, please assign it to me.

**Comment by itsankitbhusal** [comment]
@Dun-sin request is made, a simple one, have a look.
