### ISSUE TITLE
[BUG] reminder for unresponsive partner still works after chat is closed

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#427]
### Description

The notification shouldn't do that after the chat is closed,
you can find the code for this here:
https://github.com/Dun-sin/Whisper/blob/359fd0a7b031379947b2e1f4cb7b48c1cde3d3f8/client/src/components/Chat.jsx#L443-L449

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by nishitxmehta** [comment]
Hi @Dun-sin, can you please assign me this issue. I can do this for you

**Comment by Dun-sin** [comment]
> Hi @Dun-sin, can you please assign me this issue. I can do this for you
ok, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by nishitxmehta** [comment]
Thanks @Dun-sin for assigning me, I'll start working on it.

**Comment by Dun-sin** [comment]
> Thanks @Dun-sin for assigning me, I'll start working on it.

Never mind, you are unassigned for spamming and blocked from this project

**Comment by afeefuddin** [comment]
Hey @Dun-sin Can you assign me this issue

**Comment by Dun-sin** [comment]
> Hey @Dun-sin Can you assign me this issue

Definitely, thanks for wanting to contribute, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.

**Comment by afeefuddin** [comment]
Hey @Dun-sin , I am not able to reproduce this issue, can you please clarify where the issue is?

**Comment by Dun-sin** [comment]
> Hey @Dun-sin , I am not able to reproduce this issue, can you please clarify where the issue is?

- have a chat with yourself for a while
- close the chat
- wait for 3-4 minutes (don't close the app, just the chat)

**Comment by Dun-sin** [comment]
@nishitxmehta according to the contributing guideline, your time is up and if there's a PR by the end of the day, you will be unassigned

**Comment by KirtiKamal** [comment]
Hey @Dun-sin  i just wanted to work on this issue kindly assign me

**Comment by Dun-sin** [comment]
> Hey @Dun-sin i just wanted to work on this issue kindly assign me

Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by KirtiKamal** [comment]
thanks @Dun-sin .. can you please describe the issue a little bit what actually you wanted to be done

**Comment by Dun-sin** [comment]
> thanks @Dun-sin .. can you please describe the issue a little bit what actually you wanted to be done

When you get Paired with a partner and you text and they don't reply, you get sent a notification telling you to leave if you want to.

The bug is even after you leave you still get the notification after the allocated time, the issue is saying fix that.

**Comment by KirtiKamal** [comment]
yes thank you now i got the issue

**Comment by KirtiKamal** [comment]
@Dun-sin Hyy actually i am new to opensource and can you please help to understand the code base. I got the issue and figured out what need to be done and i am facing problem to figuring out the correct jsx file to work. Can you please say i have to work on which file particularly

**Comment by Dun-sin** [comment]
> @Dun-sin Hyy actually i am new to opensource and can you please help to understand the code base. I got the issue and figured out what need to be done and i am facing problem to figuring out the correct jsx file to work. Can you please say i have to work on which file particularly 
> 

It's in chat.jsx

**Comment by KirtiKamal** [comment]
Yes i can see from the above but i dont think only in chat.jsx. Is that ?

**Comment by Dun-sin** [comment]
> Yes i can see from the above but i dont think only in chat.jsx. Is that ?

this is the PR that added this feature, you can study it -> #363

**Comment by KirtiKamal** [comment]
Okk sure

**Comment by Dun-sin** [comment]
@KirtiKamal according to the contributing guideline, your time is up and if there's a PR by the end of the day, you will be unassigned, you can request for extra time but not more than 5 days, but we need a response by the end of the day

**Comment by KirtiKamal** [comment]
> @KirtiKamal according to the contributing guideline, your time is up and if there's a PR by the end of the day, you will be unassigned, you can request for extra time but not more than 5 days, but we need a response by the end of the day

I am facing difficulty to resolve this issue.
You may unassign me.
