### ISSUE TITLE
[DOCS] Updating code_of_conduct file

### ISSUE THREAD

**Issue by sidwar007** [Dun-sin/Whisper#430]
### Description

There were a few grammatical errors that I found in the file and I would like to fix them.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
It's automatic from github
