### ISSUE TITLE
[FEATURE]  add Dependabot

### ISSUE THREAD

**Issue by Akshayp02** [Dun-sin/Whisper#432]
### Description

To add Dependabot to a project, create a dependabot.yml file in project root. Configure it to check for updates in project's dependencies, and set up notifications for automated pull requests. Dependabot will then help keep dependencies up-to-date, enhancing project stability and security.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
was thinking of adding this, thanks for raising. assigned to you, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
