### ISSUE TITLE
[FEATURE] Frontend settings page UI style change request

### ISSUE THREAD

**Issue by Shariar-Hasan** [Dun-sin/Whisper#434]
### Description

Fontend UI is not quite impressive.
may i change it a little bit good looking than this?
if yes, can you assign this issue to me 😀

### Screenshots

![image](https://github.com/Dun-sin/Whisper/assets/75330767/1e5f1b1c-8451-4f3e-bc18-2433164efd04)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
I can't trust yours if you don't show me what you want to do, feel free to use figma to send a design

**Comment by Shariar-Hasan** [comment]
![image](https://github.com/Dun-sin/Whisper/assets/75330767/7f8c3ca2-e1b3-43d8-8570-5ecf40e4b080)
is it okay to for the UI?

**Comment by Dun-sin** [comment]
> ![image](https://user-images.githubusercontent.com/75330767/275339563-7f8c3ca2-e1b3-43d8-8570-5ecf40e4b080.png) dear @Dun-sin is it okay to for the UI?

basically all you want to change is the background, add shadow and change text color, could have just said that, you made it sound like you were going to make a huge change, anyway, go ahead.

Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by Shariar-Hasan** [comment]
i didnt finished then,
i just wanted to show a demo as you asked for one.
😃🙂

**Comment by Shashankpantiitbhilai** [comment]
Assign this to me

**Comment by Upendra2003** [comment]
Hey @Dun-sin can you assign this to me..
