### ISSUE TITLE
[Enhancement] Add hover effect to login and login anonymously buttons on landing page

### ISSUE THREAD

**Issue by singodiyashubham87** [Dun-sin/Whisper#435]
### What would you like to share?

Add hover effect to login and login anonymously buttons on the landing page

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Mohitraut07** [comment]
can i try ?

**Comment by singodiyashubham87** [comment]
@Mohitraut07 I'm already up to resolve this issue, please check for something else and create a new one if you want to work.

**Comment by Dun-sin** [comment]
not accepted request, but thanks for raising, you can check out this discussion instead it's about changing the landing page -> https://github.com/Dun-sin/Whisper/discussions/340
