### ISSUE TITLE
[Other] Add captions/labels to homepage icons

### ISSUE THREAD

**Issue by singodiyashubham87** [Dun-sin/Whisper#436]
### What would you like to share?

I want to add captions/labels to these homepage icons to improve the user experience(UX)

![image](https://github.com/Dun-sin/Whisper/assets/93720428/7e58b1b7-728a-4ada-843b-8e828fb5cf0f)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
that was the orignal design, i do not agree with this change, but thanks for raising
