### ISSUE TITLE
[BUG] Misleading text for "THEME" 

### ISSUE THREAD

**Issue by sohamtembhurne** [Dun-sin/Whisper#446]
### Description

Currently, the text reads dark mode and light mode
I suggest it to be changed to dark theme and light theme

### Screenshots

Existing : -
![image](https://github.com/Dun-sin/Whisper/assets/82658685/af395399-2bd0-413b-840e-c5a8bd34452d)

Proposed Solution: -
![image](https://github.com/Dun-sin/Whisper/assets/82658685/b497f9a6-5b09-44df-98c0-b30a9ec11a6a)

### 🥦 Browser

Microsoft Edge

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Thanks for raising, not an accepted change
