### ISSUE TITLE
[FEATURE] Enhance searching screen

### ISSUE THREAD

**Issue by singodiyashubham87** [Dun-sin/Whisper#448]
### Description

I want to make changes to the UI when searching for random buddies
> Give spacing to the animation circles and text
> Font change

### Screenshots

![image](https://github.com/Dun-sin/Whisper/assets/93720428/c312a6cb-ac33-43ae-a6b5-44db2bf08ad0)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
thanks for raising, not an accepted issue
