### ISSUE TITLE
'Unsaved Settings Warning' pops up for no reason

### ISSUE THREAD

**Issue by varundhand** [Dun-sin/Whisper#450]
### Description

When navigating to the **"Settings" tab**, there is a brief and inconsistent display of the **"Unsaved Settings" warning**. This warning appears for a **split second,** even when there are no unsaved changes. It should **only be displayed when there are actual unsaved changes** in the settings.

### Screenshots

_Current Display:_ 

https://github.com/Dun-sin/Whisper/assets/110025628/a77c024c-8c81-46ea-a9c4-1ce16a220477

_Ideal Display:_

https://github.com/Dun-sin/Whisper/assets/110025628/1347aa37-3b96-4d84-8b22-f3f91d9306f2

### Additional information

Its essential to ensure that the warning displays **only when the user makes appropriate changes**.

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
thanks for raising, will make this a food first issue

**Comment by varundhand** [comment]
I'm willing to work on this, please assign it to me

**Comment by Dun-sin** [comment]
> I'm willing to work on this, please assign it to me

it's a good first issue, means for new comers only

**Comment by codenoid** [comment]
what I supposed to do now? this more like cheating

**Comment by Dun-sin** [comment]
> what I supposed to do now? this more like cheating

I don't know what you are talking about🤔

**Comment by Aryakoste** [comment]
Yes i am willing to submit the PR.

**Comment by myatthiha-ucsy26** [comment]
Hello @Dun-sin , I'm willing to work in this and willing to submit PR. I'm a new comer. Could you please assign it to me ?

**Comment by Dun-sin** [comment]
> Hello @Dun-sin , I'm willing to work in this and willing to submit PR. I'm a new comer. Could you please assign it to me ?

Definitely, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
