### ISSUE TITLE
[OTHER] change web page title

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#454]
### What would you like to share?

The title says `Whisper | Chat Application` change all instances of that in `index.html` to `Whisper | Anonymously Chat and Make a friend`

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by dev-palwar** [comment]
can I work on this?

**Comment by Dun-sin** [comment]
> can I work on this?

No, this is a good first issue

**Comment by Aryakoste** [comment]
I am willing to work on this issue. I am new comer here @Dun-sin

**Comment by Dun-sin** [comment]
> I am willing to work on this issue. I am new comer here @Dun-sin

Ok, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
