### ISSUE TITLE
[BUG] DarkMode sudden switch Bug

### ISSUE THREAD

**Issue by Shariar-Hasan** [Dun-sin/Whisper#461]
### Description

When a user log out, if the app is on LIGHT Mode, it will automatically turn into darkmode.
i attached the sample video in screen shot section

### Screenshots

![ezgif com-video-to-gif](https://github.com/Dun-sin/Whisper/assets/75330767/231c66fe-3577-433c-aea7-e55c450f0571)

### Additional information

if this is an issue to be fixed,
I can fix this, and want to be assigned

### 🥦 Browser

Microsoft Edge

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Ferdinand-Ogama** [comment]
Hello, I'm new to open-source contribution and I can work on this issue. Kindly assign me.

**Comment by GOWTHAM2K1** [comment]
can i work on it??

**Comment by Dun-sin** [comment]
This isn't important😆 because it's saved to the backend and gets the information but when you log out all information about you is deleted from the browser and since the app can't find what you pick, it reverts to the default.

But thanks for raising an issue, this is intentional
