### ISSUE TITLE
[BUG]: shortcut for searching a new partner doesn't work

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#462]
### Description

It doesn't work because it's a browser shortcut too

Change the shortcut to `ctrl + alt + n`, You will find the code here
https://github.com/Dun-sin/Whisper/blob/ab1a0caa53579a1eb931aa319b2f5ecd32987561/client/src/components/Anonymous.jsx#L122

### Are you willing to work on this issue ?

None

**Comment by aman44444** [comment]
@Dun-sin can i work on this issue?

**Comment by Dun-sin** [comment]
> @Dun-sin can i work on this issue?

Sure, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/whisper/Code-Magic/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
