### ISSUE TITLE
[changing ui] -> getting buttons rather than listitems

### ISSUE THREAD

**Issue by Shivam36998** [Dun-sin/Whisper#468]
### What would you like to share?

in the pic below, we have some frequently clickable options as listitems, i think that will help more if they will be kept as buttons like get another user
![Screenshot (169)](https://github.com/Dun-sin/Whisper/assets/100841132/83b079b9-3516-48c4-9dae-98d168936365)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Shivam36998** [comment]
@Dun-sin can you please assign me this

**Comment by Dun-sin** [comment]
Disagree, thanks for raising tho
