### ISSUE TITLE
[BUG] logout Cancel button is invisible

### ISSUE THREAD

**Issue by Shariar-Hasan** [Dun-sin/Whisper#469]
### Description

 The dialog box's cancel button is not visible in light mode.
 
 

### Screenshots

showing in darkmode
![image](https://github.com/Dun-sin/Whisper/assets/75330767/6b16d670-478a-4a0c-8176-37d4d69c4d91)

not showing in lightmode
![image](https://github.com/Dun-sin/Whisper/assets/75330767/6e7f173f-3c13-4362-b26b-24b6469a9de6)

### 🥦 Browser

Microsoft Edge

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Wassaf001** [comment]
please assign it to me.

**Comment by Shariar-Hasan** [comment]
hello Mr. @Dun-sin 
can you assign me this issue, or else should i start working on it?

**Comment by Dun-sin** [comment]
> hello Mr. @Dun-sin 
> can you assign me this issue, or else should i start working on it?
> 

That's rude I'm not a Mr, before you give someone a gender search first it's annoying or use gender neutral wordings

**Comment by Shariar-Hasan** [comment]
> > hello Mr. @Dun-sin
> > can you assign me this issue, or else should i start working on it?
> 
> That's rude I'm not a Mr, before you give someone a gender search first it's annoying or use gender neutral wordings

sorry 😣
i am not good at English. 
can i call only @Dun-sin ?

**Comment by Dun-sin** [comment]
> please assign it to me.

Sure, thanks for wanting to contribute, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
