### ISSUE TITLE
[FEATURE] Add Logout button

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#47]
### Description

Currently after logging, there's no way to logout from the app beside manually changing `localStorage.isLogged = false`.
This is would be a follow up on #36 and #14 
With this, I think the we'd have a complete auth system for the app

**Comment by mathiasayivor** [comment]
@Dun-sin what are your thoughts on this?

**Comment by Dun-sin** [comment]
> @Dun-sin what are your thoughts on this?

I'm going to leave it for now, until I at least work on the chat part of the itself

**Comment by mathiasayivor** [comment]
noted

**Comment by jasham** [comment]
Hello @mathiasayivor is someone working on this feature. I have worked on this tech stack it will be easy for me to implement and learn more, can you please guide me further on this so that I can start.

**Comment by mathiasayivor** [comment]
> > @Dun-sin what are your thoughts on this?
> 
> I'm going to leave it for now, until I at least work on the chat part of the itself

@Dun-sin suggested we wait till at least some parts of the app is working.

**Comment by jasham** [comment]
Thanks @mathiasayivor.

**Comment by dhfherna** [comment]
Hi guys!! @mathiasayivor, @Dun-sin  Anyone is working on this feature?, I can work on it.
