### ISSUE TITLE
Implement Rate Limiting for Messages.

### ISSUE THREAD

**Issue by Tholkappiar** [Dun-sin/Whisper#470]
### Description

Without rate limiting, users can flood the chat with messages, potentially leading to performance issues and misuse. Rate limiting will ensure that users can send messages at a reasonable pace and prevent abuse.

### Screenshots

![anon_chat](https://github.com/Dun-sin/Whisper/assets/114584730/37c60980-f67e-4aa4-9458-c9d90d7c3a51)

### Additional information

I propose implementing rate limiting for message sending. A rate limit of, for example, 70 messages per minute per user, can be a good starting point .

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
How about 25, 70 is too much for each person.
Will assign it to you, Make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by Tholkappiar** [comment]
okay noted 👍 Thank you !

**Comment by Tholkappiar** [comment]
**Hello Maintainers ,** 
On this issue , connected the DB without any errors , but when i opened 2 browsers with the URL, the 2 browsers are not connecting with each other !

**Any idea on this ?**

**Here are the Screen Shots ;**

![whispher](https://github.com/Dun-sin/Whisper/assets/114584730/2c6d3762-e3ff-4268-af6f-43e7b8626cb5)


![Screenshot (93)](https://github.com/Dun-sin/Whisper/assets/114584730/f82b9e6a-ca5a-413d-97b2-b75d3150e95d)

**Comment by Dun-sin** [comment]
> **Hello Maintainers ,** 
> On this issue , connected the DB without any errors , but when i opened 2 browsers with the URL, the 2 browsers are not connecting with each other !
> 
> **Any idea on this ?**
> 
> **Here are the Screen Shots ;**
> 
> ![whispher](https://github.com/Dun-sin/Whisper/assets/114584730/2c6d3762-e3ff-4268-af6f-43e7b8626cb5)
> 
> 
> ![Screenshot (93)](https://github.com/Dun-sin/Whisper/assets/114584730/f82b9e6a-ca5a-413d-97b2-b75d3150e95d)
> 
> 
> 

Fill up the env for both backend and frontend

**Comment by Dun-sin** [comment]
> My Bad 😅 , thanks working , but how did you find that out very quickly without even seeing the code ?

Common mistake lately
