### ISSUE TITLE
[FEATURE] Add a colour change upon hover for the Start button.

### ISSUE THREAD

**Issue by kapooraryan** [Dun-sin/Whisper#472]
### Description

Using Tailwind CSS classes and inline styles, we can add a colour change upon hovering to the Start button for better styling.

### Screenshots

Currently:
![Start_Button](https://github.com/Dun-sin/Whisper/assets/69362333/6b685efa-100b-4cc9-83da-076e267349eb)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by rahul152-ai** [comment]
Hello, @Dun-sin Can you assign me this issue to me I would Like to work on this issue.

**Comment by Dun-sin** [comment]
@kapooraryan can you show me what colour you want to use on hover in the context

**Comment by kapooraryan** [comment]
> @kapooraryan can you show me what colour you want to use on hover in the context

Hey, @Dun-sin I have two possible colours to appear on hover.

Colour 1 (#F59E0B):
![Start_Hover](https://github.com/Dun-sin/Whisper/assets/69362333/061c2e93-6df6-4520-8b51-c12c53a43bdb)

https://github.com/Dun-sin/Whisper/assets/69362333/ca8029e3-5191-4ae4-ae2b-94735841058d

Colour 2 (#FBBF24):
![Start_Hover_2](https://github.com/Dun-sin/Whisper/assets/69362333/e9506452-d951-42e2-81c9-7bdf7f6b50f8)

https://github.com/Dun-sin/Whisper/assets/69362333/b74a3bfa-9f75-4aa7-b7af-d45c42b1e7e3

**Comment by Dun-sin** [comment]
> > @kapooraryan can you show me what colour you want to use on hover in the context
> 
> Hey, @Dun-sin I have two possible colours to appear on hover.
> 
> Colour 1 (#F59E0B): ![Start_Hover](https://user-images.githubusercontent.com/69362333/276500428-061c2e93-6df6-4520-8b51-c12c53a43bdb.png)
> Start_Hover.mp4
> 
> Colour 2 (#FBBF24): ![Start_Hover_2](https://user-images.githubusercontent.com/69362333/276500568-e9506452-d951-42e2-81c9-7bdf7f6b50f8.png)
> Start_Hover_2.mp4

second is better, you are assigned, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck
