### ISSUE TITLE
[FEATURE] add block option drop down

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#474]
### Description

add this code
```javascript
<Dropdown.Item
    onClick={() => console.log('blocking')}>
      Block
</Dropdown.Item>
``` 

after the quote reply
https://github.com/Dun-sin/Whisper/blob/6fdc60f6eab5430b1d86df943ecad3626e1d94b2/client/src/components/Chat.jsx#L558-L586

### Are you willing to work on this issue ?

None

**Comment by Anushka-Bhowmick** [comment]
Can i work on this issue?

**Comment by Dun-sin** [comment]
> Can i work on this issue?

Definitely, thanks for wanting to contribute, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck

**Comment by Anushka-Bhowmick** [comment]
PR submitted: https://github.com/Dun-sin/Whisper/pull/477

**Comment by Dun-sin** [comment]
> PR submitted: #477

keep in mind in the future you don't need to comment back on the Issue, it's not my first rodeo, so I see your PR and will definitely do the necessary. It will just cause unnecessary notifications for me and others.
