### ISSUE TITLE
[FEATURE] send a reminder notification for in activity

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#475]
### Description

Send a browser notification If a user hasn't responded after 3 minutes, we send a reminder notification like “don't leave your partner hanging, drop a response”

use this time in milliseconds: 
https://github.com/Dun-sin/Whisper/blob/10ddc38f6e203d1ef7502ee307758f7a50e9782b/client/src/components/Chat.jsx#L40

use this function to send the browser function:
https://github.com/Dun-sin/Whisper/blob/10ddc38f6e203d1ef7502ee307758f7a50e9782b/client/src/lib/browserNotification.js#L9-L22

### Are you willing to work on this issue ?

None

**Comment by MSaiKiran9** [comment]
I'm new to repository . This project looks amazing can i contribute to this issue ?

**Comment by Dun-sin** [comment]
> I'm new to repository . This project looks amazing can i contribute to this issue ?

Definitely, thanks for wanting to contribute, read the issue description properly and understand what it tells you to do also feel free to ask questions, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.

**Comment by MSaiKiran9** [comment]
Hi @Dun-sin I tried writing a helper funciton then calling it in useEffect as a callback in setTimeout already defined , but as I can see there is some problem with previously defined helper function / createBrowserNotification . I tried logging like this ---->
        export const checkPartnerResponse = (lastMessageTime, inactiveTimeThreshold) => {
	const currentTime = new Date().getTime();
	const isInactive = lastMessageTime && currentTime - lastMessageTime > inactiveTimeThreshold;
	console.log(isInactive);
	if (isInactive) {
		createBrowserNotification("your partner isn't responding, want to leave?");
	}
};
 it's showing true but it's giving this log error when the callback is being executed :
    Uncaught TypeError: str is undefined
    prepare index.js:234
    check index.js:260
    memoized index.ts:102
    filter index.js:275
    createBrowserNotification browserNotification.js:23
    checkPartnerResponse chatHelper.js:66
    inactiveTimeOut Chat.jsx:312
    setTimeout handler*Chat/< Chat.jsx:310
    React 8
    workLoop scheduler.development.js:266
    flushWork scheduler.development.js:239
    performWorkUntilDeadline scheduler.development.js:533
    js scheduler.development.js:571
    js scheduler.development.js:633
    __require chunk-ROME4SDB.js:11
    js index.js:6
    __require chunk-ROME4SDB.js:11
    React 2
    __require chunk-ROME4SDB.js:11
    js React
    __require chunk-ROME4SDB.js:11
    js React
    __require chunk-ROME4SDB.js:11
    <anonymous> react-dom_client.js:38
index.js:234:8


PS : I read the readme and used chrome and mozilla to simulate two users as anonymous logins . Please correct me if I got anything wrong .

**Comment by Dun-sin** [comment]
> Hi @Dun-sin I tried writing a helper funciton then calling it in useEffect as one of the callbacks in setTimeout that's already defined , but as I can see there is some problem with previously defined helper function > createBrowserNotification . I tried logging like this ----> export const checkPartnerResponse = (lastMessageTime, inactiveTimeThreshold) => { const currentTime = new Date().getTime(); const isInactive = lastMessageTime && currentTime - lastMessageTime > inactiveTimeThreshold; console.log(isInactive); if (isInactive) { createBrowserNotification("your partner isn't responding, want to leave?"); } }; it's showing true but it's giving this log error when the callback is being executed : Uncaught TypeError: str is undefined prepare index.js:234 check index.js:260 memoized index.ts:102 filter index.js:275 createBrowserNotification browserNotification.js:23 checkPartnerResponse chatHelper.js:66 inactiveTimeOut Chat.jsx:312 setTimeout handler*Chat/< Chat.jsx:310 React 8 workLoop scheduler.development.js:266 flushWork scheduler.development.js:239 performWorkUntilDeadline scheduler.development.js:533 js scheduler.development.js:571 js scheduler.development.js:633 __require chunk-ROME4SDB.js:11 js index.js:6 __require chunk-ROME4SDB.js:11 React 2 __require chunk-ROME4SDB.js:11 js React __require chunk-ROME4SDB.js:11 js React __require chunk-ROME4SDB.js:11 react-dom_client.js:38 index.js:234:8
> 
> PS : I read the readme and used chrome and mozilla to simulate two users as anonymous logins . Please correct me if I got anything wrong .

this is hard to read, give me a better way to read this

**Comment by MSaiKiran9** [comment]
I want to write a helper function like the one that's  already used in the useEffect's callback portion i.e., checkPartnerResponse . But when I wrote some console.logs and saw that while checkPartnerResponse is executed after the timeout it's giving some errors in the logs . It's giving error when it's hitting the createBrowserNotification part & that portion isn't executing to create a Notification . It's giving multiple logs but the main one was  this one I guess :




Uncaught TypeError: str is undefined
prepare index.js:234
check index.js:260
memoized index.ts:102
filter index.js:275
-------->  createBrowserNotification browserNotification.js:23 (*)


I tried handling errors in createBrowserNotification but it's not giving the notification popups

**Comment by Dun-sin** [comment]
> I want to write a helper function like the one that's already used in the useEffect's callback portion i.e., checkPartnerResponse . But when I wrote some console.logs and saw that while checkPartnerResponse is executed after the timeout it's giving some errors in the logs . It's giving error when it's hitting the createBrowserNotification part & that portion isn't executing to create a Notification . It's giving multiple logs but the main one was this one I guess :
> 
> Uncaught TypeError: str is undefined prepare index.js:234 check index.js:260 memoized index.ts:102 filter index.js:275 --------> createBrowserNotification browserNotification.js:23 (*)
> 
> I tried handling errors in createBrowserNotification but it's not giving the notification popups

i'm very horrible at reading so let's move this to the discord server, delete everything in your local machine, follow the readme and make your change and screen record everything

**Comment by MSaiKiran9** [comment]
Sorry @Dun-sin  I'm really short of time for this for now . Please unassign me , btw the app looks really good though :)

**Comment by devXprite** [comment]
I want to work on this issue

**Comment by avibiradar100** [comment]
Hey @Dun-sin could you please assign me to this issue

**Comment by Dun-sin** [comment]
> Hey @Dun-sin could you please assign me to this issue

Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by avibiradar100** [comment]
Sorry @Dun-sin I'm really short of time for this for now. please unassigned it . thanks
