### ISSUE TITLE
[FEATURE] send a notification when a user leaves a chat

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#476]
### Description

Send a browser notification when one of the user leaves the chat, there's already a pop-up when that happens, but if a user isn't on that page then the user can miss it. 
https://github.com/Dun-sin/Whisper/blob/4b12bf53561e7c2e5f8188c40c1a7d10eba11978/client/src/components/BuddyMatcher.jsx#L91-L106

### Additional Information
there's already a function for notification, just call it at the right position

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
> Can I be assigned this issue @Dun-sin and have a go at it?

Definitely, thanks for wanting to contribute, read the issue description properly and understand what it tells you to do also feel free to ask questions, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.

**Comment by kapooraryan** [comment]
@Dun-sin This feature can be added using the notifications API right? Adding a [reference link](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API) along.

**Comment by Dun-sin** [comment]
> @Dun-sin This feature can be added using the notifications API right? Adding a [reference link](https://developer.mozilla.org/en-US/docs/Web/API/Notifications_API/Using_the_Notifications_API) along.

yes but it's not important, there's already a function to do that
https://github.com/Dun-sin/Whisper/blob/main/client/src/lib/browserNotification.js
just call it in the right place
