### ISSUE TITLE
[Improving UI of Search random buddies page] <Some UI Improvemt To Front Page>

### ISSUE THREAD

**Issue by Ayusht777** [Dun-sin/Whisper#481]
### Description

Hey I wan to Improve the Search Section where their is some UI fixes for start button icons etc  

### Screenshots

![image](https://github.com/Dun-sin/Whisper/assets/106388215/d332d640-46ea-41e6-ba73-1b8a7ddc6fb7)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Ayusht777** [comment]
the first section which loads up have inconsistency in the icon and button  size are to off and gap between text is also uneven

**Comment by Dun-sin** [comment]
> the first section which loads up have inconsistency in the icon and button size are to off and gap between text is also uneven

good, i don't think it's important, thanks for raising
