### ISSUE TITLE
[BUG]: clicking on edit doesn't copy message

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#484]
### Description

Technically it doesn't need to copy the message, but when the edit button is clicked while chatting the message to be edited should be the value for the input box

### 🥦 Browser

Mozilla Firefox

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by sohamtembhurne** [comment]
Hi @Dun-sin , 
I can work on this issue. Please assign it to me.

**Comment by priyavratamohan** [comment]
Hi @Dun-sin, can you assign this issue to me?

**Comment by Dun-sin** [comment]
> Hi @Dun-sin, can you assign this issue to me?

Read the rules of this project else you will be blocked

**Comment by Dun-sin** [comment]
> hello @Dun-sin can I work on this issue?
> 

Definitely, thanks for wanting to contribute, read the issue description properly and understand what it tells you to do also feel free to ask questions, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.

**Comment by Yashh221** [comment]
hey @Dun-sin while logging anonymously how to get the issue locally ?

**Comment by Dun-sin** [comment]
> hey @Dun-sin while logging in anonymously how to get the issue locally ?
Chat with yourself, follow the Readme way of setting up the project.

**Comment by Dun-sin** [comment]
@Yashh221 according to the contributing guideline, your time is up and if there's a PR by the end of the day, you will be unassigned

**Comment by hubsMIT1** [comment]
Hi @Dun-sin,
I would like to work on it, can you assign me?

**Comment by deveshtanwar-IMG** [comment]
Hello @Dun-sin,
I hope you are doing fine,
I have read all the contribution rules properly, can you please assign me this issue.

**Comment by Dun-sin** [comment]
> Hello @Dun-sin, i am not able to connect to myself in localhost. chat box not opening, how to monitor changes ? in localhost.

join the discord server(link in readme), go to #coding-talk, read the previous chat on this question

**Comment by adesh1998** [comment]
could you assign this issue to me?

**Comment by Dun-sin** [comment]
> could you assign this issue to me?

Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions on the discord server. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by adesh1998** [comment]
Hey @Dun-sin , I can see this repo is working fine in live environment but for me in local i am getting bunch of errors.
<img width="1046" alt="Screenshot 2023-11-20 at 11 50 01 PM" src="https://github.com/Dun-sin/Whisper/assets/50673082/6a0399d5-c87d-4a82-bd2a-bbd53a570d49">

**Comment by Dun-sin** [comment]
> Hey @Dun-sin , I can see this repo is working fine in live environment but for me in local i am getting bunch of errors. <img alt="Screenshot 2023-11-20 at 11 50 01 PM" width="1046" src="https://user-images.githubusercontent.com/50673082/284465738-6a0399d5-c87d-4a82-bd2a-bbd53a570d49.png">

hey, hold up on this for a while

**Comment by adesh1998** [comment]
@Dun-sin Any update on this issue?

**Comment by Dun-sin** [comment]
> @Dun-sin Any update on this issue?

I'm off my computer for the next 19 days. Are you on discord? If you are and aren't on the discord server, give it a join and tag me, will let you know then when you can work on this feature, will lock this so I know it's yours when it's time
