### ISSUE TITLE
[FEATURE] Add Custom 404 page

### ISSUE THREAD

**Issue by devXprite** [Dun-sin/Whisper#486]
### Description

When we try to access a non-existent page or resource, instead of displaying a custom 404 page, a blank page is shown.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Virtual4087** [comment]
Hi I would love to work on this

**Comment by Dun-sin** [comment]
what do you want to do with the page

**Comment by Shashankpantiitbhilai** [comment]
I am interested,please assign this to me

**Comment by devXprite** [comment]
> what do you want to do with the page

## Current:
![w_b](https://github.com/Dun-sin/Whisper/assets/80192140/4acc4a82-596b-4256-954d-3c27a79fac49)

## After adding custom 404 page:
![w_a](https://github.com/Dun-sin/Whisper/assets/80192140/9dd8f293-7eed-4330-ba02-aeb152f4dab8)

**Comment by tanpreetjolly** [comment]
I am willing to work on this issue, can you assign it to me

**Comment by Dun-sin** [comment]
> > what do you want to do with the page
> 
> ## Current:
> 
> ![w_b](https://user-images.githubusercontent.com/80192140/276854238-4acc4a82-596b-4256-954d-3c27a79fac49.png)
> ## After adding custom 404 page:
> 
> ![w_a](https://user-images.githubusercontent.com/80192140/276854484-9dd8f293-7eed-4330-ba02-aeb152f4dab8.png)

good, you've got it. Thanks for wanting to contribute, read the issue description properly and understand what it tells you to do also feel free to ask questions, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.

**Comment by tanpreetjolly** [comment]
Shouldn't the navbar not exist on 404 page
