### ISSUE TITLE
[OTHER] delete gitigore file in client husky

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#488]
### What would you like to share?

https://github.com/Dun-sin/Whisper/blob/main/client/.husky/.gitignore

### Are you willing to work on this issue ?

None

**Comment by Harsh-00** [comment]
Hello, I'm interested in working on this issue. Could you please assign it to me?

**Comment by Dun-sin** [comment]
> Hello, I'm interested in working on this issue. Could you please assign it to me?

Definitely, thanks for wanting to contribute, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.
