### ISSUE TITLE
[OTHER] delete gitigore file in server husky

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#489]
### What would you like to share?

https://github.com/Dun-sin/Whisper/blob/main/server/.husky/.gitignore

### Are you willing to work on this issue ?

None

**Comment by sohamtembhurne** [comment]
I am willing to work on this issue. Please assign it to me.

**Comment by Dun-sin** [comment]
> I am willing to work on this issue. Please assign it to me.

Definitely, thanks for wanting to contribute, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.

**Comment by ParthMakode** [comment]
I can solve this issue immediately .If it's okay with @sohamtembhurne , could @Dun-sin assign it to me?

**Comment by sohamtembhurne** [comment]
I have no issues. @Dun-sin, please unassign me and assign this to @ParthMakode

**Comment by sohamtembhurne** [comment]
Then let me resolve this issue. Thanks for the quick response

**Comment by Dun-sin** [comment]
> Then let me resolve this issue. Thanks for the quick response 

You already gave it up lol

**Comment by sohamtembhurne** [comment]
> > Then let me resolve this issue. Thanks for the quick response
> 
> You already gave it up lol

I was only giving someone else a chance. Didn't knew he had worked on another issue. Anyway, it's upto you

**Comment by Himanshu1801** [comment]
Hi, can I work on this issue?

**Comment by Dun-sin** [comment]
> Hi @Dun-sin , can I work on this issue?

Definitely, thanks for wanting to contribute, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.

**Comment by Dun-sin** [comment]
> > > Then let me resolve this issue. Thanks for the quick response
> > 
> > You already gave it up lol
> 
> I was only giving someone else a chance. Didn't knew he had worked on another issue. Anyway, it's upto you 

@sohamtembhurne that's good of you but yeah you gave someone else a chance, if I assign it to you again and someone asks again and you give them, would just be a never ending circle😆

If you truly don't want to work on anything don't ask for it or if you want to but also want to give someone a chance, try a collaboration instead.

In this case giving it up or a collaboration doesn't make sense😆 but hey up to you
