### ISSUE TITLE
[OTHER] delete the client.husky file

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#490]
### What would you like to share?

https://github.com/Dun-sin/Whisper/tree/main/client.husky

### Are you willing to work on this issue ?

None

**Comment by Shashankpantiitbhilai** [comment]
I am interested ,please assign this to me

**Comment by Dun-sin** [comment]
> I am interested ,please assign this to me

Definitely, thanks for wanting to contribute, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.

**Comment by Dun-sin** [comment]
@Shashankpantiitbhilai according to the contributing guideline, your time is up and if there's a PR by the end of the day, you will be unassigned

**Comment by TheTanay902** [comment]
@Dun-sin May I be assigned to this issue if it's up for grabs? Thanks!

**Comment by Dun-sin** [comment]
> @Dun-sin May I be assigned to this issue if it's up for grabs? Thanks!

Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
