### ISSUE TITLE
[OTHER] delete estlintcache in client

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#491]
### What would you like to share?

https://github.com/Dun-sin/Whisper/blob/main/client/.eslintcache

### Are you willing to work on this issue ?

None

**Comment by ParthMakode** [comment]
I just have to delete the file?
Please assign me this task

**Comment by Dun-sin** [comment]
> I just have to delete the file? Please assign me this task

Definitely, thanks for wanting to contribute, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.
