### ISSUE TITLE
[Bug] Remove Link Highlighting from 'readme.md`

### ISSUE THREAD

**Issue by devXprite** [Dun-sin/Whisper#499]
### Description

`SocketIo` box text is highlighted which looks odd.

### Screenshots

![sc_w](https://github.com/Dun-sin/Whisper/assets/80192140/296e4142-8962-43ff-ac7b-fa7ce0ef6f27)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Mohitraut07** [comment]
cna you assign me

**Comment by Dun-sin** [comment]
thanks for raising ,will close this and open a new one with the proper instructions and make it a good first issue
