### ISSUE TITLE
[DOCS] remove highlighting from text

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#500]
### Description

add a `</a>` closing tag after the img
```
<a href="https://socket.io/" target="_blank" rel="noreferrer"><img src="https://w7.pngwing.com/pngs/162/702/png-transparent-socket-io-node-js-express-js-npm-network-socket-github-angle-triangle-logo-thumbnail.png" width="36" height="36" alt="SocketIo">
```

### Screenshots

![sc_w](https://github.com/Dun-sin/Whisper/assets/80192140/296e4142-8962-43ff-ac7b-fa7ce0ef6f27)

### Are you willing to work on this issue ?

None

**Comment by devXprite** [comment]
I want to work on this issue

**Comment by priyavratamohan** [comment]
Hi @Dun-sin, could you assign this issue to me, as I'm a new contributor, would help me in kickstarting my Open Source Journey

**Comment by Dun-sin** [comment]
> Hi @Dun-sin, could you assign this issue to me, as I'm a new contributor, would help me in kickstarting my Open Source Journey

Definitely, thanks for wanting to contribute,  make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.
