### ISSUE TITLE
[FEATURE] Refactor the nav bar by grouping 

### ISSUE THREAD

**Issue by 0xNunana** [Dun-sin/Whisper#506]
### Description

I propose that settings and logout should be separated from the day to day usable components on the nav bar. Moving them downwards will increase user experience by preventing the user from logging out easily

### Screenshots

![Screenshot from 2023-10-20 20-02-08](https://github.com/Dun-sin/Whisper/assets/94549530/7863e8c0-e8a3-42f1-9ba8-58cb537c1588)

### Additional information

Adding a logo will programme the users to remember what app they're using with ease. It can serve as the home button if necessary

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Good idea, will assign it to you but don't change the background color for anything.

Most importantly make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.
