### ISSUE TITLE
[FEATURE] Enhance Styling and Visual Appeal of Settings Form

### ISSUE THREAD

**Issue by varundhand** [Dun-sin/Whisper#507]
### Description

The current design of the settings form could benefit from some improvements to make it more **visually appealing** and **user-friendly.** 

### Screenshots

_This is the just the design, I would implement appropriate font colors and font weights to improve readability and aesthetics._

![Screenshot 2023-10-21 at 1 41 20 AM](https://github.com/Dun-sin/Whisper/assets/110025628/42499b23-f05a-4d69-bc1c-f572edccf2c7)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Not accepted, but thanks for raising
