### ISSUE TITLE
[FEATURE] <what do you have to add>

### ISSUE THREAD

**Issue by rahul152-ai** [Dun-sin/Whisper#513]
### Description

**### Add background color on hover to the 'Login Anonymously' button on the Login page.
The background color on the hover should be #2c2a2aac. 
The background color on hover for the 'Login' button should be rgb(250,188,107)**

### Screenshots

![Screenshot 2023-10-21 153442](https://github.com/Dun-sin/Whisper/assets/77874363/afd7a64f-c06f-411d-a906-514255a0c75c)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
thanks for raising, not an accepted issue
