### ISSUE TITLE
[BUG]: navbar should have a height on mobile

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#514]
### Description

add `min-h-[55px]` here:
https://github.com/Dun-sin/Whisper/blob/3cfeb16a52ecc20b6d3a6b1d1513cee83a0ac03a/client/src/components/NavBar.jsx#L70-L89
add `h-full` here:
https://github.com/Dun-sin/Whisper/blob/3cfeb16a52ecc20b6d3a6b1d1513cee83a0ac03a/client/src/components/NavBar.jsx#L19

### Are you willing to work on this issue ?

None

**Comment by sloth30799** [comment]
Can I do this one?

**Comment by Dun-sin** [comment]
> Can I do this one?

Definitely, thanks for wanting to contribute, read the issue description properly and understand what it tells you to do also feel free to ask questions, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.
