### ISSUE TITLE
[OTHER] add bug issue template title

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#515]
### What would you like to share?

add `title: "[BUG] <what is the issue>"` between `labels` and `description`
https://github.com/Dun-sin/Whisper/blob/3cfeb16a52ecc20b6d3a6b1d1513cee83a0ac03a/.github/ISSUE_TEMPLATE/bug.yml?plain=1#L2-L3

### Are you willing to work on this issue ?

None

**Comment by priyavratamohan** [comment]
Hi @Dun-sin, can you assign this issue to me?

**Comment by Dun-sin** [comment]
> Hi @Dun-sin, can you assign this issue to me?

this is a good first issue

**Comment by KshitizRana** [comment]
May I work on this issue Please assign this to me.

**Comment by Dun-sin** [comment]
> May I work on this issue Please assign this to me.

okay, thanks for wanting to contribute, read the issue description properly and understand what it tells you to do also feel free to ask questions, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.
