### ISSUE TITLE
[FEATURE] Enable searching for emojis in emoji picker

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#517]
### Description

The current emoji picker does not have the option to search for emojis and considering the fact that there are lots of emojis, this gives a bad UX when trying to look up a particular emoji to send.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by devXprite** [comment]
I want to work on this issue

**Comment by Dun-sin** [comment]
> I want to work on this issue

Ok, thanks for wanting to contribute, read the issue description properly and understand what it tells you to do also feel free to ask questions, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.
