### ISSUE TITLE
[FEATURE] shortcut key shouldn't be on mobile

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#520]
### Description
Tasks:
- [ ] don't display the shortcut on mobile

### Screenshots

![Screenshot from 2023-10-21 11-31-49](https://github.com/Dun-sin/Whisper/assets/74247733/49ae5815-bfc5-4e06-a146-0c488a267ebc)

### Are you willing to work on this issue ?

None

**Comment by RANJEETJ06** [comment]
plz assign it to me

**Comment by Dun-sin** [comment]
> plz assign it to me

ok, thanks for wanting to contribute, read the issue description properly and understand what it tells you to do also feel free to ask questions, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.

**Comment by RANJEETJ06** [comment]
> > plz assign it to me
> 
> ok, thanks for wanting to contribute, read the issue description properly and understand what it tells you to do also feel free to ask questions, make sure you follow the rules [👉🏽here👈🏽](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), else your PR will not be accepted and will be closed. Good Luck.

thank q

**Comment by Thanush19** [comment]
can i work on this .. @mathiasayivor

**Comment by mathiasayivor** [comment]
> can i work on this .. @mathiasayivor 

Sorry, this issue is already assigned. Try looking for other issues without the `assigned` label

**Comment by RANJEETJ06** [comment]
@mathiasayivor ok i made the PR what is wrong with checks i can't understand plz look into it 
what checks it fails!
