### ISSUE TITLE
[FEATURE] block bad words from showing in notification

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#527]
### Description

Implement this here:
https://github.com/Dun-sin/Whisper/blob/1bfcf78574feeb2811d1882ace6af7a42950026f/client/src/lib/browserNotification.js#L9-L22

tasks to do:
- [ ] use this library, it's already installed → https://www.npmjs.com/package/bad-words-next
- [ ] use `const message = badwords.filter(body)` then assign message to the notification API replacing body

### Are you willing to work on this issue ?

None

**Comment by devXprite** [comment]
Can i work on this issue?

**Comment by Dun-sin** [comment]
> Can i work on this issue?

Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
