### ISSUE TITLE
[BUG] Scrollbar effect

### ISSUE THREAD

**Issue by RANJEETJ06** [Dun-sin/Whisper#536]
### Description

in chat the scrollbar behaviour is weird looking

### Screenshots

![Screenshot (56)](https://github.com/Dun-sin/Whisper/assets/121615244/4604ac18-9e68-44ef-a7b1-45c28a00c567)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Aryakoste** [comment]
Hello @Dun-sin. I can work on this issue. But just want to ask if we should just remove scrollbar display  by keeping scrolling on overflow or show scrollbar only when the content overflows the container.

**Comment by Dun-sin** [comment]
> Hello @Dun-sin. I can work on this issue. But just want to ask if we should just remove scrollbar display  by keeping scrolling on overflow or show scrollbar only when the content overflows the container.

Second one is a better choice. You've got it. 

thanks for wanting to contribute. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by Aryakoste** [comment]
![image](https://github.com/Dun-sin/Whisper/assets/91268931/20d248ce-85e4-467c-b3ac-963c21b8d3de)
its showing this error for backend whenever i try to send message from anoynomous user

**Comment by Dun-sin** [comment]
> ![image](https://github.com/Dun-sin/Whisper/assets/91268931/20d248ce-85e4-467c-b3ac-963c21b8d3de)
> its showing this error for backend whenever i try to send message from anoynomous user

How latest is your local code

**Comment by Aryakoste** [comment]
Yesterday I was not getting the error. Now i forked the latest code from your repo and started getting this error.

**Comment by Dun-sin** [comment]
> Yesterday I was not getting the error. Now i forked the latest code from your repo and started getting this error.

I understand, so you need to add `VITE_SECRET_KEY` AND `SECRET_KEY` for the backend and frontend respectively. The value can be anything

**Comment by Aryakoste** [comment]
Yes now working perfectly. I tested changes done by me and they are working. After the messages overflow the container then only the scrollbar appear. So I don't need to push anymore changes. Thank you.
