### ISSUE TITLE
[DOCS] update env sample file for server

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#538]
### Description

add this:
`SECRET_KEY=decryption101`
to the env_sample file here:
https://github.com/Dun-sin/Whisper/blob/main/server/.env_sample

### Are you willing to work on this issue ?

None

**Comment by anevski-stefan** [comment]
@Dun-sin I want to work on this issue, can you assign me?

**Comment by KshitizRana** [comment]
May I work on this issue, Assign it to me ?

**Comment by Zesterdock** [comment]
Hey, please assign this issue to me, i want to work on it

**Comment by Ankitv003** [comment]
can i work on this issue? this would be my pr for hackoberfest!

**Comment by Dun-sin** [comment]
> Hey, please assign this issue to me, i want to work on it

Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by sohamtembhurne** [comment]
Can I work on this issue ?

**Comment by Dun-sin** [comment]
@Zesterdock 
according to the contributing guideline, your time is up and if there's a PR by the end of the day, you will be unassigned.

**Comment by Ankitv003** [comment]
Hey @Dun-sin  can i be assigned after that?

**Comment by Ankitv003** [comment]
can i  work on this @Dun-sin ?

**Comment by Ankitv003** [comment]
and can you please explain , what needs to be done? do we have to add another file named ".env" or do we need make changes to the  "env_sample" by simply adding this ``` SECRET_KEY=decryption101```

**Comment by Dun-sin** [comment]
> can i work on this @Dun-sin ?

and sure, read the contributing files for the guidelines to creating a pr
