### ISSUE TITLE
[DOCS] update env sample for client

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#539]
### Description

add this:
`VITE_SECRET_KEY=decryption101`
to the env_sample file here:
https://github.com/Dun-sin/Whisper/blob/main/client/.env_sample

### Are you willing to work on this issue ?

None

**Comment by anevski-stefan** [comment]
@Dun-sin can i work on this issue?

**Comment by avibiradar100** [comment]
Hey @Dun-sin could you please assign me to this issue

**Comment by Dun-sin** [comment]
> Hey @Dun-sin could you please assign me to this issue

nope, this is a good first issue

**Comment by KshitizRana** [comment]
May I work on this issue please assign this to me ?

**Comment by Aditya7pandey** [comment]
May I work on this issue

**Comment by Dun-sin** [comment]
> May I work on this issue 

Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
