### ISSUE TITLE
[OTHER] Disable click on profile button if user is not logged in

### ISSUE THREAD

**Issue by singodiyashubham87** [Dun-sin/Whisper#544]
### What would you like to share?

I want to make the profile button non-clickable if the user is not logged in.
Currently, it shows "Please create an account" which is not good for user experience.

### Additional information

![image](https://github.com/Dun-sin/Whisper/assets/93720428/73ad5f1a-96bb-4541-baa4-7f4f16b7e333)
![image](https://github.com/Dun-sin/Whisper/assets/93720428/5f83fa32-6340-4bc1-be13-68d6bc24cc2a)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by hamzailyas237** [comment]
I would like to work on this. Assign it to me.

**Comment by Dun-sin** [comment]
It's actually good user experience, thanks for raising not an accepted issue
