### ISSUE TITLE
[FEATURE] add captcha

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#545]
### Description

Adding captcha will help prevent bots, places to add captchas:
— after 2 chats a day, user gets a captcha they have to pass
— if they are a new user, they have to pass a captcha before they can create an account, so on the login page users shouldn't be able to click on any of the buttons until it's passed

### Are you willing to work on this issue ?

None

**Comment by singodiyashubham87** [comment]
I wanna work on this issue @Dun-sin

**Comment by Dun-sin** [comment]
> I want to work on this issue. Please assign this to me. @Dun-sin

can youy explain back to me what the issue is telling you to do?

**Comment by Shubham1450** [comment]
As we know CAPTCHA is used to distinguish between humans and bots. So in this we have to implement CAPTCHA at two place. 
1. If a user chat for 2 times in a day then user gets a captcha which they have to pass.
2.If user wants to create a new account then user have to pass the CAPTCHA before creating new account, and  on the login page users shouldn't be able to click on any of the buttons until it's passed.

**Comment by Dun-sin** [comment]
> As we know CAPTCHA is used to distinguish between humans and bots. So in this we have to implement CAPTCHA at two place.
> 
>     1. If a user chat for 2 times in a day then user gets a captcha which they have to pass.
> 
> 
> 2 .If user wants to create a new account then user have to pass the CAPTCHA before creating new account, and on the login page users shouldn't be able to click on any of the buttons until it's passed. @Dun-sin

awesome spot on, you've got it. thanks for wanting to contribute. ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by Dun-sin** [comment]
@Shubham1450 
according to the contributing guideline, your time is up and if there's a PR by the end of the day, you will be unassigned. You can request for extra time but not more than x days, but we need a response by the end of the day

**Comment by sarthakgarg814** [comment]
Hi @Dun-sin,
Please Assign this to me

**Comment by prajwalbandak** [comment]
hey @Dun-sin , 
Could you please explain this one ,
` _As we know CAPTCHA is used to distinguish between humans and bots. So in this we have to implement CAPTCHA at two place.

1. If a user chat for 2 times in a day then user gets a captcha which they have to pass.`_

how we get to know that, **if user chat for 2 times in a day**   please explain,
will try to give the PR.

**Comment by Dun-sin** [comment]
hi @sarthakgarg814 @prajwalbandak atm this can't be worked on, i will let you know when it's finally open to be worked on will lock the issue until then, @prajwalbandak let's discuss more on the implementation on discord, link in the readme and tag me with your question again in the #coding-talk channel
