### ISSUE TITLE
[BUG] Add redirecting link to logo and cursor pointer on hover

### ISSUE THREAD

**Issue by singodiyashubham87** [Dun-sin/Whisper#547]
### Description

The logo on the website is not currently clickable.
It has to be clickable and also on hover the cursor should change to pointer.

### Screenshots

![image](https://github.com/Dun-sin/Whisper/assets/93720428/e3007729-ac28-430c-990c-3e70dd4d7aed)

### Additional information

Kindly assign me this issue.

### 🥦 Browser

Brave

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Bashamega** [comment]
I would love to work on it

**Comment by Dun-sin** [comment]
Good idea but not accepted, because it's basically taking you to the search screen when you click that which you can also go to with the search button right under. Plus it doesn't show on mobile.
