### ISSUE TITLE
[FEATURE] Enable Users Delete their account

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#552]
### Description

Currently, users are unable to delete their accounts, they can only logout. It's crucial for an anonymous chat app to have the option for users to delete their accounts.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
They can delete their account in the profile section. Obviously anonymous users can't delete their account maybe that's why you didn't notice
