### ISSUE TITLE
[FEATURE] Sidebar doesn't have a light mode theme

### ISSUE THREAD

**Issue by Judge-Paul** [Dun-sin/Whisper#554]
### Description

The sidebar doesn't update when light mode is toggled, I am guessing it's because it doesn't have a light mode theme

### Screenshots

![Screenshot from 2023-10-27 08-46-21](https://github.com/Dun-sin/Whisper/assets/110723341/66549110-70c7-4a3b-b392-242a20c20f71)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
That's intentional, thanks for raising tho
