### ISSUE TITLE
[BUG] Toggle doesn't respect darkMode state

### ISSUE THREAD

**Issue by Judge-Paul** [Dun-sin/Whisper#555]
### Description

After toggling on or off if you press cancel the toggle goes back to its previous state but the darkMode state will still be changed.
Which will make the toggle and dark mode state out of sync

### Screenshots

https://github.com/Dun-sin/Whisper/assets/110723341/ed6a858f-e369-40dc-a90a-4f79db61371e

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Thanks for raising, but will fix it myself Cuz it's a little more than that
