### ISSUE TITLE
[DOCS] Add requirements for adding libraries that require extra configuration

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#561]
### Description

Currently, there are no specific requirements for updating the documentation when new PRs introduce new libraries that require additional setup steps.

Proposed Solution:
We should update the contributing guidelines to mandate that new PRs introducing new libraries with extra setup requirements must also include relevant documentation for setting up the project.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
don't worry about this
