### ISSUE TITLE
[BUG] Login Anonymously Visibility 

### ISSUE THREAD

**Issue by amitabh-sahu** [Dun-sin/Whisper#566]
### Description

In the login page Login Anonymously cta text is not visible (light mode)

### Screenshots

<img width="354" alt="Screenshot 2023-11-02 at 7 50 00 PM" src="https://github.com/Dun-sin/Whisper/assets/90052329/102000c5-5e50-42e0-ada5-9afb7fef31a2">

### Additional information

add the following to the button: `dark:text-white`

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
> Can you please assign this issue to me

Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions on the discord server. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
