### ISSUE TITLE
[FEATURE] remove spinner from the input, at the Profile page

### ISSUE THREAD

**Issue by WungthingKashungnao** [Dun-sin/Whisper#570]
### What would you like to share?

Hello 
I think the input, would look much cleaner without the spinners
![whisper input png](https://github.com/Dun-sin/Whisper/assets/57941260/ccc4bff2-40d8-4e99-a06c-404d99f38ea6)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Thanks for raising, not an accepted issue👍🏽
