### ISSUE TITLE
[BUG] After connection on one screen it shows loading and on other chat comes

### ISSUE THREAD

**Issue by sarthakgarg814** [Dun-sin/Whisper#574]
### Description

Code is messes up at a lot of places on client side. Eslint error messages are ignored.

### Screenshots

<img width="1512" alt="Screenshot 2023-12-09 at 12 07 14 AM" src="https://github.com/Dun-sin/Whisper/assets/52478788/27b06f3e-a0bd-4a4f-b74a-a7e8b7c5ec2a">
<img width="1512" alt="Screenshot 2023-12-09 at 12 10 47 AM" src="https://github.com/Dun-sin/Whisper/assets/52478788/802f296a-bdb5-4ea6-8bbd-d4d464d2abfb">

### Additional information

How to reciprocate?
1. open one tab and login.
2. open private tab and login.
3. click on found user on both and connect.
4. Type something you will find the issue

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by sarthakgarg814** [comment]
Any update ?

**Comment by Dun-sin** [comment]
> Any update ?

I'm currently working on #296, so if after it's done and this problem still persists then you can have it💪🏽

**Comment by sarthakgarg814** [comment]
Okay sure

**Comment by Dun-sin** [comment]
> Okay sure, are you converting it to nextjs ?
> 

Yes I am
