### ISSUE TITLE
[BUG] Room not found

### ISSUE THREAD

**Issue by MJinH** [Dun-sin/Whisper#577]
### Description

![Screenshot (207)](https://github.com/Dun-sin/Whisper/assets/97130553/46240f25-50fe-4fb5-b7e4-c391a1eb6eb6)

When I log in as an anonymous user and try to send a message, I encounter this error. Please let me know if there are any additional settings required. If not, I'd like to work on this issue.

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Hi, I'm currently working on it, but thanks for raising will let you know if I need help tho💪🏽

**Comment by Dun-sin** [comment]
Actually @MJinH you should take it, I need a break from trying to fix it, better you than me anyway

anyway, if you have questions on the discord server. Follow the guidelines [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by MJinH** [comment]
> Actually @MJinH you should take it, I need a break from trying to fix it, better you than me anyway
> 
> anyway, if you have questions on the discord server. Follow the guidelines [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

Got it, I'll make sure to follow the guidelines. Thanks for letting me take it. However, how much time is allocate for this issue?
