### ISSUE TITLE
[BUG] .env_sample file missing

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#578]
### Description

When setting up the project for dev, there's no `.env_sample` file as stated in the docs

### 🥦 Browser

Other

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
Oh shot, I knew I was forgetting something, if anyone wants this, let me know, I would give you what to add to it on discord(link in project Readme) 💪🏽

**Comment by bL34cHig0** [comment]
Hey @Dun-sin, I'd like to work on this issue.

**Comment by Dun-sin** [comment]
> Hey @Dun-sin, I'd like to work on this issue.
> 

Alright, Wil assign you to it, join the server, tag me in coding-talk channel, and I will give you the content of the sample file.

But when making a pull request, make sure to follow the project guidelines💪🏽

**Comment by bL34cHig0** [comment]
th

> > Hey @Dun-sin, I'd like to work on this issue.
> 
> Alright, Wil assign you to it, join the server, tag me in coding-talk channel, and I will give you the content of the sample file.
> 
> But when making a pull request, make sure to follow the project guidelines💪🏽

Thanks, will do right away
