### ISSUE TITLE
[BUG] chat isn't visible

### ISSUE THREAD

**Issue by MJinH** [Dun-sin/Whisper#586]
### Description

When you connect to chat as anonymous and send messages, the other person doesn't receive messages and what you type isn't visible.

### Screenshots

![Screenshot (212)](https://github.com/Dun-sin/Whisper/assets/97130553/6b500dc5-4d81-46a7-8306-b244c30d8dbb)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
go for it @MJinH. Follow the guidelines [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by MJinH** [comment]
> go for it @MJinH. Follow the guidelines [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

Hi @Dun-sin , before creating a PR, can I briefly ask why we are disconnecting the socket here in the 'anonymous.tsx' file?. 

![Screenshot (213)](https://github.com/Dun-sin/Whisper/assets/97130553/02eaac16-d885-41e7-b8d1-7e85ed2ac1cc)

**Comment by Dun-sin** [comment]
> > go for it @MJinH. Follow the guidelines [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
> 
> Hi @Dun-sin , before creating a PR, can I briefly ask why we are disconnecting the socket here in the 'anonymous.tsx' file?.
> 
> ![Screenshot (213)](https://private-user-images.githubusercontent.com/97130553/296254281-02eaac16-d885-41e7-b8d1-7e85ed2ac1cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzExNzQsIm5iZiI6MTcwNTA3MDg3NCwicGF0aCI6Ii85NzEzMDU1My8yOTYyNTQyODEtMDJlYWFjMTYtZDg4NS00MWU3LWI4ZDEtN2U4NWVkMmFjMWNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE0NDc1NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhODk4MTVmM2RmYWRmODExNDEzNzFjOTU1MDJhYmU5YTdjNThkZDY3ODZhNGIwNDU0MjRlNjYzNTMzOWEzOGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HmjyaN6s6Gfk9mthzYSLbZhor_MCA8KTHEBvz_8tLLI)

Notice it's in the return of the useEffect, which is meant for cleaning up useEffects, it's there because it's a cleanup and not the actual code

**Comment by MJinH** [comment]
I noticed that if we don't comment that out, socket.connect will become false, and whenever we send a message, it gets stuck here and returns immediately. Is there any way to keep connect as true without commenting out this part?

![Screenshot (214)](https://github.com/Dun-sin/Whisper/assets/97130553/7d061dd7-9d3d-4d89-92ba-7aa7b036bd18)

**Comment by Dun-sin** [comment]
> I noticed that if we don't comment that out, socket.connect will become false, and whenever we send a message, it gets stuck here and returns immediately. Is there any way to keep connect as true without commenting out this part?
> 
> ![Screenshot (214)](https://private-user-images.githubusercontent.com/97130553/296281585-7d061dd7-9d3d-4d89-92ba-7aa7b036bd18.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNzY4MzAsIm5iZiI6MTcwNTA3NjUzMCwicGF0aCI6Ii85NzEzMDU1My8yOTYyODE1ODUtN2QwNjFkZDctOWQzZC00ZDg5LTkyYmEtN2FhN2IwMzZiZDE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTEyVDE2MjIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMjA3MGU1MDUyNmQ2NDQ5NzllYmVjNzI3YWMzZjA4NzQ4NjE4MWYyNzM1NzYyMGYxYWExYTUwMWI1Nzg4M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.npO9YsSdrDyHuOHczowkP5pJHOSEqb4nVDzLosl10-M)

the whole application runs on socket so we do always need it to be true, in that case removing the socket,disconnect is our safest and best bet
