### ISSUE TITLE
[BUG] Volume slider in settings has a width of 0

### ISSUE THREAD

**Issue by benaissazaki** [Dun-sin/Whisper#589]
### Description

The volume slider has a width of 0 so it's unusable.

### Screenshots

![image](https://github.com/Dun-sin/Whisper/assets/33980130/b3b705ad-d697-4044-8f23-a736c30233b8)

### Additional information

It can be fixed by setting the width of the `div.rs-form-control-wrapper` wrapping the slider to 100%. There isn't an option to pass a class to that div as far as I know, so it will require custom CSS.

### 🥦 Browser

Other

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Go for it, thanks for wanting to contribute. Follow the guidelines [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
