### ISSUE TITLE
[FEATURE] Add docker support

### ISSUE THREAD

**Issue by imvision** [Dun-sin/Whisper#59]
### Description

Docker compose will make it simple to start the projects and mongo db.

**Comment by hasnainmakada-99** [comment]
Hey @imvision I would like to know more about this issue and I'll like to give it a try

**Comment by mathiasayivor** [comment]
Hey @Dun-sin what do you think about this issue?
Using docker just makes things easier

**Comment by Dun-sin** [comment]
I left it for a reason, pretty non-important in my opinion for now anyway

**Comment by mathiasayivor** [comment]
@Dun-sin this only takes a few seconds to implement can we work on this now?

**Comment by Dun-sin** [comment]
> @Dun-sin this only takes a few seconds to implement can we work on this now?

Okay
