### ISSUE TITLE
[FEATURE] Improve on `Chat` component size

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#593]
### Description

The current `Chat` component imports `bad words` data statically here:
https://github.com/Dun-sin/Whisper/blob/b73c6db38c94ebe052d8aaf512379a4a1401f4de/src/components/Chat.tsx#L18-L19C46

This impacts the component's size hence the loading time. It would be better to lazily load this data using dynamic imports for improved results

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by DevDaniloFerrari** [comment]
Hello, I've begun working on addressing this issue, but I haven't completed it yet. Could you please assign this issue to me?

**Comment by Dun-sin** [comment]
> Hello, I've begun working on addressing this issue, but I haven't completed it yet. Could you please assign this issue to me?

Go for it, but when you're making your PR take notes of the guidelines in the [contributing.md](https://github.com/Dun-sin/whisper/blob/main/CONTRIBUTING.md)
