### ISSUE TITLE
[OTHER] User Interface Enhancement for Settings Webpage 

### ISSUE THREAD

**Issue by arshadakl** [Dun-sin/Whisper#594]
### What would you like to share?

The settings webpage needs improvement, with the **main part not aligned from the top** and **different colors than other pages**. This affects user satisfaction. Recommending adjustments to make it consistent and enhance overall look.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Hi @arshadakl I would appreciate a screenshot or image explaining more of your thoughts, please join the discord server and use the contributors channel to explain your thoughts more.

Thanks
