### ISSUE TITLE
[BUG] Dark Mode not working

### ISSUE THREAD

**Issue by ABHID10** [Dun-sin/Whisper#597]
### Description

Dark mode feature not working properly.

### Screenshots

![image](https://github.com/Dun-sin/Whisper/assets/86340981/8b7aa4a9-cb85-490e-a4bf-fddc5a51979c)
![Screenshot 2024-01-21 210122](https://github.com/Dun-sin/Whisper/assets/86340981/83085046-646e-4a26-b357-ff28fb2962bf)

### Additional information

Nope

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Hi @ABHID10, thanks for wanting to contribute, you've got it assigned to you ask if you have questions on the discord server. Follow the guidelines [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by FazeenIjaz** [comment]
Hi, Can i do this task , if not assigned to anyone?

**Comment by Dun-sin** [comment]
@ABHID10 how's this going?

**Comment by ABHID10** [comment]
I have gone through the documentation to understand the codebase. I am doing the task on priority.

**Comment by Dun-sin** [comment]
> I have gone through the documentation to understand the codebase. I am doing the task on priority.

It's a 7 days assigned issue which means the 7 days are up, but will give an extension of 3 days

**Comment by ishn123** [comment]
Hi @Dun-sin I have fixed this issue in the existing code, Can I raise PR for that?

**Comment by Dun-sin** [comment]
> <img width="620" alt="Screenshot 2024-02-04 at 6 52 54 PM" src="https://github.com/Dun-sin/Whisper/assets/62070580/e8842658-3e23-4bcf-b787-188591091ed3">
> 
> Hi @Dun-sin I have fixed this issue in the existing code, Can I raise PR for that?

That doesn't fix the issue

**Comment by ishn123** [comment]
@Dun-sin Could you please add the screenshots for what is the actual bug and what is expected.

**Comment by Dun-sin** [comment]
We already have dark mode implemented, but it's not working on toggle. That's why it's a bug to be fixed not a feature added

#424

**Comment by ishn123** [comment]
I haven't added any new feature, in the existing code only I have added few things, even haven't made any new variables.

**Comment by Karan9927** [comment]
@Dun-sin Just wanted to give you a heads up that I've reviewed the issue and managed to solve it! I've also attached the images for your reference. Do let me know if i can make a pull request.
![image](https://github.com/Dun-sin/Whisper/assets/115612744/f9a8ce75-254d-43f0-a4f7-b9ddbaa002d4)
![image](https://github.com/Dun-sin/Whisper/assets/115612744/dc25cb8a-558d-43e4-b141-3f5edc2fa6b8)

**Comment by Dun-sin** [comment]
> @Dun-sin Just wanted to give you a heads up that I've reviewed the issue and managed to solve it! I've also attached the images for your reference. Do let me know if i can make a pull request.
> ![image](https://github.com/Dun-sin/Whisper/assets/115612744/f9a8ce75-254d-43f0-a4f7-b9ddbaa002d4)
> ![image](https://github.com/Dun-sin/Whisper/assets/115612744/dc25cb8a-558d-43e4-b141-3f5edc2fa6b8)
> 

Still not correct as the background color is missing

**Comment by Dun-sin** [comment]
> You want the white background of the form that is behind to be dark on toggle or the background color of the page to be dark on toggle be specific?
> 

Everything was already set up, the toggle just isn't working, all this issue is saying is, fix the toggle and make it work

**Comment by Karan9927** [comment]
I Made it work like you wanted and shared the screenshot I can make a PR in that you can view the changes and review the code.

**Comment by ishn123** [comment]
@Dun-sin  I have made it work like you are mentioning.

**Comment by Dun-sin** [comment]
@ishn123 @Karan9927 none of you have showed me the right thing, and right now I'm too busy to be going back and forth with this, so will just fix it myself when I have the time.

Thanks for wanting to help, if you want to communicate more on this then join the discord server and we can talk there, as for now will be locking this.

And for the love of God @Karan9927 stop creating unnecessary issues
