### ISSUE TITLE
[BUG] Login Issue: Bad Request Error Encountered

### ISSUE THREAD

**Issue by Arshath01** [Dun-sin/Whisper#600]
### Description

Encountering an issue with the login functionality. Attempting to log in results in a 'Bad Request' error, preventing successful login. Investigating and addressing this issue.

### Screenshots

![whischat vercel app_login and 3 more pages - Personal - Microsoft​ Edge 25-01-2024 19_22_47](https://github.com/Dun-sin/Whisper/assets/112787816/31521167-f5c2-4a79-ae6e-d6076167ad70)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
thanks for raising but there's a reason why, it's intentional, thanks for raising tho
