### ISSUE TITLE
Close button on settings page

### ISSUE THREAD

**Issue by Karan9927** [Dun-sin/Whisper#604]
### Description

Whenever a person click on setting and update the settings there is no way the user can close it and the cancel button is also not working

### Screenshots

![image](https://github.com/Dun-sin/Whisper/assets/115612744/612a5bd1-3a5a-49ec-91ff-8b748bcfe8c0)
![image](https://github.com/Dun-sin/Whisper/assets/115612744/6628281a-8236-46bb-94f9-9075c0db2acc)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Thanks for raising, but it doesn't make sense to close it as it's not modal but a page
