### ISSUE TITLE
Back Button on Setting page 

### ISSUE THREAD

**Issue by Karan9927** [Dun-sin/Whisper#605]
### Description

I think a back button that navigates from setting page to home page will be a great feature to add on !

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Not a good idea either as once again there's a navigation, doesn't make sense to have a back page
