### ISSUE TITLE
New feature

### ISSUE THREAD

**Issue by Karan9927** [Dun-sin/Whisper#606]
### Description

I am sorry for writing this again and again but if you are saying that there is a navigation users can use to navigate from setting to home page. So what's the use of Next.js for creating single page applications if somebody have to rely on there browsers back button.
And this is the last suggestion I wanted to make. Thank you for your time.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Maybe stop writing it again and again and just use the discord server to communicate, you are giving me more unnecessary work.

There's a navigation bar that works you don't see twitter giving you a back button unless you are in a tweet or a dm, unless we create a friends section.

We don't need a back button, let it go dude, you are causing a spam behaviour
