### ISSUE TITLE
[BUG] The settings Update or Cancel Button Is Not Functioning

### ISSUE THREAD

**Issue by prabhanshjn** [Dun-sin/Whisper#608]
### Description

Hi,
I tried using the application and explored the settings page (/settings).
After changing a few settings like Dark Mode, and Sound.

I pressed the Update button, but nothing happened, Cancel button also nothing happened. I felt this was a UX and Functionality issue

Moreover, in the console. I get an API error

### Screenshots

![image](https://github.com/Dun-sin/Whisper/assets/95516177/8dea5b9b-5c39-4769-8029-15c4561bdb33)
![image](https://github.com/Dun-sin/Whisper/assets/95516177/0f1ae265-4095-43bd-aaaa-8015e1befc0b)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
sorry for the late reply, go for it
thanks for wanting to contribute, ask if you have questions on the discord server. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
