### ISSUE TITLE
[BUG] Login button not working 

### ISSUE THREAD

**Issue by Golu7667** [Dun-sin/Whisper#609]
### Description

i am using WHISPER but i can't login.

### Screenshots

![whisperlogin](https://github.com/Dun-sin/Whisper/assets/103061012/e7fdcb78-3ae2-427d-89e8-7ce70ff0f1f7)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
right the login button doesn't work atm, we plan to convert it to use a typical login form

**Comment by Girishg17** [comment]
Hi @Dun-sin Please assign this issue to me . will solve it in a day

**Comment by Golu7667** [comment]
login button working
