### ISSUE TITLE
[BUG] Stop Button for stop searching for users doesn't work

### ISSUE THREAD

**Issue by tokhy1** [Dun-sin/Whisper#612]
### Description

In the website when i click stop searching button, it doesn't work and it is still searching for users.

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
This happens because the server went to sleep and is having a problem reconnecting. Will be hosting the server somewhere else soon, but it's not a bug. Thanks for raising an issue and trying out the product
