### ISSUE TITLE
[OTHER] husky not running precommit

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#613]
### What would you like to share?

whenever i commit a message, husky is meant to run but it's not and shows this warning
```
hint: The 'client/.husky/pre-commit' hook was ignored because it's not set as executable.
```

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by DanonymousCoder** [comment]
Hi, I would like to work on this issue
