### ISSUE TITLE
[BUG] Profile image not update

### ISSUE THREAD

**Issue by Golu7667** [Dun-sin/Whisper#616]
### Description

I want to change my profile photo but not change my profile photo

### Screenshots

![profilewishper](https://github.com/Dun-sin/Whisper/assets/103061012/6cfefbff-9d1d-4f22-bef9-07209bd5f1d1)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Hi @Golu7667 thanks for wanting to contribute, how do you plan on building this feature?

**Comment by aryan127** [comment]
hi @Golu7667  I would like to contribute on this. Can I ??

**Comment by Dun-sin** [comment]
> i want to work on it

The problem we faced was because nsfw library doesn't work fine, if you can find a way for us to upload images and still check if it's a +18 one, then go for it
