### ISSUE TITLE
[BUG] Dark Mode Enable Icon Not Found

### ISSUE THREAD

**Issue by Golu7667** [Dun-sin/Whisper#619]
### Description

When the dark mode button is enabled, the icon does not appear, indicating a bug.

### Additional information

![whischat_icon_not_found](https://github.com/Dun-sin/Whisper/assets/103061012/601f7e2b-6a69-47ba-b45e-2138b67d170d)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
It appears but just in the wrong color. Feel free to fix it

thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions on the discord server. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by Golu7667** [comment]
@Dun-sin For some reason, I was unassigned. Could you please assign me again so I can fix this bug?

**Comment by Dun-sin** [comment]
> @Dun-sin For some reason, I was unassigned. Could you please assign me again so I can fix this bug?

You unassigned yourself🤷

**Comment by Golu7667** [comment]
@Dun-sin yes this is my mistake
