### ISSUE TITLE
[OTHER] Remove the two unnecessary vercel repositories

### ISSUE THREAD

**Issue by Golu7667** [Dun-sin/Whisper#621]
### What would you like to share?

There are four checks, but two Vercel repositories are not working. The main Vercel repository is Vercel – whisper-b2p2. Remove the two non-working repositories from the Vercel account so that only the two working checks remain.
![whispervercel](https://github.com/Dun-sin/Whisper/assets/103061012/dcc9b464-1bfc-4c52-85a9-6ca4ce195617)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
can't remove the first one but removed the second, thanks
