### ISSUE TITLE
[BUG] can't read warning text in light mode

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#622]
### Description

When a user sends a message with an inappropriate word, the receiver gets a warning asking them if they want to view it or not. In light mode the text colors aren't properly set, which makes the user unenabled to read it or see the options.

On dark mode it looks like this:
![image](https://github.com/user-attachments/assets/b307afec-0499-489f-aee4-b7e567c6e794)

### Screenshots

on light mode:
![image](https://github.com/user-attachments/assets/210985ef-0019-4940-bd43-9dc34c5d3d89)

### 🥦 Browser

Brave

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Golu7667** [comment]
Assign me

**Comment by Dun-sin** [comment]
> Assign me

Hi, thanks for wanting to fix this issue, but i would like to leave it up for someone new to the project or open source in general. You can check out the rest of the issues or use the application to see what you can add.

**Comment by TysonThurman** [comment]
Hi, can I please be assigned to work on this?

**Comment by Dun-sin** [comment]
> Hi, can I please be assigned to work on this?

Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions on the discord server. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
