### ISSUE TITLE
[BUG] Login Button not working

### ISSUE THREAD

**Issue by Golu7667** [Dun-sin/Whisper#624]
### Description

Login button not working 

### Screenshots

![whisperlogin1](https://github.com/user-attachments/assets/ee289006-fad5-424a-9a6d-bde5a0c4dd50)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
Fixed, thanks for raising💪🏽
