### ISSUE TITLE
[OTHER] Update or Remove Outdated URL in Repository Fork

### ISSUE THREAD

**Issue by Golu7667** [Dun-sin/Whisper#625]
### What would you like to share?

When I forked this repository, the URL https://whispe.vercel.app/ was shown, but it has many bugs because the URL is not updated to the latest commit. Please update or remove this URL so new users do not face this problem.
![whisperloginurl](https://github.com/user-attachments/assets/0f95934b-bcdc-45c3-b2fb-32686714932e)
![whisperloginurl1](https://github.com/user-attachments/assets/251cf725-4b1f-430f-a922-1188260c3cbe)
![whisperlogin2](https://github.com/user-attachments/assets/d772161e-5dbc-401c-bedb-6fcdc0ef643a)

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by Dun-sin** [comment]
Delete your fork and refork it. The original repo doesn't have that link
