### ISSUE TITLE
[BUG] Copying chat not work

### ISSUE THREAD

**Issue by Golu7667** [Dun-sin/Whisper#628]
### Description

When I copy chat, it is not copying correctly.

### Screenshots

![whispercopy](https://github.com/user-attachments/assets/2c9c5ec2-22e7-4611-9785-f9d7ad2622b0)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions on the discord server. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by TysonThurman** [comment]
I've also noticed that if I refresh the screen a couple of times, it'll change my message to this sort of message. Refreshing again will change it back to its normal text but it shows again after a couple more refreshes. Just wanted to add that extra info. I hope it helps.

<img width="1752" alt="Screenshot 2024-07-18 at 11 45 06 PM" src="https://github.com/user-attachments/assets/79714fe5-2c13-4d97-a832-a9d298b00e12">
<img width="1752" alt="Screenshot 2024-07-18 at 11 40 50 PM" src="https://github.com/user-attachments/assets/fdf57821-70d0-4718-b6e8-d8635b9a5fcf">

**Comment by Dun-sin** [comment]
> I've also noticed that if I refresh the screen a couple of times, it'll change my message to this sort of message. Refreshing again will change it back to its normal text but it shows again after a couple more refreshes. Just wanted to add that extra info. I hope it helps.
> 
> <img width="1752" alt="Screenshot 2024-07-18 at 11 45 06 PM" src="https://github.com/user-attachments/assets/79714fe5-2c13-4d97-a832-a9d298b00e12">
> <img width="1752" alt="Screenshot 2024-07-18 at 11 40 50 PM" src="https://github.com/user-attachments/assets/fdf57821-70d0-4718-b6e8-d8635b9a5fcf">
> 
> 

Thanks for letting me know, please create a new issue highlighting this. Thank you

**Comment by TysonThurman** [comment]
> > I've also noticed that if I refresh the screen a couple of times, it'll change my message to this sort of message. Refreshing again will change it back to its normal text but it shows again after a couple more refreshes. Just wanted to add that extra info. I hope it helps.
> > <img alt="Screenshot 2024-07-18 at 11 45 06 PM" width="1752" src="https://private-user-images.githubusercontent.com/34899110/350288524-79714fe5-2c13-4d97-a832-a9d298b00e12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTMwMzAsIm5iZiI6MTcyMTQxMjczMCwicGF0aCI6Ii8zNDg5OTExMC8zNTAyODg1MjQtNzk3MTRmZTUtMmMxMy00ZDk3LWE4MzItYTlkMjk4YjAwZTEyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE4MTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0NDQ2OWMzOGY0MjYwNjU1YTFlYzg2MzY4ZGZhNTg2MDNmMGU2YjBkZGMwMWQ5NmM1N2UxZjFjNzBjYjY1ZWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mti4LCMyES6ijDzGvoUTtUy6vZ_yXGaylOtjhO-0LnY">
> > <img alt="Screenshot 2024-07-18 at 11 40 50 PM" width="1752" src="https://private-user-images.githubusercontent.com/34899110/350286168-fdf57821-70d0-4718-b6e8-d8635b9a5fcf.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MTMwMzAsIm5iZiI6MTcyMTQxMjczMCwicGF0aCI6Ii8zNDg5OTExMC8zNTAyODYxNjgtZmRmNTc4MjEtNzBkMC00NzE4LWI2ZTgtZDg2MzViOWE1ZmNmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE4MTIxMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNiNjNlY2E2YjRjNzhjZGE1OTU2NjhiMjlhYTIxYjAzOGQxNzkzZjYyMThmZjE4MGYyMjYzY2M2MGYwYWUyNmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tCqnCGDAEnpFcPdVkfwtLV8ONmoOxC-TrVtxfIFeT_Q">
> 
> Thanks for letting me know, please create a new issue highlighting this. Thank you

Okay, will do.
