### ISSUE TITLE
[BUG] Refreshing the chat page displays encrypted messages

### ISSUE THREAD

**Issue by TysonThurman** [Dun-sin/Whisper#630]
### Description

If you refresh the chat screen a couple of times, it'll change the message(s) to this sort of encrypted version of the message. Refreshing again will change it back to its normal text but then it can be replicated again after a couple more refreshes.

### Screenshots

<img width="1752" alt="Screenshot 2024-07-18 at 11 45 06 PM" src="https://github.com/user-attachments/assets/79714fe5-2c13-4d97-a832-a9d298b00e12">
<img width="1752" alt="Screenshot 2024-07-18 at 11 40 50 PM" src="https://github.com/user-attachments/assets/fdf57821-70d0-4718-b6e8-d8635b9a5fcf">

### Additional information

You can replicate this issue by sending any message in the chat and then refresh the page a couple of times.

### 🥦 Browser

Brave

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions on the discord server. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by Dun-sin** [comment]
I suggest, we decrypt the message before displaying it and if we don't have the keys atm, we use a loading screen to let the users know it's loading

**Comment by TysonThurman** [comment]
My apologies, I got tied up with work and wasn't able to work on this the last couple of days. I am just getting back on it to try and resolve this issue. Is there a way I can have a couple of extra days to get this completed? If not, no worries. I will try to complete it within the next day or so.

**Comment by Dun-sin** [comment]
> My apologies, I got tied up with work and wasn't able to work on this the last couple of days. I am just getting back on it to try and resolve this issue. Is there a way I can have a couple of extra days to get this completed? If not, no worries. I will try to complete it within the next day or so.

no problem, you get 4 days extra.

**Comment by TysonThurman** [comment]
Awesome, thank you 😎

**Comment by TysonThurman** [comment]
@Dun-sin I don't think I'll be able to find the fix for this issue in time so please go ahead and unassign me. I will continue to try and find a solution but I don't want to hold up another developer that may want to put in a pull request for this issue. Sorry for the inconvenience. I look forward to contributing more but I've run out of time on this one.

**Comment by Dun-sin** [comment]
> @Dun-sin I don't think I'll be able to find the fix for this issue in time so please go ahead and unassign me. I will continue to try and find a solution but I don't want to hold up another developer that may want to put in a pull request for this issue. Sorry for the inconvenience. I look forward to contributing more but I've run out of time on this one.

thanks for trying, do come back when you think you want to try again

**Comment by spy235** [comment]
@Dun-sin  
Can i try? basically I want to contribute to open source projects.but i don't know where to start from I know JavaScript and reactJs.
can you please guide me how can I start contributing to open source??

**Comment by Dun-sin** [comment]
> @Dun-sin Can i try? basically I want to contribute to open source projects.but i don't know where to start from I know JavaScript and reactJs. can you please guide me how can I start contributing to open source??

I would not recommend this issue to a beginner to open source or coding in general, but first contribute to this → https://github.com/firstcontributions/first-contributions

and come back and try to contribute to this

**Comment by Golu7667** [comment]
I can work on this issue. If you have no problem, please assign it to me.
