### ISSUE TITLE
[BUG] Reply chat text not show 

### ISSUE THREAD

**Issue by Golu7667** [Dun-sin/Whisper#631]
### Description

The reply chat text is not showing.

### Screenshots

![whisperreply](https://github.com/user-attachments/assets/398b6010-a8f3-42dd-ae13-f6eda51a50a2)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Timi16** [comment]
Please can I work on this issue

**Comment by Golu7667** [comment]
I want to work on this issue. Can you assign it to me

**Comment by Dun-sin** [comment]
> I want to work on this issue. Can you assign it to me

Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
