### ISSUE TITLE
[FEATURE] change minimum age to 12

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#634]
### Description

Change the number from 1 to 12

https://github.com/Dun-sin/Whisper/blob/71dd0ba6069456da93bb25a786682d47cb322d5b/client/src/pages/Profile.jsx#L213-L218

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by DanonymousCoder** [comment]
I would like to work on this

**Comment by Dun-sin** [comment]
> I would like to work on this

Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by DanonymousCoder** [comment]
I've created a pull request. Please kindly review
