### ISSUE TITLE
[DOCS] add extra variables to env_sample

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#638]
### Description

add this two to -> https://github.com/Dun-sin/Whisper/blob/main/server/.env_sample
```
MAILTRAP_TOKEN=<mailtraptoken>
MAILTRAP_EMAIL=mailtrap@demomailtrap.com
```

and this to -> https://github.com/Dun-sin/Whisper/blob/main/client/.env_sample
```
VITE_SECRET_KEY=whisper123
```

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by ChinoUkaegbu** [comment]
Hi, I'd like to be assigned to this issue!

**Comment by Dun-sin** [comment]
> Hi, I'd like to be assigned to this issue!

Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
