### ISSUE TITLE
[BUG] logout dialogue still showing after user has logged out

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#644]
### Description

<as the title says>

### Screenshots

![image](https://github.com/user-attachments/assets/97426956-f4a5-4405-a086-d5a6a514751f)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by malakbenr** [comment]
Can you assign me this issue @Dun-sin ?

**Comment by Dun-sin** [comment]
> Can you assign me this issue @Dun-sin ?

@malakbenr Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by malakbenr** [comment]
Thank you for the guidance! I'll make sure to thoroughly read the issue description and follow the guidelines closely. I'll reach out if I have any questions. Looking forward to contributing!
