### ISSUE TITLE
[DOCS] Fix anchor ref in contributing.md

### ISSUE THREAD

**Issue by Kaylen7** [Dun-sin/Whisper#649]
## Description
The link in word `here` points to an anchor that does not exist in file: 

````
### Pull Request guidelines

- Don't create a pull request on an issue that doesn't exist, create an issue first and if the changes you are proposing are said to be okay, you can go ahead and create a pull request
- Don't work on the main branch, create your own branch by following the instructions [here](#-how-to-make-a-pull-request)
````
Maybe it should point here: `#### 👌🏾 How to fill a pull request template(Text)` ?

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Yep, you're correct @Kaylen7 will assign it to you, I'm guessing this means you've read the contributing guidelines so just go ahead and create a PR💪🏽
