### ISSUE TITLE
[DOCS] add Google Analytics to env_sample

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#652]
### Description

Add this 
```
VITE_GOOGLE_ANALYTICS=123
```

to this file:
https://github.com/Dun-sin/Whisper/blob/main/client/.env_sample

**Comment by sumitnair26** [comment]
Hello can i pick this issue ?

**Comment by Dun-sin** [comment]
> Hello can i pick this issue ?

@sumitnair26 
Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions here or on our discord server(in readme). Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by sumitnair26** [comment]
Hello @Dun-sin i have added VITE_GOOGLE_ANALYTICS in **.env_sample**
create PR  https://github.com/Dun-sin/Whisper/pull/654, please review
