### ISSUE TITLE
[FEATURE] add the ability to block users

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#655]
### Description

The feature should only be available to users that have an account
the flow should look like this:
- user clicks on block
- checks if the user has an account → if not, show an alert saying they should create an account to have the feature to block someone
- if they do have an account, we send a request to the backend, with the user ID of who they want to block

### Additional information

> NOTE: the steps aren't definite, if you have a better way of doing it, don't hesitate to let me know
> NOTE 2: when forking the project, fork from the branch linked to this issue

**Comment by NishantPadhi** [comment]
Hi,
I want to work on this issue. Can I work on this?

**Comment by Dun-sin** [comment]
> Hi, I want to work on this issue. Can I work on this?

sure, before i do that, please give me back the instructions of this issue in the way you understand it

**Comment by NishantPadhi** [comment]
There will be 1 block button. When clicking the button, we should check if the user has an account. If they don't have an account, we need to show some alert saying in order to have the blocking feature. If they have an account, we can make 1 API call to block the user.

**Comment by Dun-sin** [comment]
> There will be 1 block button. When clicking the button, we should check if the user has an account. If they don't have an account, we need to show some alert saying in order to have the blocking feature. If they have an account, we can make 1 API call to block the user.

you're missing something

**Comment by azr-arch** [comment]
can i get this ?

**Comment by Dun-sin** [comment]
> can i get this ?

will see if @NishantPadhi can get the instructions correctly, if they don't then you can have it

**Comment by azr-arch** [comment]
how long we will wait @Dun-sin  ?

**Comment by Dun-sin** [comment]
> how long will we wait @Dun-sin  ?
> 

I will just assign it to you now. Thanks for the reminder.

Make sure to read the issue description carefully and ask if you have questions on the discord server. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
