### ISSUE TITLE
[FEATURE] Sepreate searching and foundUser into different routes

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#659]
### Description

when a user clicks on search, it takes them to the `foundUser` route immediately instead of staying on the `searching` route until a chat partner has been found

### Screenshots

https://github.com/user-attachments/assets/ad9e3b29-a12c-4647-8435-59fa38b84661

### Additional information

You'll find the route definition here
https://github.com/Dun-sin/Whisper/blob/dbec99c68f63c606647ea2cef1d458a72ae83b1b/client/src/App.jsx#L50-L57

**Comment by malakbenr** [comment]
Hi, can I work on this issue ?

**Comment by Dun-sin** [comment]
> Hi, can I work on this issue ? 

Sure, go for it

**Comment by Dun-sin** [comment]
hi @malakbenr you have 2 more days to raise a PR, else you'll be unassigned.

**Comment by kalvakeerthi** [comment]
I would like to work on this issue. Can you please assign this to me?

**Comment by Kritik-Kapoor** [comment]
Can I get this issue ?

**Comment by VijeshVS** [comment]
Hi, can I work on this issue ?

**Comment by ayushmaz** [comment]
Hi @Dun-sin , Can I pick this item?

**Comment by Dun-sin** [comment]
> Hi @Dun-sin , Can I pick this item?

Sure @ayushmaz, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
