### ISSUE TITLE
[FEATURE] move menu toggle into it's own component

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#660]
### Description

For cleaner code, move this to its own component and call it in Anonymous.jsx component

https://github.com/Dun-sin/Whisper/blob/dbec99c68f63c606647ea2cef1d458a72ae83b1b/client/src/components/Anonymous.jsx#L153-L163

### Additional Information
Provide a screen recording of the menu toggle working

**Comment by Bridgetamana** [comment]
I can do this

**Comment by Priyanshu-2005** [comment]
Hey @Dun-sin  I want to work on this issue kindly assign it to me.

**Comment by Dun-sin** [comment]
sorry @Priyanshu-2005 @Bridgetamana asked first, but @Priyanshu-2005 you can go through other good first issues and indicate there instead

**Comment by Dun-sin** [comment]
> I can do this

Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by Dun-sin** [comment]
@Priyanshu-2005 are you still up for this?

**Comment by Priyanshu-2005** [comment]
@Dun-sin  Yes i am willing to contribute Kindly assign this issue to me.

**Comment by Dun-sin** [comment]
> @Dun-sin Yes i am willing to contribute Kindly assign this issue to me.

alright then, Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
