### ISSUE TITLE
[OTHER] move the message list to its own component

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#663]
### What would you like to share?
https://github.com/Dun-sin/Whisper/blob/dbec99c68f63c606647ea2cef1d458a72ae83b1b/client/src/components/Chat.jsx#L442-L585

### Additional information
Break it down into subcomponents as well:
- create a component for when we're displaying the bad word warning https://github.com/Dun-sin/Whisper/blob/dbec99c68f63c606647ea2cef1d458a72ae83b1b/client/src/components/Chat.jsx#L499-L515
- create a component for status https://github.com/Dun-sin/Whisper/blob/dbec99c68f63c606647ea2cef1d458a72ae83b1b/client/src/components/Chat.jsx#L554-L579

**Comment by zainab-a-ali** [comment]
can I be assigned this issue?

**Comment by zainab-a-ali** [comment]
Can I be assigned this issue as well @Dun-sin ?

**Comment by wheval** [comment]
I want to work on this issue. I can create the component asap. Thanks

**Comment by Dun-sin** [comment]
> I want to work on this issue. I can create the component asap. Thanks

sure @wheval, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions on the discord server. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
