### ISSUE TITLE
[OTHER] move all socket function in chat.jsx into chatSocket.js

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#664]
### What would you like to share?

The chat component
https://github.com/Dun-sin/Whisper/blob/dbec99c68f63c606647ea2cef1d458a72ae83b1b/client/src/components/Chat.jsx

The chatSocket file:
https://github.com/Dun-sin/Whisper/blob/dbec99c68f63c606647ea2cef1d458a72ae83b1b/client/src/lib/chatSocket.js

**Comment by damirgros** [comment]
Can I work on this issue? Also I have a question, what do you want to be moved to chatSocket.js?
Only this?
```js
	const emitTyping = useCallback((boolean) => {
		socket.timeout(5000).emit(NEW_EVENT_TYPING, { chatId: app.currentChatId, isTyping: boolean });
	}, []);
```

**Comment by Dun-sin** [comment]
> Can I work on this issue? Also I have a question, what do you want to be moved to chatSocket.js?
> Only this?
> ```js
> 	const emitTyping = useCallback((boolean) => {
> 		socket.timeout(5000).emit(NEW_EVENT_TYPING, { chatId: app.currentChatId, isTyping: boolean });
> 	}, []);
> ```
> 

No `all` socket functions, meaning find all the socket emit or on methods and the functions they put as a second argument should be moved.

**Comment by azr-arch** [comment]
hey can i get tbis one

**Comment by Dun-sin** [comment]
> hey can i get this ?
> 

Sure @azr-arch , thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions on the discord server. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by Dun-sin** [comment]
> hey @Dun-sin, do you know how to fix this 
> ```
> C:\Users\Desktop\Github Repositories\Whisper\server\utils\lib.js:391
>   message = CryptoJS.AES.encrypt(message, secretKey).toString();
>                                           ^
> 
> ReferenceError: secretKey is not define
> ```
> ?

Can you track where secretKey is coming from?

**Comment by azr-arch** [comment]
> > hey @Dun-sin, do you know how to fix this
> > ```
> > C:\Users\Desktop\Github Repositories\Whisper\server\utils\lib.js:391
> >   message = CryptoJS.AES.encrypt(message, secretKey).toString();
> >                                           ^
> > 
> > ReferenceError: secretKey is not define
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ?
> 
> Can you track where secretKey is coming from?

the whole file doesn't have any imports or variables for secretKey

**Comment by Dun-sin** [comment]
> > > hey @Dun-sin, do you know how to fix this
> > > ```
> > > C:\Users\Desktop\Github Repositories\Whisper\server\utils\lib.js:391
> > >   message = CryptoJS.AES.encrypt(message, secretKey).toString();
> > >                                           ^
> > > 
> > > ReferenceError: secretKey is not define
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ?
> > 
> > 
> > Can you track where secretKey is coming from?
> 
> the whole file doesn't have any imports or variables for secretKey

is this blocking your PR? if it is, move the other socket functions and leave the one for editing

**Comment by azr-arch** [comment]
there are already some bugs with the current version, like when you try to delete or copy the message, error occurs. so how do i record 

> > > > hey @Dun-sin, do you know how to fix this
> > > > ```
> > > > C:\Users\Desktop\Github Repositories\Whisper\server\utils\lib.js:391
> > > >   message = CryptoJS.AES.encrypt(message, secretKey).toString();
> > > >                                           ^
> > > > 
> > > > ReferenceError: secretKey is not define
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > ?
> > > 
> > > 
> > > Can you track where secretKey is coming from?
> > 
> > 
> > the whole file doesn't have any imports or variables for secretKey
> 
> is this blocking your PR? if it is, move the other socket functions and leave the one for editing

its not blocking, i'll it for you. 
thanks for helping

**Comment by Dun-sin** [comment]
> there are already some bugs with the current version, like when you try to delete or copy the message, error occurs. so how do i record 
> 
> > > > > hey @Dun-sin, do you know how to fix this
> > > > > ```
> > > > > C:\Users\Desktop\Github Repositories\Whisper\server\utils\lib.js:391
> > > > >   message = CryptoJS.AES.encrypt(message, secretKey).toString();
> > > > >                                           ^
> > > > > 
> > > > > ReferenceError: secretKey is not define
> > > > > ```
> > > > > 
> > > > > 
> > > > >     
> > > > >       
> > > > >     
> > > > > 
> > > > >       
> > > > >     
> > > > > 
> > > > >     
> > > > >   
> > > > > ?
> > > > 
> > > > 
> > > > Can you track where secretKey is coming from?
> > > 
> > > 
> > > the whole file doesn't have any imports or variables for secretKey
> > 
> > is this blocking your PR? if it is, move the other socket functions and leave the one for editing
> 
> its not blocking, i'll it for you. 
> thanks for helping 


Don't worry about recording🙌🏾

**Comment by azr-arch** [comment]
message copy, edit and delete are not working, look into them too
