### ISSUE TITLE
[OTHER] define the hasActiveReply ternary condition outside of the class

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#665]
### What would you like to share?

Move this:
https://github.com/Dun-sin/Whisper/blob/dbec99c68f63c606647ea2cef1d458a72ae83b1b/client/src/components/Chat.jsx#L447-L448

here:
https://github.com/Dun-sin/Whisper/blob/dbec99c68f63c606647ea2cef1d458a72ae83b1b/client/src/components/Chat.jsx#L439-L440

**Comment by zainab-a-ali** [comment]
Can I be assigned this issue?

**Comment by Dun-sin** [comment]
> Can I be assigned this issue?

Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
