### ISSUE TITLE
[OTHER] remove the fragment in messageInput

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#668]
### What would you like to share?

https://github.com/Dun-sin/Whisper/blob/dbec99c68f63c606647ea2cef1d458a72ae83b1b/client/src/components/Chat/MessageInput.jsx#L61-L118

**Comment by Tarunkumarkanakam** [comment]
I would like to contribute to this project, Can you brief me on what exactly needs to be done?

**Comment by Dun-sin** [comment]
> I would like to contribute to this project, Can you brief me on what exactly needs to be done?

sure, a react fragment is used to group elements together without using an actually element and it's represented with `<>` but since that component only has one fragment child we can remove the fragment and just return the form

**Comment by Dun-sin** [comment]
@Tarunkumarkanakam  the time assigned to this Issue is over, you're now unassigned. Thanks for trying to contribute, you're free to ask to work on other issues, if you can meet up with the time assigned.

**Comment by muhammednithal** [comment]
Can I work on this issue
