### ISSUE TITLE
[OTHER] Use npm ci

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#67]
### What would you like to share?

In Github actions, `npm install` is used to install dependencies, but using `npm ci`is much better

Change Github actions to use `npm ci` instead of `npm install`

**Comment by hasnainmakada-99** [comment]
Hey @Dun-sin  I would like to try to solve this one

**Comment by Dun-sin** [comment]
> Hey @Dun-sin I would like to try to solve this one

Yes, go ahead

**Comment by hasnainmakada-99** [comment]
Hey @Dun-sin I just have to make changes in the yaml files to change the `npm install` to `npm ci `  right ?
