### ISSUE TITLE
[BUG] Chat Edit functionality is not working.

### ISSUE THREAD

**Issue by Golu7667** [Dun-sin/Whisper#671]
### Description

chat edit functionality is not working .So, I want to work on this issue.

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Edit your PR with the actual problem. `not working properly` doesn't help with us documenting issues
