### ISSUE TITLE
[BUG] seen message text not seen in light mode

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#678]
### Description

we can only see it when it's highlighted, so change the text color to this in light mode #011627

### Screenshots

![brave_ckRC5wl00H](https://github.com/user-attachments/assets/6da1c5f2-c844-4400-9f2b-aa81f7d73e4c)

**Comment by AlexVCS** [comment]
Hi there, I'd like to work on this issue. Can you assign it to me please?

**Comment by AlexVCS** [comment]
.take

**Comment by Dun-sin** [comment]
> Hi there, I'd like to work on this issue. Can you assign it to me please?

Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by AlexVCS** [comment]
> > Hi there, I'd like to work on this issue. Can you assign it to me please?
> 
> Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

Thanks! I'm running both the client and server on my machine. Is there a way for me to generate a random buddy to chat with? I'd like to recreate the issue on my machine and then be able to see if my changes are right and visible.

**Comment by Dun-sin** [comment]
> > > Hi there, I'd like to work on this issue. Can you assign it to me please?
> > 
> > Sure, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
> 
> Thanks! I'm running both the client and server on my machine. Is there a way for me to generate a random buddy to chat with? I'd like to recreate the issue on my machine and then be able to see if my changes are right and visible.

Please go through the readme of how to run the project, feel free to ask questions afterwards
