### ISSUE TITLE
[FEATURE] chat menu

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#68]
### Description

The menu icon should be clickable and have the option to close a chat when a chat starts

### Screenshots

![image](https://user-images.githubusercontent.com/78784850/185900533-496b56b4-617c-4f4b-b724-9147e8ffe771.png)

**Comment by mathiasayivor** [comment]
Was this implemented?

**Comment by Dun-sin** [comment]
> Was this implemented?

nope, i just added the logo

**Comment by mathiasayivor** [comment]
oh ok

**Comment by JhoanAlvear** [comment]
i can help with the problem

**Comment by Dun-sin** [comment]
> i can help with the problem
> 

Sure go for it, thanks for wanting to contribute
