### ISSUE TITLE
[BUG] <what is the issue>

### ISSUE THREAD

**Issue by sanaullah1266** [Dun-sin/Whisper#693]
### Description

#fixed please make sure your ui is  loo
king good its look not that much professional I want to improve the home page of this website

### Additional information

![Capture](https://github.com/user-attachments/assets/c8be3036-5216-4382-b9f5-81f0dba930f2)

### 🥦 Browser

Google Chrome

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
hi @sanaullah1266 thanks for wanting to improve whisper, not sure what you want to improve, but if you are sure of spefici things you want to add and why they should be added. Please create a new issue filling the template properly and letting us know what we can do to improve whisper
