### ISSUE TITLE
[FEATURE] Prevent editing/deleting of old messages

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#705]
### Description

It will be really helpful to prevent users from deleting/editing their messages after they've been sent for some time (e.g after 15 minutes).
This will help promote integrity. Messaging platforms like WhatsApp have already implemented this feature, preventing users from editing/deleting messages sent for over 15 minutes

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

None

**Comment by azr-arch** [comment]
Can i get this?

**Comment by Dun-sin** [comment]
> Can i get this? 

Sure @azr-arch, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions on the discord server. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. 

For this it is better to not show the option at all after the time has passed, check for it in the frontend and the backend.

Good luck!

**Comment by azr-arch** [comment]
where do i put constants like this - `const FIFTEEN_MINUTES = 15 * 60 * 1000;` ?
