### ISSUE TITLE
[BUG] delete unneeded line of code from lib.js in server folder

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#708]
### Description

Delete this 2 lines:
- https://github.com/Dun-sin/Whisper/blob/36bd89f833371ad48ae28cff60839f178aadb700/server/utils/lib.js#L391
- https://github.com/Dun-sin/Whisper/blob/36bd89f833371ad48ae28cff60839f178aadb700/server/utils/lib.js#L3

> Note: Please read the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

**Comment by wheval** [comment]
Hello @Dun-sin, I would love to work on this issue.
