### ISSUE TITLE
[FEATURE] add prettier to github actions

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#711]
We need to add prettier GitHub actions, so when a PR is raised it auto corrects any lint issues

> Note: Please read the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

**Comment by joshua-jinu** [comment]
hey @Dun-sin, i would like to work on this, can i be assigned

**Comment by Dun-sin** [comment]
> hey @Dun-sin, i would like to work on this, can i be assigned



Sure @joshua-jinu, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions on the discord server. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!
