### ISSUE TITLE
[DOCS] better folder structure

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#72]
### Description

**_Problem_**: The structure of the project is bad, it goes in the format of component ⇾ Page + Logical solution + CSS styles

**_Solution_**: pages, components and styles with its own folder.

If you know a better folder structure for react applications, you can send a YouTube video link (most preferred) or an article on how the structure works/looks like

**Comment by rajanmagar** [comment]
Solution: A perfect and ideal solution for what you are looking for. https://blog.webdevsimplified.com/2022-07/react-folder-structure/

**Comment by Dun-sin** [comment]
> Solution: A perfect and ideal solution for what you are looking for. https://blog.webdevsimplified.com/2022-07/react-folder-structure @Dun-sin

Thank you for this
