### ISSUE TITLE
[BUG] Editing Message not working and causing app to crash

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#722]
### Description

in sockets for editMessage we get this error:
```C:\Users\jesud\Documents\Programming\Whisper\server\sockets\editMessage.js:21
      if (!isMessageEditableOrDeletable(chatId, messageId)) {
      ^

ReferenceError: isMessageEditableOrDeletable is not defined
```
### Steps to Reproduce

Set up the project as usual or go to the live link
Join a chat
Send a Message
Click on the dropdown icon
Click on editing the message

**Comment by amishabaraskar** [comment]
Hi @Dun-sin ,

I want to work on this issue. I can check the problem with the socket. Thanks

**Comment by Dun-sin** [comment]
> I want to work on this issue. I can check the problem with the socket. Thanks

Sure @amishabaraskar, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by Dun-sin** [comment]
@amishabaraskar the time allocated to this PR is over, please submit your PR today
