### ISSUE TITLE
[FEATURE] let users know what happens when they don't allow notifications

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#730]
### Description

Currently if users get sent the permission to allow whisper to send them a notification, and they reject it, it just stops there.

we need a dialog that tells them what happens if they don't accept it, something along the lines of
`We noticed you've blocked Whisper from sending notifications. Are you sure you don’t want to enable them? Notifications help you stay updated, remember who you're talking to, and ensure you dont miss important messages.`

and they get the option to turn it on or still leave it block. If they pick to turn it on then we rerequest the permission to allow notifications.

### Additional information

Summary of tasks:
- [ ] Send a dialog when users decline whisper from sending them notifications
- [ ] the dialog should have two options
- [ ] the first option should be `Keep Blocked` that just closes the dialog and does nothing 
- [ ] the second option should be `Allow` that resends the permission request for sending notification and also closes the dialog

**Comment by AdarshKumar02291** [comment]
Can you assign me this issue .

**Comment by Dun-sin** [comment]
> Can you assign me this issue .

Sure @AdarshKumar02291, thanks for wanting to contribute. Make sure to read the issue description carefully and ask if you have questions. Follow the rules [here](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md#rules), or your PR won't be accepted and will be closed. Good luck!

**Comment by AdarshKumar02291** [comment]
Hy @Dun-sin i did a bit of research .  First three steps are completed . It seems there isn't any api that resets the permission once it is blocked . One way to handle is given in this blog [https://pushpad.xyz/blog/reset-the-denied-permission-for-notifications](url) . Let me know how to handle step 4

**Comment by AdarshKumar02291** [comment]
i could but the recalling doesn't do any thing . The dialouge closes and thats it regardless of the options chosen by the user in the dialog
