### ISSUE TITLE
[FEATURE] <what do you have to add>

### ISSUE THREAD

**Issue by jolanipekun** [Dun-sin/Whisper#735]
### Description

Units tests for controllers and models

### Additional information

I would like to include some units test to add to the robustness and quality of the apllication using jest and supertest.

### 👀 Have you checked if this issue has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Contributing Guidelines?

- [X] I have read and understood the rules in the [Contributing Guidelines](https://github.com/Dun-sin/Whisper/blob/main/CONTRIBUTING.md)

### Are you willing to work on this issue ?

Yes I am willing to submit a PR!

**Comment by Dun-sin** [comment]
Thanks for raising this @jolanipekun, but this isn't something we want right now.

I do encourage you to feel free to raise other issues🙌🏽
