### ISSUE TITLE
Responsiveness Issue

### ISSUE THREAD

**Issue by Coding-Hashira** [Dun-sin/Whisper#75]
### Description

In small devices, everything in the start (or search) screen appears quite big. Even in other tabs, text appears quite big.

### Screenshots

![IMG_20220911_184141](https://user-images.githubusercontent.com/96920778/189529677-0519f554-e339-46e0-88d7-523514d20503.jpg)

**Comment by Dun-sin** [comment]
Yeah I know about this, this isn't an issue right now, focusing on things with actual priority like making it work first🙂

Thanks for pointing this out tho

**Comment by pushkaraj2007** [comment]
Hey @Dun-sin,

Should I work on this, or let it go for now?

**Comment by Dun-sin** [comment]
Was going to say let it go, but do it

**Comment by pushkaraj2007** [comment]
Thanks for assigning, @Dun-sin
