### ISSUE TITLE
[BUG] Search for someone didn't work

### ISSUE THREAD

**Issue by unkwnownGriot** [Dun-sin/Whisper#77]
### Description

I'm actually on the live demo website and whenever  click on the start button it displays a page with **searching...** without displaying anything else 

### Screenshots

![2022-09-15 12_09_08-Window](https://user-images.githubusercontent.com/83823820/190400079-992532f8-30e0-4fb0-b949-1bd9d5c25684.png)

**Comment by Dun-sin** [comment]
The app latest version isn't hosted yet because of this bug #71 I updated the about so people will know this app isn't functioning yet

**Comment by unkwnownGriot** [comment]
so how can i help you to fix this bug ? In the version of the project i have i can't even send messages

**Comment by Dun-sin** [comment]
> so how can i help you to fix this bug ? In the version of the project i have i can't even send messages

As I said it's not hosted, so you have to clone it and all
