### ISSUE TITLE
[FEATURE] Improve on random user pairing

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#83]
### Description

Currently, it's unclear if users are being properly paired. We need to get the pairing feature fully working

**Comment by Dun-sin** [comment]
How is it unclear?

**Comment by mathiasayivor** [comment]
On the `/founduser` route, I sometimes get matched to myself, or just a loading text ('Searching.....').

**Comment by mathiasayivor** [comment]
It's unclear if that's for testing purposes or if it's a bug.
We need to get the pairing feature fully working now hence contributing to our aim toward an MVP asap

**Comment by Dun-sin** [comment]
> On the `/founduser` route, I sometimes get matched to myself, or just a loading text ('Searching.....').

Oh yeah I noticed that

**Comment by mathiasayivor** [comment]
Can I hop on this one?

**Comment by Dun-sin** [comment]
Sure, is chatting working better now?

**Comment by mathiasayivor** [comment]
> Sure, is chatting working better now?

![Screenshot from 2022-09-21 17-30-22](https://user-images.githubusercontent.com/74247733/191572038-08a4af18-a713-48ad-a3fb-74160115da82.png)

So far, this is how it's going. I'm not getting any rendering issues, etc

**Comment by Dun-sin** [comment]
Isn't that repeating twice?

**Comment by mathiasayivor** [comment]
yh

**Comment by Dun-sin** [comment]
> yh

Yeah that's what I meant by rendering issue

**Comment by mathiasayivor** [comment]
Oh I see now

**Comment by mathiasayivor** [comment]
I'm working on it anyways

**Comment by mathiasayivor** [comment]
Is it possible to close two issues at once?
i.e issue #71 and this one

**Comment by Dun-sin** [comment]
@jasham wanted to work on the rendering issue

**Comment by mathiasayivor** [comment]
Oh ok

**Comment by mathiasayivor** [comment]
Would leave that part for now

**Comment by jasham** [comment]
Thanks @Dun-sin & @mathiasayivor. I will start working on it now.

**Comment by jasham** [comment]
@Dun-sin @mathiasayivor is context-api integrated with the project ??

**Comment by Dun-sin** [comment]
> @Dun-sin @mathiasayivor is context-api integrated with the project ??

Yes
