### ISSUE TITLE
[FEATURE] Add Typescript Support

### ISSUE THREAD

**Issue by mathiasayivor** [Dun-sin/Whisper#85]
### Description

As the project grows, we're gonna need typescript to at least help with typing support.
Currently, we're writing types using jsdoc, which is a bit verbose

NOTE: This is not a priority atm, but to serve as a todo

**Comment by BurhanRaja** [comment]
Hello @mathiasayivor,
Can I contribute to this issue-feature?

**Comment by BurhanRaja** [comment]
Hello @mathiasayivor 
Can I contribute to this **issue-feature**?
