### ISSUE TITLE
[BUG] SSO using Google caused in errors

### ISSUE THREAD

**Issue by Gismo1337** [Dun-sin/Whisper#87]
### Description

Never logged in before.
Used Google as sign in

**Got instant errors at homescreen:**
```
GET https://whisper-app-api.herokuapp.com/api/v1/provider/getProviderServiceRequests/undefined
GET https://whisper-app-api.herokuapp.com/api/v1/app/getUserActiveSubscriptions/undefined
GET https://whisper-app-api.herokuapp.com/api/v1/app/getFriends/undefined
```

### Screenshots

![grafik](https://user-images.githubusercontent.com/6397577/192773619-53fbe94b-9cc8-4a96-a0f6-93425e22fc60.png)
![grafik](https://user-images.githubusercontent.com/6397577/192773659-84a46b7c-8759-49b7-b647-986a43d31835.png)

**Comment by Dun-sin** [comment]
By google do you mean your gmail?
