### ISSUE TITLE
[BUG] errors visiting wallet

### ISSUE THREAD

**Issue by Gismo1337** [Dun-sin/Whisper#88]
### Description

Visiting Wallet caused errors
See Screenshot

### Screenshots

![grafik](https://user-images.githubusercontent.com/6397577/192773926-85820c7f-ef61-44dc-899e-5df950c1d47b.png)

**Comment by Dun-sin** [comment]
I think you are at the wrong project

**Comment by mathiasayivor** [comment]
@Gismo1337 I think you're on the wrong repository

**Comment by Dun-sin** [comment]
> > @Gismo1337 I think you're on the wrong repository
> 
> hmm whisper chat?

try the link in about

**Comment by Gismo1337** [comment]
> > > @Gismo1337 I think you're on the wrong repository
> > 
> > hmm whisper chat? I clicked on the link DEMO in read me of this repo here
> 
> where did you get the link from?

Readme.md
demo

**Comment by Dun-sin** [comment]
Anyway, where ever you got the link to this repo is pointing to the wrong place.

You can check out this project too, if you like

**Comment by Gismo1337** [comment]
> > > > > @Gismo1337 I think you're on the wrong repository
> > > > 
> > > > 
> > > > hmm whisper chat? I clicked on the link DEMO in read me of this repo here
> > > 
> > > 
> > > where did you get the link from?
> > 
> > 
> > Readme.md demo
> 
> of this repo?

Yes

https://whisper.vercel.app/
![grafik](https://user-images.githubusercontent.com/6397577/192776247-028574c1-e097-46f8-970c-2e2296983495.png)

**Comment by Dun-sin** [comment]
This isn't my project, very different from the one in this project's about

**Comment by Dun-sin** [comment]
I see where the problem is coming from

**Comment by Dun-sin** [comment]
> I see where the problem is coming from

right repo, wrong project

**Comment by Gismo1337** [comment]
you are kidding.
this is you?
![grafik](https://user-images.githubusercontent.com/6397577/192776662-e57cf551-9cba-4e7f-93d4-1080af5a2e5b.png)

scroll down in readme to this position and click on whisper
![grafik](https://user-images.githubusercontent.com/6397577/192776786-6e62447d-6654-41b2-ac2d-95a7d7d37649.png)

its this link:
https://whisper.vercel.app/

and i am right now in the issues of this: 
![grafik](https://user-images.githubusercontent.com/6397577/192776965-00a4664a-a3f9-49e1-80cf-8f251d9fba02.png)


i am hard confused

**Comment by Dun-sin** [comment]
@Gismo1337 as i said, i see where the problem is coming from, you are in the right repo that was linked to the wrong project.

Apologies for the confusion, it has been fixed with the proper link in the README file. Thanks for pointing it out

Thank you for wanting to contribute, I hope you still do so
