### ISSUE TITLE
[DOCS] wrong link in README

### ISSUE THREAD

**Issue by Dun-sin** [Dun-sin/Whisper#92]
### Description

`View Demo` has a wrong link, replace it with the proper link to the site, which can be found in about section of this repo

### Screenshots

![image](https://user-images.githubusercontent.com/78784850/192782782-0b489f48-503a-491d-b603-f30a2cbc6eee.png)

**Comment by cesar-codes** [comment]
Hi @Dun-sin - this seems like a cool project and I'd like to help. May I claim this issue, please?

**Comment by Dun-sin** [comment]
Definitely, thanks for wanting to contribute

**Comment by RAM844** [comment]
Hey @Dun-sin , is this issue resolved?
