### ISSUE TITLE
[FEATURE] Open graph

### ISSUE THREAD

**Issue by Nakamcode** [Dun-sin/Whisper#97]
### An open graph is a preview image that shows when a link is shared on social media
_for more info about open graphs read the blog below_
https://ahrefs.com/blog/open-graph-meta-tags/

### Screenshots

![captures_chrome-capture-2022-9-2 (1)](https://user-images.githubusercontent.com/89482825/193437212-ab0a3b39-da89-48b6-967e-0ce96a02174b.png)

**Comment by mihir1739** [comment]
I would like to work on it..

**Comment by Dun-sin** [comment]
@mihir1739 an update pls?
